jest.mock('../../decisions/decisionEngineService', () => ({
  refreshDecisionRecommendations: jest.fn(),
}));

jest.mock('../hiringAutomationService', () => {
  const actual = jest.requireActual('../hiringAutomationService');
  return {
    ...actual,
    generateHiringAutomationActions: jest.fn(),
    queueHiringAutomationSideEffects: jest.fn(),
  };
});

jest.mock('../../predictions/predictionEngineService', () => ({
  listPredictionInsightsByIds: jest.fn().mockResolvedValue([]),
}));

jest.mock('../../../../../../../core/actions/actionEngine', () => {
  const actual = jest.requireActual('../../../../../../../core/actions/actionEngine');
  return {
    ...actual,
    createActionEngine: jest.fn(),
  };
});

import type { Prisma } from '@prisma/client';
import { canTransitionActionStatus, normalizeActionStatus } from '../../../../../../../core/actions/actionHistory';
import type { RecommendedAction } from '../../../../../../../core/actions/actionEngine';
import { createActionEngine } from '../../../../../../../core/actions/actionEngine';
import { refreshDecisionRecommendations } from '../../decisions/decisionEngineService';
import {
  dismissActionRecommendation,
  executeActionRecommendation,
  refreshActionRecommendations,
  saveActionRecommendation,
  setActionRecommendationStatus,
} from '../actionEngineService';
import {
  extractHiringAutomationMetadata,
  generateHiringAutomationActions,
  queueHiringAutomationSideEffects,
} from '../hiringAutomationService';

const createActionEngineMock = createActionEngine as jest.MockedFunction<typeof createActionEngine>;
const refreshDecisionRecommendationsMock = refreshDecisionRecommendations as jest.MockedFunction<typeof refreshDecisionRecommendations>;
const generateHiringAutomationActionsMock = generateHiringAutomationActions as jest.MockedFunction<typeof generateHiringAutomationActions>;
const queueHiringAutomationSideEffectsMock = queueHiringAutomationSideEffects as jest.MockedFunction<typeof queueHiringAutomationSideEffects>;

function toJsonValue<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

interface ActionStatusEventRow {
  id: string;
  actionRecommendationId: string;
  fromStatus: string | null;
  toStatus: string;
  actorId: string | null;
  note: string | null;
  metadata: Prisma.JsonValue;
  createdAt: Date;
}

interface ActionRecommendationRow {
  id: string;
  actionId: string;
  actionType: string;
  storylineKey: string | null;
  sourceFindingIds: string[];
  predictionIds: string[];
  targetEntityType: string;
  targetEntityId: string;
  targetEntityLabel: string | null;
  recommendedAction: string;
  priority: string;
  priorityScore: number;
  confidence: number;
  explanation: string;
  evidence: Prisma.JsonValue;
  metadata: Prisma.JsonValue;
  status: string;
  executedAt: Date | null;
  dismissedAt: Date | null;
  savedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

function makeRecommendedAction(
  actionId: string,
  overrides: Partial<RecommendedAction> = {},
): RecommendedAction {
  return {
    actionId,
    actionType: 'VERIFY_CREDENTIAL',
    targetEntity: {
      entityType: 'provider',
      entityId: '1234567890',
      entityLabel: 'Ada Lovelace',
    },
    recommendedAction: 'Verify credential for Ada Lovelace',
    priority: 'HIGH',
    priorityScore: 0.72,
    confidence: 0.8,
    explanation: 'Credential verification recommended.',
    createdAt: '2026-04-22T12:00:00.000Z',
    status: 'pending',
    storylineKey: 'storyline:credential',
    sourceFindingIds: ['finding-1'],
    predictionIds: ['prediction-1'],
    evidence: [{ label: 'credential freshness', source: 'trust_state' }],
    metadata: {},
    ...overrides,
  };
}

function makeHiringMetadata(missingCredentials: string[] = []): Record<string, unknown> {
  return {
    autoGenerated: true,
    applicationId: 'app-1',
    opportunityId: 'opp-1',
    organizationId: 'org-1',
    organizationName: 'General Hospital',
    providerNpi: '1234567890',
    providerLabel: 'Ada Lovelace',
    recommendationLabel: 'Ready for interview',
    recommendationConfidence: 0.91,
    workflowEffects: {
      queueDestination: 'interview_queue',
      missingCredentials,
      employerNotification: true,
      clinicianRequest: false,
      webhookEligible: true,
      webhookQueued: false,
    },
    previewActionType: null,
    previewRecommendationLabel: null,
    previewRecommendationConfidence: null,
  };
}

function mulberry32(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state += 0x6D2B79F5;
    let value = state;
    value = Math.imul(value ^ (value >>> 15), value | 1);
    value ^= value + Math.imul(value ^ (value >>> 7), value | 61);
    return ((value ^ (value >>> 14)) >>> 0) / 4294967296;
  };
}

class InMemoryActionPrisma {
  private actions = new Map<string, ActionRecommendationRow>();
  private statusEvents: ActionStatusEventRow[] = [];
  private actionCounter = 0;
  private eventCounter = 0;
  private updateBarrierSize = 0;
  private updateBarrierArrival = 0;
  private updateBarrierResolvers: Array<() => void> = [];
  private failNextStatusEventCreateForActionIds = new Map<string, number>();

  public readonly actionRecommendation = {
    findMany: async (args?: { where?: { actionId?: { in?: string[] } } }) => {
      const rows = [...this.actions.values()].filter((row) => {
        const actionIds = args?.where?.actionId?.in;
        return !actionIds || actionIds.includes(row.actionId);
      });
      return rows.map((row) => this.cloneRow(row));
    },
    create: async (args: { data: any }) => {
      const id = `action-row-${++this.actionCounter}`;
      const createdAt = args.data.createdAt instanceof Date ? args.data.createdAt : new Date(args.data.createdAt);
      const row: ActionRecommendationRow = {
        id,
        actionId: args.data.actionId,
        actionType: args.data.actionType,
        storylineKey: args.data.storylineKey ?? null,
        sourceFindingIds: [...(args.data.sourceFindingIds ?? [])],
        predictionIds: [...(args.data.predictionIds ?? [])],
        targetEntityType: args.data.targetEntityType,
        targetEntityId: args.data.targetEntityId,
        targetEntityLabel: args.data.targetEntityLabel ?? null,
        recommendedAction: args.data.recommendedAction,
        priority: args.data.priority,
        priorityScore: args.data.priorityScore,
        confidence: args.data.confidence,
        explanation: args.data.explanation,
        evidence: toJsonValue(args.data.evidence ?? []),
        metadata: toJsonValue(args.data.metadata ?? {}),
        status: args.data.status,
        executedAt: null,
        dismissedAt: null,
        savedAt: null,
        createdAt,
        updatedAt: createdAt,
      };
      this.actions.set(row.actionId, row);

      const nestedEvents = args.data.statusEvents?.create ?? [];
      for (const event of nestedEvents) {
        this.statusEvents.push({
          id: `status-event-${++this.eventCounter}`,
          actionRecommendationId: row.id,
          fromStatus: event.fromStatus ?? null,
          toStatus: event.toStatus,
          actorId: event.actorId ?? null,
          note: event.note ?? null,
          metadata: toJsonValue(event.metadata ?? {}),
          createdAt: event.createdAt instanceof Date ? event.createdAt : new Date(event.createdAt),
        });
      }

      return this.cloneRow(row);
    },
    update: async (args: { where: { actionId: string }; data: Record<string, unknown> }) => {
      const row = this.requireAction(args.where.actionId);
      Object.assign(row, {
        ...args.data,
        sourceFindingIds: args.data.sourceFindingIds ? [...(args.data.sourceFindingIds as string[])] : row.sourceFindingIds,
        predictionIds: args.data.predictionIds ? [...(args.data.predictionIds as string[])] : row.predictionIds,
        evidence: args.data.evidence ? toJsonValue(args.data.evidence) : row.evidence,
        metadata: args.data.metadata ? toJsonValue(args.data.metadata) : row.metadata,
        updatedAt: new Date('2026-04-22T12:00:00.000Z'),
      });
      return this.cloneRow(row);
    },
    findUnique: async (args: { where: { actionId: string }; include?: { statusEvents?: unknown } }) => {
      const row = this.actions.get(args.where.actionId);
      if (!row) {
        return null;
      }
      return this.withInclude(row, args.include);
    },
    findUniqueOrThrow: async (args: { where: { actionId: string }; include?: { statusEvents?: unknown } }) => {
      const row = await this.actionRecommendation.findUnique(args);
      if (!row) {
        throw new Error(`Action not found: ${args.where.actionId}`);
      }
      return row;
    },
    updateMany: async (args: { where: { id: string; status: string }; data: Record<string, unknown> }) => {
      await this.waitForUpdateBarrier();
      const row = [...this.actions.values()].find((candidate) => candidate.id === args.where.id && candidate.status === args.where.status);
      if (!row) {
        return { count: 0 };
      }

      Object.assign(row, {
        ...args.data,
        updatedAt: new Date('2026-04-22T12:05:00.000Z'),
      });
      return { count: 1 };
    },
  };

  public readonly actionStatusEvent = {
    create: async (args: { data: Omit<ActionStatusEventRow, 'id'> }) => {
      const row = [...this.actions.values()].find((candidate) => candidate.id === args.data.actionRecommendationId);
      if (!row) {
        throw new Error(`Unknown action recommendation id: ${args.data.actionRecommendationId}`);
      }

      const remainingFailures = this.failNextStatusEventCreateForActionIds.get(row.actionId) ?? 0;
      if (remainingFailures > 0) {
        this.failNextStatusEventCreateForActionIds.set(row.actionId, remainingFailures - 1);
        throw new Error(`Injected status-event failure for ${row.actionId}`);
      }

      const created: ActionStatusEventRow = {
        id: `status-event-${++this.eventCounter}`,
        actionRecommendationId: args.data.actionRecommendationId,
        fromStatus: args.data.fromStatus ?? null,
        toStatus: args.data.toStatus,
        actorId: args.data.actorId ?? null,
        note: args.data.note ?? null,
        metadata: toJsonValue(args.data.metadata ?? {}),
        createdAt: args.data.createdAt instanceof Date ? args.data.createdAt : new Date(args.data.createdAt),
      };
      this.statusEvents.push(created);
      return toJsonValue(created);
    },
  };

  public async $transaction<T>(work: (tx: this) => Promise<T>): Promise<T> {
    const snapshot = {
      actions: new Map([...this.actions.entries()].map(([key, value]) => [key, this.cloneRow(value)])),
      statusEvents: this.statusEvents.map((event) => ({ ...event, createdAt: new Date(event.createdAt) })),
      actionCounter: this.actionCounter,
      eventCounter: this.eventCounter,
    };

    try {
      return await work(this);
    } catch (error) {
      this.actions = new Map(snapshot.actions.entries());
      this.statusEvents = snapshot.statusEvents;
      this.actionCounter = snapshot.actionCounter;
      this.eventCounter = snapshot.eventCounter;
      throw error;
    }
  }

  public enableConcurrentUpdateBarrier(target = 2): void {
    this.updateBarrierSize = target;
    this.updateBarrierArrival = 0;
    this.updateBarrierResolvers = [];
  }

  public injectStatusEventFailure(actionId: string, count = 1): void {
    this.failNextStatusEventCreateForActionIds.set(actionId, count);
  }

  public reset(): void {
    this.actions.clear();
    this.statusEvents = [];
    this.actionCounter = 0;
    this.eventCounter = 0;
    this.updateBarrierSize = 0;
    this.updateBarrierArrival = 0;
    this.updateBarrierResolvers = [];
    this.failNextStatusEventCreateForActionIds.clear();
  }

  public getAction(actionId: string): ActionRecommendationRow | null {
    const row = this.actions.get(actionId);
    return row ? this.cloneRow(row) : null;
  }

  public getActionWithEvents(actionId: string): (ActionRecommendationRow & { statusEvents: ActionStatusEventRow[] }) | null {
    const row = this.actions.get(actionId);
    return row ? this.withInclude(row, { statusEvents: true }) as (ActionRecommendationRow & { statusEvents: ActionStatusEventRow[] }) : null;
  }

  public listActionRows(): ActionRecommendationRow[] {
    return [...this.actions.values()].map((row) => this.cloneRow(row));
  }

  public async updateActionMetadata(actionId: string, metadata: Record<string, unknown>): Promise<void> {
    await this.actionRecommendation.update({
      where: { actionId },
      data: { metadata: toJsonValue(metadata) },
    });
  }

  private requireAction(actionId: string): ActionRecommendationRow {
    const row = this.actions.get(actionId);
    if (!row) {
      throw new Error(`Action not found: ${actionId}`);
    }
    return row;
  }

  private cloneRow(row: ActionRecommendationRow): ActionRecommendationRow {
    return {
      ...toJsonValue(row),
      createdAt: new Date(row.createdAt),
      updatedAt: new Date(row.updatedAt),
      executedAt: row.executedAt ? new Date(row.executedAt) : null,
      dismissedAt: row.dismissedAt ? new Date(row.dismissedAt) : null,
      savedAt: row.savedAt ? new Date(row.savedAt) : null,
    };
  }

  private withInclude(
    row: ActionRecommendationRow,
    include?: { statusEvents?: unknown },
  ): ActionRecommendationRow & { statusEvents?: ActionStatusEventRow[] } {
    const cloned = this.cloneRow(row) as ActionRecommendationRow & { statusEvents?: ActionStatusEventRow[] };
    if (include?.statusEvents) {
      cloned.statusEvents = this.statusEvents
        .filter((event) => event.actionRecommendationId === row.id)
        .sort((left, right) => right.createdAt.getTime() - left.createdAt.getTime())
        .map((event) => ({
          ...toJsonValue(event),
          createdAt: new Date(event.createdAt),
        }));
    }
    return cloned;
  }

  private async waitForUpdateBarrier(): Promise<void> {
    if (this.updateBarrierSize === 0) {
      return;
    }

    this.updateBarrierArrival += 1;
    if (this.updateBarrierArrival < this.updateBarrierSize) {
      await new Promise<void>((resolve) => {
        this.updateBarrierResolvers.push(resolve);
      });
      return;
    }

    const resolvers = [...this.updateBarrierResolvers];
    this.updateBarrierSize = 0;
    this.updateBarrierArrival = 0;
    this.updateBarrierResolvers = [];
    for (const resolve of resolvers) {
      resolve();
    }
  }
}

type ActionPrisma = InMemoryActionPrisma;

function makeSeededAction(
  prismaClient: ActionPrisma,
  input: {
    actionId: string;
    actionType?: RecommendedAction['actionType'];
    status?: string;
    metadata?: Record<string, unknown>;
    targetEntityId?: string;
    targetEntityLabel?: string;
  },
): Promise<void> {
  return prismaClient.actionRecommendation.create({
    data: {
      actionId: input.actionId,
      actionType: input.actionType ?? 'VERIFY_CREDENTIAL',
      storylineKey: 'storyline:test',
      sourceFindingIds: ['finding-1'],
      predictionIds: ['prediction-1'],
      targetEntityType: 'provider',
      targetEntityId: input.targetEntityId ?? '1234567890',
      targetEntityLabel: input.targetEntityLabel ?? 'Ada Lovelace',
      recommendedAction: 'Take action',
      priority: 'HIGH',
      priorityScore: 0.72,
      confidence: 0.81,
      explanation: 'Action recommended for testing.',
      evidence: [],
      metadata: toJsonValue(input.metadata ?? {}),
      status: input.status ?? 'OPEN',
      createdAt: new Date('2026-04-22T12:00:00.000Z'),
      statusEvents: {
        create: [{
          fromStatus: null,
          toStatus: 'pending',
          note: 'Seeded for action execution test.',
          metadata: {},
          createdAt: new Date('2026-04-22T12:00:00.000Z'),
        }],
      },
    },
  }).then(() => undefined);
}

function validateStatusHistory(statusEvents: ActionStatusEventRow[]): { duplicateStates: number; invalidTransitions: number } {
  const chronological = [...statusEvents].sort((left, right) => left.createdAt.getTime() - right.createdAt.getTime());
  let duplicateStates = 0;
  let invalidTransitions = 0;

  for (let index = 0; index < chronological.length; index += 1) {
    const current = chronological[index]!;
    const previous = index > 0 ? chronological[index - 1] : null;
    const currentStatus = normalizeActionStatus(current.toStatus);

    if (previous) {
      const previousStatus = normalizeActionStatus(previous.toStatus);
      if (previousStatus === currentStatus) {
        duplicateStates += 1;
      }
      if (!canTransitionActionStatus(previousStatus, currentStatus)) {
        invalidTransitions += 1;
      }
    } else if (current.fromStatus !== null) {
      invalidTransitions += 1;
    }
  }

  return { duplicateStates, invalidTransitions };
}

describe('actionEngineService', () => {
  let prismaClient: ActionPrisma;

  beforeEach(() => {
    prismaClient = new InMemoryActionPrisma();
    jest.resetAllMocks();
  });

  it('dedupes duplicate action recommendations during refresh and keeps the strongest candidate', async () => {
    refreshDecisionRecommendationsMock.mockResolvedValue([]);
    const weak = makeRecommendedAction('action_duplicate', {
      priorityScore: 0.41,
      confidence: 0.54,
      explanation: 'Weaker recommendation.',
    });
    const strong = makeRecommendedAction('action_duplicate', {
      priorityScore: 0.9,
      confidence: 0.92,
      explanation: 'Stronger recommendation.',
      recommendedAction: 'Verify credential immediately',
    });
    createActionEngineMock.mockReturnValue({
      generate: jest.fn().mockReturnValue([weak, strong]),
    });
    generateHiringAutomationActionsMock.mockResolvedValue([]);
    queueHiringAutomationSideEffectsMock.mockResolvedValue();

    const persisted = await refreshActionRecommendations('2026-04-22T12:00:00.000Z', prismaClient as never);

    expect(persisted).toHaveLength(1);
    expect(persisted[0]?.actionId).toBe('action_duplicate');
    expect(persisted[0]?.explanation).toBe('Stronger recommendation.');

    const rows = prismaClient.listActionRows();
    expect(rows).toHaveLength(1);
    expect(rows[0]?.priorityScore).toBe(0.9);
    expect(rows[0]?.confidence).toBe(0.92);
  });

  it('keeps independent multi-action workflows isolated and valid', async () => {
    await makeSeededAction(prismaClient, { actionId: 'action_save_then_dismiss', targetEntityId: '1234567890' });
    await makeSeededAction(prismaClient, { actionId: 'action_execute', targetEntityId: '1234567891', targetEntityLabel: 'Grace Hopper' });

    const saved = await saveActionRecommendation('action_save_then_dismiss', {
      actorId: 'ops-user',
      note: 'Parking for follow-up.',
    }, prismaClient as never);
    const executed = await executeActionRecommendation('action_execute', {
      actorId: 'ops-user',
      note: 'Execution completed.',
    }, prismaClient as never);
    const dismissed = await dismissActionRecommendation('action_save_then_dismiss', {
      actorId: 'ops-user',
      note: 'No longer needed.',
    }, prismaClient as never);

    expect(saved.status).toBe('in_progress');
    expect(executed.status).toBe('completed');
    expect(dismissed.status).toBe('skipped');

    const first = prismaClient.getActionWithEvents('action_save_then_dismiss');
    const second = prismaClient.getActionWithEvents('action_execute');

    expect(first?.status).toBe('skipped');
    expect(first?.statusEvents).toHaveLength(3);
    expect(second?.status).toBe('completed');
    expect(second?.statusEvents).toHaveLength(2);
  });

  it('recovers cleanly after a failed dependency check without drifting state', async () => {
    await makeSeededAction(prismaClient, {
      actionId: 'action_ready_with_missing_dependency',
      actionType: 'READY_TO_INTERVIEW',
      metadata: makeHiringMetadata(['Board Certification']),
    });

    await expect(
      executeActionRecommendation('action_ready_with_missing_dependency', {
        actorId: 'ops-user',
        note: 'Attempt to complete before dependency resolution.',
      }, prismaClient as never),
    ).rejects.toThrow('Action has unresolved dependencies');

    await prismaClient.updateActionMetadata('action_ready_with_missing_dependency', makeHiringMetadata([]));

    const recovered = await executeActionRecommendation('action_ready_with_missing_dependency', {
      actorId: 'ops-user',
      note: 'Dependencies cleared.',
    }, prismaClient as never);

    const stored = prismaClient.getActionWithEvents('action_ready_with_missing_dependency');
    const metadata = extractHiringAutomationMetadata(stored?.metadata);

    expect(recovered.status).toBe('completed');
    expect(metadata?.workflowEffects.missingCredentials).toEqual([]);
    expect(stored?.statusEvents).toHaveLength(2);
    expect(stored?.statusEvents?.filter((event) => event.toStatus.toLowerCase() === 'completed')).toHaveLength(1);
  });

  it('treats concurrent execute attempts as one terminal transition', async () => {
    await makeSeededAction(prismaClient, { actionId: 'action_concurrent_execute' });
    prismaClient.enableConcurrentUpdateBarrier(2);

    const [first, second] = await Promise.all([
      executeActionRecommendation('action_concurrent_execute', {
        actorId: 'ops-user-1',
        note: 'Concurrent execute #1',
      }, prismaClient as never),
      executeActionRecommendation('action_concurrent_execute', {
        actorId: 'ops-user-2',
        note: 'Concurrent execute #2',
      }, prismaClient as never),
    ]);

    const stored = prismaClient.getActionWithEvents('action_concurrent_execute');

    expect(first.status).toBe('completed');
    expect(second.status).toBe('completed');
    expect(stored?.status).toBe('completed');
    expect(stored?.statusEvents).toHaveLength(2);
    expect(stored?.statusEvents?.filter((event) => event.toStatus.toLowerCase() === 'completed')).toHaveLength(1);
  });

  it('maintains valid state under 50 clinician workflows with random failures and concurrency', async () => {
    const random = mulberry32(424242);
    const workflowStats = {
      clinicians: 50,
      actionsCompleted: 0,
      actionsSkipped: 0,
      actionsInProgress: 0,
      dependencyBlocks: 0,
      transientFailuresRecovered: 0,
      duplicateTerminalEvents: 0,
      invalidTransitions: 0,
    };

    for (let index = 0; index < workflowStats.clinicians; index += 1) {
      const actionId = `workflow_${index}`;
      const roll = random();
      const actionType = roll < 0.3
        ? 'READY_TO_INTERVIEW'
        : roll < 0.55
          ? 'REQUEST_CREDENTIAL'
          : roll < 0.75
            ? 'CONTINUE_REVIEW'
            : 'VERIFY_CREDENTIAL';
      const missingCredentials = actionType === 'READY_TO_INTERVIEW' && random() < 0.28
        ? ['Board Certification']
        : [];

      await makeSeededAction(prismaClient, {
        actionId,
        actionType,
        targetEntityId: `${1003000000 + index}`,
        targetEntityLabel: `Clinician ${index}`,
        metadata: actionType === 'READY_TO_INTERVIEW'
          ? makeHiringMetadata(missingCredentials)
          : {},
      });

      if (random() < 0.18) {
        prismaClient.injectStatusEventFailure(actionId, 1);
      }
    }

    const workflows = prismaClient.listActionRows().map(async (row, index) => {
      try {
        if (row.actionType === 'READY_TO_INTERVIEW') {
          if (index % 5 === 0) {
            prismaClient.enableConcurrentUpdateBarrier(2);
            await Promise.allSettled([
              executeActionRecommendation(row.actionId, { actorId: `actor-${index}`, note: 'Concurrent execute A' }, prismaClient as never),
              executeActionRecommendation(row.actionId, { actorId: `actor-${index}-b`, note: 'Concurrent execute B' }, prismaClient as never),
            ]);
          }

          try {
            await executeActionRecommendation(row.actionId, { actorId: `actor-${index}`, note: 'Initial execute attempt' }, prismaClient as never);
          } catch (error) {
            const message = error instanceof Error ? error.message : String(error);
            if (message.includes('Invalid action status transition') || message.includes('existingStatus')) {
              return;
            }
            if (message.includes('unresolved dependencies')) {
              workflowStats.dependencyBlocks += 1;
              await prismaClient.updateActionMetadata(row.actionId, makeHiringMetadata([]));
            }
            workflowStats.transientFailuresRecovered += 1;
            try {
              await executeActionRecommendation(row.actionId, { actorId: `actor-${index}`, note: 'Retry after transient failure' }, prismaClient as never);
            } catch {
              // action already in terminal state or second transient failure; acceptable
            }
          }
          return;
        }

        if (row.actionType === 'REQUEST_CREDENTIAL') {
          try {
            await saveActionRecommendation(row.actionId, { actorId: `actor-${index}`, note: 'Waiting on credential upload' }, prismaClient as never);
          } catch {
            workflowStats.transientFailuresRecovered += 1;
            await saveActionRecommendation(row.actionId, { actorId: `actor-${index}`, note: 'Recovered save' }, prismaClient as never);
          }
          await dismissActionRecommendation(row.actionId, { actorId: `actor-${index}`, note: 'Credential request sent' }, prismaClient as never);
          return;
        }

        if (row.actionType === 'CONTINUE_REVIEW') {
          try {
            await saveActionRecommendation(row.actionId, { actorId: `actor-${index}`, note: 'Queued for review' }, prismaClient as never);
          } catch {
            workflowStats.transientFailuresRecovered += 1;
            await saveActionRecommendation(row.actionId, { actorId: `actor-${index}`, note: 'Recovered review queue' }, prismaClient as never);
          }
          if (random() < 0.5) {
            await setActionRecommendationStatus(row.actionId, 'pending', { actorId: `actor-${index}`, note: 'Moved back to backlog' }, prismaClient as never);
          }
          return;
        }

        try {
          await executeActionRecommendation(row.actionId, { actorId: `actor-${index}`, note: 'Verification complete' }, prismaClient as never);
        } catch {
          workflowStats.transientFailuresRecovered += 1;
          await executeActionRecommendation(row.actionId, { actorId: `actor-${index}`, note: 'Retry verification execute' }, prismaClient as never);
        }
      } catch (error) {
        throw new Error(`Workflow ${row.actionId} failed: ${error instanceof Error ? error.message : String(error)}`);
      }
    });

    await Promise.all(workflows);

    for (const row of prismaClient.listActionRows()) {
      const hydrated = prismaClient.getActionWithEvents(row.actionId);
      const history = validateStatusHistory(hydrated?.statusEvents ?? []);
      workflowStats.invalidTransitions += history.invalidTransitions;
      workflowStats.duplicateTerminalEvents += history.duplicateStates;

      const normalizedStatus = normalizeActionStatus(row.status);
      if (normalizedStatus === 'completed') {
        workflowStats.actionsCompleted += 1;
      } else if (normalizedStatus === 'skipped') {
        workflowStats.actionsSkipped += 1;
      } else if (normalizedStatus === 'in_progress') {
        workflowStats.actionsInProgress += 1;
      }

      const metadata = extractHiringAutomationMetadata(row.metadata);
      if (
        row.actionType === 'READY_TO_INTERVIEW'
        && normalizedStatus === 'completed'
        && (metadata?.workflowEffects.missingCredentials.length ?? 0) > 0
      ) {
        throw new Error(`Completed action still had unresolved dependencies: ${row.actionId}`);
      }
    }

    const debugRows = prismaClient.listActionRows().map((row) => `${row.actionId}(${row.actionType}):${row.status}`);
    console.info(`DEBUG_STATES ${debugRows.join(' ')}`);
    console.info(`ACTION_SIMULATION ${JSON.stringify(workflowStats)}`);

    expect(workflowStats.invalidTransitions).toBe(0);
    expect(workflowStats.duplicateTerminalEvents).toBe(0);
    expect(workflowStats.actionsCompleted + workflowStats.actionsSkipped + workflowStats.actionsInProgress).toBe(50);
  });
});
