/**
 * A non-production deployment must never be indexable.
 *
 * The review environment (docs/deployment/review-environment.md) runs the
 * IDENTICAL production build against a second hostname. Nothing about the
 * bundle distinguishes it — same `NODE_ENV`, same code, same routes — so the
 * only thing standing between a review deploy and a crawlable duplicate of
 * vitalcv.com is the deployment's own `RAILWAY_ENVIRONMENT` claim.
 *
 * These assert the OUTCOME (what robots.txt says, what header ships) rather
 * than the mechanism, so a refactor of how the environment is detected cannot
 * quietly drop the protection.
 */

import { afterEach, describe, expect, it, vi } from 'vitest';

import { isCanonicalProduction } from '@/lib/deployment/canonicalProduction';
import { isDesignPreviewAllowed } from '@/lib/design/preview';
import { isMatchaDeckPreviewAllowed } from '@/components/matcha-deck/sourceBoundary';

const ORIGINAL = { ...process.env };
afterEach(() => {
  process.env = { ...ORIGINAL };
  vi.resetModules();
});

/** Load robots.ts fresh so it reads the env we just set. */
async function robotsFor(env: Record<string, string | undefined>) {
  process.env = { ...ORIGINAL, ...env };
  vi.resetModules();
  const mod = await import('@/app/robots');
  return mod.default();
}

describe('isCanonicalProduction — the one definition', () => {
  it('is true only when a deployment declares itself production', () => {
    expect(isCanonicalProduction({ RAILWAY_ENVIRONMENT: 'production' })).toBe(true);
    expect(isCanonicalProduction({ VERCEL_ENV: 'production' })).toBe(true);
    expect(isCanonicalProduction({ RAILWAY_ENVIRONMENT: '  PRODUCTION  ' })).toBe(true);
  });

  it('is false for the review environment and every other context', () => {
    expect(isCanonicalProduction({ RAILWAY_ENVIRONMENT: 'review' })).toBe(false);
    expect(isCanonicalProduction({ RAILWAY_ENVIRONMENT: 'staging' })).toBe(false);
    expect(isCanonicalProduction({ VERCEL_ENV: 'preview' })).toBe(false);
    expect(isCanonicalProduction({})).toBe(false);
  });

  it('never infers production from NODE_ENV — the review build sets it too', () => {
    expect(isCanonicalProduction({})).toBe(false);
  });
});

describe('robots.txt refuses every non-canonical deployment', () => {
  it('advertises the site on canonical production', async () => {
    const robots = await robotsFor({ RAILWAY_ENVIRONMENT: 'production' });
    const rule = Array.isArray(robots.rules) ? robots.rules[0] : robots.rules;
    expect(rule.allow).toBe('/');
    // A list since the generated provider sitemaps joined it. What this test is
    // about is WHICH deployments advertise anything at all — asserting the exact
    // single string made adding a second sitemap look like a review-environment
    // regression. The "advertises nothing off canonical production" case below
    // is the half that carries the meaning.
    const sitemaps = Array.isArray(robots.sitemap)
      ? robots.sitemap
      : [robots.sitemap].filter(Boolean);
    expect(sitemaps).toContain('https://vitalcv.com/sitemap.xml');
    expect(sitemaps.every((s) => s?.startsWith('https://vitalcv.com/'))).toBe(true);
  });

  it('disallows the whole tree on the review environment', async () => {
    const robots = await robotsFor({ RAILWAY_ENVIRONMENT: 'review' });
    const rule = Array.isArray(robots.rules) ? robots.rules[0] : robots.rules;
    expect(rule.disallow).toBe('/');
    expect(rule.allow).toBeUndefined();
  });

  it('publishes no sitemap off canonical production', async () => {
    // An absolute vitalcv.com sitemap served from a review host invites a
    // crawler to reconcile two origins.
    for (const env of ['review', 'staging', undefined]) {
      const robots = await robotsFor({ RAILWAY_ENVIRONMENT: env });
      expect(robots.sitemap, `sitemap leaked for RAILWAY_ENVIRONMENT=${env}`).toBeUndefined();
    }
  });
});

describe('the environment decision is read at request time, not baked at build', () => {
  /**
   * The bug this pins, caught by running the production build both ways:
   * metadata routes are STATICALLY GENERATED by default, so `robots.txt` and
   * `sitemap.xml` froze whatever `RAILWAY_ENVIRONMENT` was set during
   * `next build`. A CI build has none, so production would have shipped the
   * blanket `Disallow: /` and an empty sitemap — deindexing vitalcv.com — with
   * every test above still green, because they call the function directly and
   * never see Next's caching.
   *
   * Asserting the mechanism rather than the outcome is deliberate here: static
   * vs dynamic is only observable in a real build, and `force-dynamic` is the
   * one line that decides it.
   */
  it('robots and sitemap opt out of static generation', async () => {
    for (const mod of ['@/app/robots', '@/app/sitemap']) {
      vi.resetModules();
      const loaded = await import(mod);
      expect(loaded.dynamic, `${mod} must export dynamic = 'force-dynamic'`).toBe('force-dynamic');
    }
  });
});

describe('the sitemap only advertises from canonical production', () => {
  async function sitemapFor(env: Record<string, string | undefined>) {
    process.env = { ...ORIGINAL, ...env };
    vi.resetModules();
    const mod = await import('@/app/sitemap');
    return mod.default();
  }

  it('lists routes on canonical production', async () => {
    const entries = await sitemapFor({ RAILWAY_ENVIRONMENT: 'production' });
    expect(entries.length).toBeGreaterThan(0);
    expect(entries[0].url.startsWith('https://vitalcv.com')).toBe(true);
  });

  it('is empty on the review environment', async () => {
    expect(await sitemapFor({ RAILWAY_ENVIRONMENT: 'review' })).toEqual([]);
  });

  it('still exports every route for the freshness guard to measure', async () => {
    process.env = { ...ORIGINAL, RAILWAY_ENVIRONMENT: 'review' };
    vi.resetModules();
    const { SITEMAP_ROUTES } = await import('@/app/sitemap');
    expect(SITEMAP_ROUTES.length).toBeGreaterThan(0);
  });
});

describe('the preview gates read the same predicate', () => {
  it('canonical production still refuses /design/* even with the flag set', () => {
    expect(isDesignPreviewAllowed({
      NODE_ENV: 'production', RAILWAY_ENVIRONMENT: 'production', DESIGN_PREVIEW: '1',
    })).toBe(false);
  });

  it('the review environment MAY serve design references with the flag', () => {
    // Deliberate: a review deployment is where a design reference is useful,
    // and it is not publicly advertised.
    expect(isDesignPreviewAllowed({
      NODE_ENV: 'production', RAILWAY_ENVIRONMENT: 'review', DESIGN_PREVIEW: '1',
    })).toBe(true);
    expect(isDesignPreviewAllowed({
      NODE_ENV: 'production', RAILWAY_ENVIRONMENT: 'review',
    })).toBe(false);
  });

  it('the MATCHA deck harness keeps the same boundary', () => {
    expect(isMatchaDeckPreviewAllowed({
      NODE_ENV: 'production', RAILWAY_ENVIRONMENT: 'production', MATCHA_DECK_PREVIEW: '1',
    })).toBe(false);
    expect(isMatchaDeckPreviewAllowed({
      NODE_ENV: 'production', RAILWAY_ENVIRONMENT: 'review', MATCHA_DECK_PREVIEW: '1',
    })).toBe(true);
  });
});

describe('the rule has exactly one definition', () => {
  it('no file re-implements the RAILWAY_ENVIRONMENT === production comparison', async () => {
    const { readFileSync, readdirSync, statSync } = await import('node:fs');
    const { join } = await import('node:path');
    const root = join(process.cwd());
    const offenders: string[] = [];

    const walk = (dir: string) => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        if (entry.isDirectory()) {
          if (['node_modules', '.next', '.turbo', '_archive', '__tests__', 'tests'].includes(entry.name)) continue;
          walk(join(dir, entry.name));
          continue;
        }
        if (!/\.(ts|tsx)$/.test(entry.name)) continue;
        const file = join(dir, entry.name);
        if (file.endsWith(join('lib', 'deployment', 'canonicalProduction.ts'))) continue;
        const src = readFileSync(file, 'utf8');
        // The shape this replaced: comparing the environment's OWN NAME against
        // 'production', optionally through a normalising method chain.
        //
        // The comparison must be ADJACENT to the variable. An earlier version
        // used `[^\n]*` between them, which happily spanned a whole boolean
        // expression and flagged `lib/backend-url.ts` — a line that mentions
        // RAILWAY_ENVIRONMENT but is asking a different question ("am I
        // deployed anywhere at all?", by presence) and ends with an unrelated
        // `NODE_ENV === 'production'`. A guard that flags correct code gets
        // switched off, so the pattern only allows `?.trim().toLowerCase()`
        // style chaining in between.
        if (/\benv\.(RAILWAY_ENVIRONMENT|VERCEL_ENV)\s*(\??\.\s*\w+\(\)\s*)*===\s*['"]production['"]/.test(src)) {
          offenders.push(file.slice(root.length + 1));
        }
      }
    };
    for (const dir of ['app', 'lib', 'components']) {
      try {
        if (statSync(join(root, dir)).isDirectory()) walk(join(root, dir));
      } catch {
        // directory absent in this checkout — nothing to walk
      }
    }

    expect(
      offenders,
      `these re-implement isCanonicalProduction instead of importing it:\n  ${offenders.join('\n  ')}`,
    ).toEqual([]);
  });
});
