apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-metrics
  namespace: chai-vc-platform
  labels:
    release: kube-prometheus
    app: api
spec:
  namespaceSelector:
    matchNames:
      - chai-vc-platform
  selector:
    matchLabels:
      app: api
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
      scheme: HTTP
      scrapeTimeout: 10s
      honorLabels: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker-metrics
  namespace: chai-vc-platform
  labels:
    release: kube-prometheus
    app: worker
spec:
  namespaceSelector:
    matchNames:
      - chai-vc-platform
  selector:
    matchLabels:
      app: worker
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
      scheme: HTTP
      scrapeTimeout: 10s
      honorLabels: true

