import type { MetadataRoute } from 'next';

import { isCanonicalProductionProcess } from '@/lib/deployment/canonicalProduction';

/**
 * `robots.txt`.
 *
 * Canonical production advertises the site. **Every other deployment refuses
 * the whole tree**, because every other deployment is a second copy of the
 * marketing site on a different hostname — and a crawlable duplicate is an SEO
 * hazard that nothing else in the stack would catch. The review environment
 * (docs/deployment/review-environment.md) runs the identical production build,
 * so nothing about the bundle distinguishes it; only the deployment's own
 * `RAILWAY_ENVIRONMENT` claim does.
 *
 * This is defence in depth, not the control: `Disallow` is a request to
 * well-behaved crawlers, so the review deployment ALSO sends
 * `X-Robots-Tag: noindex, nofollow` from the middleware, which is the header
 * search engines actually obey.
 *
 * The sitemap is omitted off canonical production for the same reason — an
 * absolute vitalcv.com sitemap served from a review host would be inviting a
 * crawler to reconcile two origins.
 */
/**
 * Evaluated per REQUEST, not at build.
 *
 * Metadata routes are statically generated by default, which bakes whatever
 * `RAILWAY_ENVIRONMENT` happened to be set during `next build`. A local or CI
 * build has no such variable, so the static output would be the blanket
 * `Disallow: /` — and production would ship it, deindexing vitalcv.com
 * entirely while every test still passed. Verified by running the production
 * build both ways before this line existed.
 *
 * Same reasoning as `app/page.tsx`: an environment decision must be read from
 * the running container, never frozen into the bundle.
 */
export const dynamic = 'force-dynamic';

export default function robots(): MetadataRoute.Robots {
  if (!isCanonicalProductionProcess()) {
    return {
      rules: [{ userAgent: '*', disallow: '/' }],
    };
  }

  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        // W0.4: `/demo` and `/design/` are demo/prototype surfaces. Both carry
        // noindex now, but robots.txt is the cheaper, coarser gate and it also
        // covers the sample-clinician surfaces /demo links into.
        disallow: [
          '/api/',
          '/internal/',
          '/review/',
          '/mission-ops/',
          '/pilot-ops/',
          '/holder/',
          '/workspace/',
          '/demo',
          '/design/',
        ],
      },
    ],
    sitemap: 'https://vitalcv.com/sitemap.xml',
  };
}
