// @ts-nocheck
import { createHash } from 'node:crypto';
import type { PrismaClient } from '@prisma/client';

// ts-jest's CommonJS transform can elide the mixed value/type Prisma import in
// this @ts-nocheck legacy module, then leave references to its generated binding
// behind. Keep the runtime namespace as an explicit CommonJS load; the typed
// client remains type-only.
const { Prisma } = require('@prisma/client') as typeof import('@prisma/client');
import type { RecommendedAction } from '../../../../../../core/actions/actionEngine';
import { log } from '../../obs/logger';
import {
  parseOrganizationRequirementsEnvelope,
  type AutomationRules,
} from '../employers/pilotPolicy';
import {
  getCachedTrustState,
  type ClinicianTrustState,
} from '../trust/trustStateEngine';

const ACTIVE_APPLICATION_STATUSES = ['PENDING', 'REVIEWED'] as const;
const ACTIVE_FINDING_STATUSES = ['new', 'acknowledged', 'investigating', 'escalated'] as const;

type HiringAutomationActionType =
  | 'READY_TO_INTERVIEW'
  | 'REQUEST_CREDENTIAL'
  | 'RISK_ESCALATED'
  | 'CONTINUE_REVIEW';

export type HiringTimelineStage =
  | 'applied'
  | 'verified'
  | 'reviewed'
  | 'escalated'
  | 'accepted';

export interface HiringWorkflowEffects {
  queueDestination: 'interview_queue' | 'credential_request' | 'risk_review' | 'review_queue';
  missingCredentials: string[];
  employerNotification: boolean;
  clinicianRequest: boolean;
  webhookEligible: boolean;
  webhookQueued: boolean;
}

export interface HiringRecommendationPreview {
  actionType: HiringAutomationActionType | 'ACCEPT_RECOMMENDED';
  label: string;
  confidence: number;
  explanation: string;
  autoGenerated: boolean;
  createdAt: string;
  workflowEffects: HiringWorkflowEffects;
  previewDecision: {
    actionType: 'ACCEPT_RECOMMENDED';
    label: string;
    confidence: number;
  } | null;
}

export interface HiringTimelineEvent {
  stage: HiringTimelineStage;
  occurredAt: string | null;
  description: string;
}

export interface HiringAutomationMetadata extends Record<string, unknown> {
  autoGenerated: true;
  applicationId: string;
  opportunityId: string;
  organizationId: string;
  organizationName: string | null;
  providerNpi: string;
  providerLabel: string | null;
  recommendationLabel: string;
  recommendationConfidence: number;
  workflowEffects: HiringWorkflowEffects;
  previewActionType: 'ACCEPT_RECOMMENDED' | null;
  previewRecommendationLabel: string | null;
  previewRecommendationConfidence: number | null;
}

const hiringApplicationArgs = Prisma.validator<Prisma.ApplicationDefaultArgs>()({
  include: {
    opportunity: {
      include: {
        organization: {
          include: {
            organizationProfile: true,
          },
        },
      },
    },
  },
});

type HiringApplicationRecord = Prisma.ApplicationGetPayload<typeof hiringApplicationArgs>;

function isMissingTableError(
  error: unknown,
  tableName: string,
): boolean {
  if (
    !(error instanceof Prisma.PrismaClientKnownRequestError)
    && !(
      typeof error === 'object'
      && error !== null
      && 'code' in error
      && (error as { code?: unknown }).code === 'P2021'
    )
  ) {
    return false;
  }

  const meta = (
    error instanceof Prisma.PrismaClientKnownRequestError
      ? error.meta
      : (error as { meta?: unknown }).meta
  ) as { table?: unknown } | undefined;
  const missingTable = typeof meta?.table === 'string' ? meta.table : null;
  return missingTable?.includes(tableName) ?? false;
}

function stableHash(value: string): string {
  return createHash('sha256').update(value).digest('hex').slice(0, 24);
}

function toJsonValue(value: unknown): Prisma.InputJsonValue {
  return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
}

function asRecord(value: unknown): Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
    ? value as Record<string, unknown>
    : {};
}

function asString(value: unknown): string | null {
  return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null;
}

function asStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }

  const seen = new Set<string>();
  const values: string[] = [];
  for (const item of value) {
    if (typeof item !== 'string') {
      continue;
    }

    const trimmed = item.trim();
    const key = trimmed.toLowerCase();
    if (trimmed.length === 0 || seen.has(key)) {
      continue;
    }

    seen.add(key);
    values.push(trimmed);
  }

  return values;
}

function normalizeText(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
}

function clamp01(value: number): number {
  if (!Number.isFinite(value)) {
    return 0;
  }

  return Math.max(0, Math.min(1, value));
}

function severityRank(value: string): number {
  switch (value.toLowerCase()) {
    case 'critical':
      return 4;
    case 'high':
      return 3;
    case 'medium':
      return 2;
    case 'low':
      return 1;
    default:
      return 0;
  }
}

function recommendationLabel(actionType: HiringAutomationActionType): string {
  switch (actionType) {
    case 'READY_TO_INTERVIEW':
      return 'Move to interview';
    case 'REQUEST_CREDENTIAL':
      return 'Request credential';
    case 'RISK_ESCALATED':
      return 'Escalate risk before interview';
    case 'CONTINUE_REVIEW':
    default:
      return 'Continue review';
  }
}

function queueDestinationFor(actionType: HiringAutomationActionType): HiringWorkflowEffects['queueDestination'] {
  switch (actionType) {
    case 'READY_TO_INTERVIEW':
      return 'interview_queue';
    case 'REQUEST_CREDENTIAL':
      return 'credential_request';
    case 'RISK_ESCALATED':
      return 'risk_review';
    case 'CONTINUE_REVIEW':
    default:
      return 'review_queue';
  }
}

function priorityFor(actionType: HiringAutomationActionType): RecommendedAction['priority'] {
  switch (actionType) {
    case 'RISK_ESCALATED':
      return 'CRITICAL';
    case 'REQUEST_CREDENTIAL':
    case 'READY_TO_INTERVIEW':
      return 'HIGH';
    case 'CONTINUE_REVIEW':
    default:
      return 'MEDIUM';
  }
}

function priorityScoreFor(actionType: HiringAutomationActionType, readinessScore: number): number {
  switch (actionType) {
    case 'RISK_ESCALATED':
      return 96;
    case 'READY_TO_INTERVIEW':
      return Math.max(78, Math.min(94, readinessScore));
    case 'REQUEST_CREDENTIAL':
      return Math.max(72, Math.min(88, readinessScore + 10));
    case 'CONTINUE_REVIEW':
    default:
      return Math.max(58, Math.min(75, readinessScore));
  }
}

function confidenceForAction(
  actionType: HiringAutomationActionType,
  readinessScore: number,
  missingCredentials: string[],
  hasBlockingRisk: boolean,
): number {
  if (actionType === 'RISK_ESCALATED') {
    return hasBlockingRisk ? 0.92 : 0.78;
  }

  if (actionType === 'REQUEST_CREDENTIAL') {
    return clamp01(0.62 + (missingCredentials.length * 0.08));
  }

  if (actionType === 'READY_TO_INTERVIEW') {
    return clamp01(0.55 + (readinessScore / 200));
  }

  return clamp01(0.42 + (readinessScore / 250));
}

function previewConfidence(readinessScore: number): number {
  return clamp01(0.52 + (readinessScore / 180));
}

function factTokens(trustState: ClinicianTrustState): string[] {
  const values: string[] = [];

  for (const fact of trustState.facts) {
    values.push(normalizeText(fact.factType));
    values.push(normalizeText(fact.source));
    if (fact.details) {
      values.push(normalizeText(fact.details));
    }
  }

  return values.filter((value) => value.length > 0);
}

function hasKeyword(tokens: readonly string[], keywords: readonly string[]): boolean {
  return keywords.some((keyword) => {
    const normalized = normalizeText(keyword);
    return tokens.some((token) => token.includes(normalized) || normalized.includes(token));
  });
}

function requirementSatisfied(
  trustState: ClinicianTrustState,
  requirement: string,
): boolean {
  const normalized = normalizeText(requirement);
  const gaps = trustState.gap_summary.map((gap) => normalizeText(gap));
  const tokens = factTokens(trustState);

  if (normalized.includes('npi') || normalized.includes('identity')) {
    return trustState.identityVerified;
  }

  if (normalized.includes('license') || normalized.includes('licensure')) {
    return trustState.licensureStatus === 'verified';
  }

  if (normalized.includes('board') || normalized.includes('certification') || normalized.includes('certified')) {
    return !hasKeyword(gaps, ['board certification']) || hasKeyword(tokens, ['board', 'certification']);
  }

  if (normalized.includes('dea')) {
    return !hasKeyword(gaps, ['dea']) || hasKeyword(tokens, ['dea']);
  }

  if (normalized.includes('malpractice') || normalized.includes('insurance')) {
    return !hasKeyword(gaps, ['malpractice', 'insurance']) || hasKeyword(tokens, ['malpractice', 'insurance']);
  }

  if (
    normalized.includes('sanction')
    || normalized.includes('npdb')
    || normalized.includes('oig')
    || normalized.includes('exclusion')
    || normalized.includes('clear')
  ) {
    return trustState.exclusionClear;
  }

  return hasKeyword(tokens, [requirement]) && !hasKeyword(gaps, [requirement]);
}

function extractRequirementLabels(application: HiringApplicationRecord): string[] {
  const profile = application.opportunity.organization.organizationProfile;
  if (!profile) {
    return [];
  }

  const envelope = parseOrganizationRequirementsEnvelope(profile.requirements, []);
  const explicit = envelope.automationRules.requiredCredentials;
  if (explicit.length > 0) {
    return explicit;
  }

  return envelope.requirements.map((requirement) => requirement.label);
}

function buildMissingCredentials(
  trustState: ClinicianTrustState,
  application: HiringApplicationRecord,
): string[] {
  return extractRequirementLabels(application).filter((requirement) => !requirementSatisfied(trustState, requirement));
}

function buildRiskSummary(findings: readonly { findingId: string; title: string; summary: string; severity: string; status: string; storylineKey: string; }[]): {
  hasBlockingRisk: boolean;
  highestSeverity: string;
  sourceFindingIds: string[];
  storylineCount: number;
  explanation: string;
} {
  const activeFindings = findings.filter((finding) => ACTIVE_FINDING_STATUSES.includes(finding.status.toLowerCase() as typeof ACTIVE_FINDING_STATUSES[number]));
  const blocking = activeFindings.filter((finding) => severityRank(finding.severity) >= severityRank('high'));
  const highestSeverityFinding = [...blocking].sort((left, right) => severityRank(right.severity) - severityRank(left.severity))[0]
    ?? [...activeFindings].sort((left, right) => severityRank(right.severity) - severityRank(left.severity))[0]
    ?? null;

  return {
    hasBlockingRisk: blocking.length > 0,
    highestSeverity: highestSeverityFinding?.severity ?? 'low',
    sourceFindingIds: activeFindings.slice(0, 4).map((finding) => finding.findingId),
    storylineCount: new Set(activeFindings.map((finding) => finding.storylineKey)).size,
    explanation: highestSeverityFinding
      ? `${highestSeverityFinding.title}: ${highestSeverityFinding.summary}`
      : 'No blocking findings are currently attached.',
  };
}

function buildWorkflowEffects(input: {
  actionType: HiringAutomationActionType;
  missingCredentials: string[];
  notifyEmployer: boolean;
  notifyClinician: boolean;
  webhookEligible: boolean;
}): HiringWorkflowEffects {
  const employerNotification = input.notifyEmployer
    && (input.actionType === 'READY_TO_INTERVIEW' || input.actionType === 'RISK_ESCALATED' || input.actionType === 'CONTINUE_REVIEW');
  const clinicianRequest = input.notifyClinician && input.actionType === 'REQUEST_CREDENTIAL';

  return {
    queueDestination: queueDestinationFor(input.actionType),
    missingCredentials: [...input.missingCredentials],
    employerNotification,
    clinicianRequest,
    webhookEligible: employerNotification && input.webhookEligible,
    webhookQueued: employerNotification && input.webhookEligible,
  };
}

function buildActionExplanation(input: {
  actionType: HiringAutomationActionType;
  providerLabel: string;
  opportunityTitle: string;
  readinessScore: number;
  missingCredentials: string[];
  riskSummary: string;
  organizationName: string | null;
  storylines: number;
}): string {
  switch (input.actionType) {
    case 'READY_TO_INTERVIEW':
      return `${input.providerLabel} meets the configured interview threshold for ${input.opportunityTitle} with readiness ${input.readinessScore}/100 and no blocking trust gaps.`;
    case 'REQUEST_CREDENTIAL':
      return `${input.providerLabel} is not yet ready for ${input.opportunityTitle}. Missing or unresolved credentials: ${input.missingCredentials.join(', ') || 'additional evidence required'}.`;
    case 'RISK_ESCALATED':
      return `${input.providerLabel} is blocked by active high-risk trust signals for ${input.organizationName ?? input.opportunityTitle}. ${input.riskSummary}`;
    case 'CONTINUE_REVIEW':
    default:
      return `${input.providerLabel} clears the minimum threshold for ${input.opportunityTitle}, but the recommendation is to continue review while ${input.storylines > 0 ? `${input.storylines} storyline(s) remain active` : 'remaining signals settle'}.`;
  }
}

function resolveActionType(input: {
  readinessScore: number;
  rules: AutomationRules;
  missingCredentials: string[];
  hasBlockingRisk: boolean;
}): HiringAutomationActionType {
  if (input.hasBlockingRisk) {
    return 'RISK_ESCALATED';
  }

  if (input.missingCredentials.length > 0 || input.readinessScore < input.rules.minReadinessScore) {
    return 'REQUEST_CREDENTIAL';
  }

  if (input.readinessScore >= input.rules.readyToInterviewThreshold) {
    return 'READY_TO_INTERVIEW';
  }

  return 'CONTINUE_REVIEW';
}

function buildActionId(input: {
  actionType: HiringAutomationActionType;
  applicationId: string;
  providerNpi: string;
  opportunityId: string;
}): string {
  return `action_${stableHash(`hiring:${input.actionType}:${input.applicationId}:${input.providerNpi}:${input.opportunityId}`)}`;
}

function metadataFromUnknown(value: unknown): HiringAutomationMetadata | null {
  const record = asRecord(value);
  if (record.autoGenerated !== true) {
    return null;
  }

  const workflowEffects = asRecord(record.workflowEffects);
  const recommendationLabel = asString(record.recommendationLabel);
  const providerNpi = asString(record.providerNpi);
  const applicationId = asString(record.applicationId);
  const opportunityId = asString(record.opportunityId);
  const organizationId = asString(record.organizationId);

  if (!recommendationLabel || !providerNpi || !applicationId || !opportunityId || !organizationId) {
    return null;
  }

  return {
    autoGenerated: true,
    applicationId,
    opportunityId,
    organizationId,
    organizationName: asString(record.organizationName),
    providerNpi,
    providerLabel: asString(record.providerLabel),
    recommendationLabel,
    recommendationConfidence: typeof record.recommendationConfidence === 'number'
      ? clamp01(record.recommendationConfidence)
      : 0,
    workflowEffects: {
      queueDestination: (
        workflowEffects.queueDestination === 'interview_queue'
        || workflowEffects.queueDestination === 'credential_request'
        || workflowEffects.queueDestination === 'risk_review'
        || workflowEffects.queueDestination === 'review_queue'
      )
        ? workflowEffects.queueDestination
        : 'review_queue',
      missingCredentials: asStringArray(workflowEffects.missingCredentials),
      employerNotification: workflowEffects.employerNotification === true,
      clinicianRequest: workflowEffects.clinicianRequest === true,
      webhookEligible: workflowEffects.webhookEligible === true,
      webhookQueued: workflowEffects.webhookQueued === true,
    },
    previewActionType: record.previewActionType === 'ACCEPT_RECOMMENDED' ? 'ACCEPT_RECOMMENDED' : null,
    previewRecommendationLabel: asString(record.previewRecommendationLabel),
    previewRecommendationConfidence: typeof record.previewRecommendationConfidence === 'number'
      ? clamp01(record.previewRecommendationConfidence)
      : null,
  };
}

export function extractHiringAutomationMetadata(value: unknown): HiringAutomationMetadata | null {
  return metadataFromUnknown(value);
}

export async function generateHiringAutomationActions(
  nowIso: string,
  prismaClient: PrismaClient,
): Promise<RecommendedAction[]> {
  const applications = await prismaClient.application.findMany({
    where: {
      status: {
        in: [...ACTIVE_APPLICATION_STATUSES],
      },
    },
    ...hiringApplicationArgs,
  }).catch((error) => {
    if (isMissingTableError(error, 'Application')) {
      log('warn', 'hiring_automation_optional_table_unavailable', {
        table: 'Application',
      });
      return [];
    }

    throw error;
  });

  if (applications.length === 0) {
    return [];
  }

  const organizationIds = [...new Set(applications.map((application) => application.opportunity.organizationId))];
  const webhookConfigs = await prismaClient.employerWebhookConfig.findMany({
    where: {
      employerId: { in: organizationIds },
      isActive: true,
    },
    select: {
      employerId: true,
    },
  });
  const webhookEnabledOrgIds = new Set(webhookConfigs.map((config) => config.employerId));

  const npis = [...new Set(applications.map((application) => application.npi).filter((npi): npi is string => Boolean(npi)))];
  const trustStates = new Map(
    await Promise.all(
      npis.map(async (npi) => [npi, await getCachedTrustState(npi)] as const),
    ),
  );

  const findings = npis.length === 0
    ? []
    : await prismaClient.investigatorFinding.findMany({
        where: {
          entityIds: { hasSome: npis },
          status: { in: [...ACTIVE_FINDING_STATUSES] },
        },
        select: {
          findingId: true,
          title: true,
          summary: true,
          severity: true,
          status: true,
          storylineKey: true,
          entityIds: true,
        },
        orderBy: [
          { priorityScore: 'desc' },
          { lastSeenAt: 'desc' },
        ],
      });

  const findingsByNpi = new Map<string, Array<{
    findingId: string;
    title: string;
    summary: string;
    severity: string;
    status: string;
    storylineKey: string;
  }>>();

  for (const finding of findings) {
    const matchedNpi = finding.entityIds.find((entityId) => /^\d{10}$/.test(entityId));
    if (!matchedNpi) {
      continue;
    }

    const current = findingsByNpi.get(matchedNpi) ?? [];
    current.push({
      findingId: finding.findingId,
      title: finding.title,
      summary: finding.summary,
      severity: finding.severity,
      status: finding.status,
      storylineKey: finding.storylineKey,
    });
    findingsByNpi.set(matchedNpi, current);
  }

  const actions: RecommendedAction[] = [];

  for (const application of applications) {
    const providerNpi = application.npi;
    if (!providerNpi) {
      continue;
    }

    const trustState = trustStates.get(providerNpi) ?? null;
    const orgProfile = application.opportunity.organization.organizationProfile;
    if (!trustState || !orgProfile) {
      continue;
    }

    const envelope = parseOrganizationRequirementsEnvelope(orgProfile.requirements, []);
    if (!envelope.automationRules.enabled) {
      continue;
    }

    const providerLabel = providerNpi;
    const missingCredentials = buildMissingCredentials(trustState, application);
    const risk = buildRiskSummary(findingsByNpi.get(providerNpi) ?? []);
    const actionType = resolveActionType({
      readinessScore: trustState.readiness_score,
      rules: envelope.automationRules,
      missingCredentials,
      hasBlockingRisk: risk.hasBlockingRisk,
    });
    const recommendationConfidence = confidenceForAction(
      actionType,
      trustState.readiness_score,
      missingCredentials,
      risk.hasBlockingRisk,
    );
    const workflowEffects = buildWorkflowEffects({
      actionType,
      missingCredentials,
      notifyEmployer: envelope.automationRules.notifyEmployer,
      notifyClinician: envelope.automationRules.notifyClinician,
      webhookEligible: webhookEnabledOrgIds.has(application.opportunity.organizationId),
    });
    const previewEligible = typeof envelope.automationRules.autoAcceptThreshold === 'number'
      && trustState.readiness_score >= envelope.automationRules.autoAcceptThreshold
      && missingCredentials.length === 0
      && !risk.hasBlockingRisk;

    const explanation = buildActionExplanation({
      actionType,
      providerLabel,
      opportunityTitle: application.opportunity.title,
      readinessScore: trustState.readiness_score,
      missingCredentials,
      riskSummary: risk.explanation,
      organizationName: application.opportunity.organization.name,
      storylines: risk.storylineCount,
    });

    const recommendation = recommendationLabel(actionType);
    const metadata: HiringAutomationMetadata = {
      autoGenerated: true,
      applicationId: application.id,
      opportunityId: application.opportunityId,
      organizationId: application.opportunity.organizationId,
      organizationName: application.opportunity.organization.name ?? null,
      providerNpi,
      providerLabel,
      recommendationLabel: recommendation,
      recommendationConfidence,
      workflowEffects,
      previewActionType: previewEligible ? 'ACCEPT_RECOMMENDED' : null,
      previewRecommendationLabel: previewEligible ? 'Recommend acceptance' : null,
      previewRecommendationConfidence: previewEligible ? previewConfidence(trustState.readiness_score) : null,
    };

    actions.push({
      actionId: buildActionId({
        actionType,
        applicationId: application.id,
        providerNpi,
        opportunityId: application.opportunityId,
      }),
      actionType,
      targetEntity: {
        entityType: 'provider',
        entityId: providerNpi,
        entityLabel: providerLabel,
      },
      recommendedAction: recommendation,
      priority: priorityFor(actionType),
      priorityScore: priorityScoreFor(actionType, trustState.readiness_score),
      confidence: recommendationConfidence,
      explanation,
      createdAt: nowIso,
      status: 'pending',
      storylineKey: risk.hasBlockingRisk ? (findingsByNpi.get(providerNpi)?.[0]?.storylineKey ?? null) : null,
      sourceFindingIds: risk.sourceFindingIds,
      predictionIds: [],
      evidence: [
        {
          label: 'Readiness score',
          snippet: `${trustState.readiness_score}/100`,
          source: 'trust_state',
        },
        ...(missingCredentials.length > 0
          ? [{
              label: 'Missing credentials',
              snippet: missingCredentials.join(', '),
              source: 'automation_rules',
            }]
          : []),
        ...(risk.hasBlockingRisk
          ? [{
              label: 'Blocking risk',
              snippet: risk.explanation,
              source: 'investigator_findings',
            }]
          : []),
      ],
      metadata,
    });
  }

  return actions;
}

export async function queueHiringAutomationSideEffects(
  actions: readonly RecommendedAction[],
  prismaClient: PrismaClient,
): Promise<void> {
  const autoGeneratedActions = actions
    .map((action) => ({
      action,
      metadata: extractHiringAutomationMetadata(action.metadata),
    }))
    .filter((entry): entry is { action: RecommendedAction; metadata: HiringAutomationMetadata } => Boolean(entry.metadata))
    .filter((entry) => entry.metadata.workflowEffects.webhookQueued);

  if (autoGeneratedActions.length === 0) {
    return;
  }

  await Promise.allSettled(
    autoGeneratedActions.map(({ action, metadata }) => prismaClient.outboxEvent.upsert({
      where: {
        dedupeKey: `hiring-automation:webhook:${action.actionId}`,
      },
      update: {
        payload: toJsonValue({
          schema: 'https://vitalcv.com/hiring-automation/webhook/v1',
          actionId: action.actionId,
          actionType: action.actionType,
          recommendationLabel: metadata.recommendationLabel,
          recommendationConfidence: metadata.recommendationConfidence,
          workflowEffects: metadata.workflowEffects,
          applicationId: metadata.applicationId,
          opportunityId: metadata.opportunityId,
          organizationId: metadata.organizationId,
          providerNpi: metadata.providerNpi,
          providerLabel: metadata.providerLabel,
          issuedAt: action.createdAt,
        }),
        aggregateType: 'ActionRecommendation',
        aggregateId: action.actionId,
      },
      create: {
        eventType: 'HIRING_AUTOMATION_RECOMMENDATION',
        aggregateType: 'ActionRecommendation',
        aggregateId: action.actionId,
        payload: toJsonValue({
          schema: 'https://vitalcv.com/hiring-automation/webhook/v1',
          actionId: action.actionId,
          actionType: action.actionType,
          recommendationLabel: metadata.recommendationLabel,
          recommendationConfidence: metadata.recommendationConfidence,
          workflowEffects: metadata.workflowEffects,
          applicationId: metadata.applicationId,
          opportunityId: metadata.opportunityId,
          organizationId: metadata.organizationId,
          providerNpi: metadata.providerNpi,
          providerLabel: metadata.providerLabel,
          issuedAt: action.createdAt,
        }),
        dedupeKey: `hiring-automation:webhook:${action.actionId}`,
      },
    })),
  );
}

export function recommendationPreviewFromMetadata(
  metadata: unknown,
  actionType: string,
  explanation: string,
  createdAt: string,
): HiringRecommendationPreview | null {
  const automation = extractHiringAutomationMetadata(metadata);
  if (!automation) {
    return null;
  }

  return {
    actionType: actionType === 'READY_TO_INTERVIEW'
      || actionType === 'REQUEST_CREDENTIAL'
      || actionType === 'RISK_ESCALATED'
      || actionType === 'CONTINUE_REVIEW'
      ? actionType
      : 'CONTINUE_REVIEW',
    label: automation.recommendationLabel,
    confidence: automation.recommendationConfidence,
    explanation,
    autoGenerated: automation.autoGenerated,
    createdAt,
    workflowEffects: automation.workflowEffects,
    previewDecision: automation.previewActionType && automation.previewRecommendationLabel
      ? {
          actionType: automation.previewActionType,
          label: automation.previewRecommendationLabel,
          confidence: automation.previewRecommendationConfidence ?? 0,
        }
      : null,
  };
}

export function buildHiringTimeline(input: {
  status: string;
  createdAt: string;
  reviewedAt: string | null;
  updatedAt: string;
  latestRecommendation: HiringRecommendationPreview | null;
  acceptedAt: string | null;
}): HiringTimelineEvent[] {
  const timeline: HiringTimelineEvent[] = [{
    stage: 'applied',
    occurredAt: input.createdAt,
    description: 'Application received by employer queue.',
  }];

  if (input.latestRecommendation) {
    timeline.push({
      stage: 'verified',
      occurredAt: input.latestRecommendation.createdAt,
      description: `${input.latestRecommendation.label} recommendation generated.`,
    });
  }

  if (input.reviewedAt || (input.latestRecommendation && input.latestRecommendation.actionType !== 'REQUEST_CREDENTIAL')) {
    timeline.push({
      stage: 'reviewed',
      occurredAt: input.reviewedAt ?? input.latestRecommendation?.createdAt ?? input.updatedAt,
      description: 'Employer review state recorded for this application.',
    });
  }

  if (input.latestRecommendation?.actionType === 'RISK_ESCALATED') {
    timeline.push({
      stage: 'escalated',
      occurredAt: input.latestRecommendation.createdAt,
      description: 'Risk signals escalated into the employer review lane.',
    });
  }

  if (input.status === 'ACCEPTED' || input.acceptedAt) {
    timeline.push({
      stage: 'accepted',
      occurredAt: input.acceptedAt ?? input.reviewedAt ?? input.updatedAt,
      description: 'Employer accepted the application.',
    });
  }

  return timeline;
}
