/** State-specific credentialing data for /credentialing/[state] pages.
 *  Each entry drives metadata, content, and JSON-LD for one state page. */

export interface StateCredentialingData {
  /** URL slug, e.g. "california" */
  slug: string;
  /** Full state name */
  name: string;
  /** Abbreviation */
  abbr: string;
  /** Medical board name */
  boardName: string;
  /** Board website URL */
  boardUrl: string;
  /** Typical initial licensure timeline */
  licensureTimeline: string;
  /** Typical credentialing timeline (payer/hospital) */
  credentialingTimeline: string;
  /** Key requirements or notes specific to this state */
  notes: string[];
}

export const STATES: StateCredentialingData[] = [
  { slug: 'alabama', name: 'Alabama', abbr: 'AL', boardName: 'Alabama Board of Medical Examiners', boardUrl: 'https://www.albme.org', licensureTimeline: '8–12 weeks', credentialingTimeline: '90–120 days', notes: ['Requires USMLE/COMLEX completion', 'Telemedicine license available for out-of-state providers'] },
  { slug: 'alaska', name: 'Alaska', abbr: 'AK', boardName: 'Alaska State Medical Board', boardUrl: 'https://www.commerce.alaska.gov/web/cbpl/ProfessionalLicensing/StateMedicalBoard.aspx', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['Locum tenens permits available', 'Accepts IMLC for interstate practice'] },
  { slug: 'arizona', name: 'Arizona', abbr: 'AZ', boardName: 'Arizona Medical Board', boardUrl: 'https://www.azmd.gov', licensureTimeline: '4–8 weeks', credentialingTimeline: '60–90 days', notes: ['Offers expedited licensure for military and border-state physicians', 'Universal license recognition for experienced providers'] },
  { slug: 'arkansas', name: 'Arkansas', abbr: 'AR', boardName: 'Arkansas State Medical Board', boardUrl: 'https://www.armedicalboard.org', licensureTimeline: '8–12 weeks', credentialingTimeline: '90–120 days', notes: ['Telemedicine registration required for out-of-state practice', 'IMLC participating state'] },
  { slug: 'california', name: 'California', abbr: 'CA', boardName: 'Medical Board of California', boardUrl: 'https://www.mbc.ca.gov', licensureTimeline: '12–16 weeks', credentialingTimeline: '90–150 days', notes: ['One of the longest licensure timelines in the US', 'Requires separate DEA and state furnishing number', 'Does not participate in IMLC'] },
  { slug: 'colorado', name: 'Colorado', abbr: 'CO', boardName: 'Colorado Medical Board', boardUrl: 'https://dpo.colorado.gov/MedicalBoard', licensureTimeline: '4–8 weeks', credentialingTimeline: '60–90 days', notes: ['Relatively fast processing', 'IMLC participating state'] },
  { slug: 'connecticut', name: 'Connecticut', abbr: 'CT', boardName: 'Connecticut Medical Examining Board', boardUrl: 'https://portal.ct.gov/DPH/Practitioner-Licensing--Investigations/Medical/Medical-Board', licensureTimeline: '8–12 weeks', credentialingTimeline: '90–120 days', notes: ['Requires Connecticut-specific CME', 'IMLC participating state'] },
  { slug: 'delaware', name: 'Delaware', abbr: 'DE', boardName: 'Delaware Board of Medical Licensure and Discipline', boardUrl: 'https://dpr.delaware.gov/boards/medicalpractice/', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Accepts FCVS profile'] },
  { slug: 'florida', name: 'Florida', abbr: 'FL', boardName: 'Florida Board of Medicine', boardUrl: 'https://flboardofmedicine.gov', licensureTimeline: '8–16 weeks', credentialingTimeline: '90–120 days', notes: ['High volume of applications can slow processing', 'Separate DO board (Board of Osteopathic Medicine)', 'Does not participate in IMLC'] },
  { slug: 'georgia', name: 'Georgia', abbr: 'GA', boardName: 'Georgia Composite Medical Board', boardUrl: 'https://medicalboard.georgia.gov', licensureTimeline: '8–12 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Telemedicine license available'] },
  { slug: 'hawaii', name: 'Hawaii', abbr: 'HI', boardName: 'Hawaii Medical Board', boardUrl: 'https://cca.hawaii.gov/pvl/boards/medical/', licensureTimeline: '8–14 weeks', credentialingTimeline: '90–120 days', notes: ['Limited specialist availability drives demand', 'Telemedicine special purpose license available'] },
  { slug: 'idaho', name: 'Idaho', abbr: 'ID', boardName: 'Idaho Board of Medicine', boardUrl: 'https://bom.idaho.gov', licensureTimeline: '4–8 weeks', credentialingTimeline: '60–90 days', notes: ['IMLC participating state', 'Relatively streamlined process'] },
  { slug: 'illinois', name: 'Illinois', abbr: 'IL', boardName: 'Illinois Department of Financial and Professional Regulation', boardUrl: 'https://idfpr.illinois.gov', licensureTimeline: '8–12 weeks', credentialingTimeline: '90–120 days', notes: ['Large market with high provider demand', 'IMLC participating state'] },
  { slug: 'indiana', name: 'Indiana', abbr: 'IN', boardName: 'Indiana Medical Licensing Board', boardUrl: 'https://www.in.gov/pla/professions/medical-licensing-board-of-indiana/', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Accepts FCVS profile'] },
  { slug: 'iowa', name: 'Iowa', abbr: 'IA', boardName: 'Iowa Board of Medicine', boardUrl: 'https://medicalboard.iowa.gov', licensureTimeline: '4–8 weeks', credentialingTimeline: '60–90 days', notes: ['IMLC participating state', 'Generally faster than national average'] },
  { slug: 'kansas', name: 'Kansas', abbr: 'KS', boardName: 'Kansas Board of Healing Arts', boardUrl: 'https://www.ksbha.org', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Expedited process for border-state providers'] },
  { slug: 'kentucky', name: 'Kentucky', abbr: 'KY', boardName: 'Kentucky Board of Medical Licensure', boardUrl: 'https://kbml.ky.gov', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Rural health shortage drives demand'] },
  { slug: 'louisiana', name: 'Louisiana', abbr: 'LA', boardName: 'Louisiana State Board of Medical Examiners', boardUrl: 'https://www.lsbme.la.gov', licensureTimeline: '8–12 weeks', credentialingTimeline: '90–120 days', notes: ['Does not participate in IMLC', 'Separate telemedicine permit required'] },
  { slug: 'maine', name: 'Maine', abbr: 'ME', boardName: 'Maine Board of Licensure in Medicine', boardUrl: 'https://www.maine.gov/md/', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Rural practice opportunities'] },
  { slug: 'maryland', name: 'Maryland', abbr: 'MD', boardName: 'Maryland Board of Physicians', boardUrl: 'https://www.mbp.state.md.us', licensureTimeline: '8–12 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Large healthcare market near DC metro'] },
  { slug: 'massachusetts', name: 'Massachusetts', abbr: 'MA', boardName: 'Massachusetts Board of Registration in Medicine', boardUrl: 'https://www.mass.gov/orgs/board-of-registration-in-medicine', licensureTimeline: '10–16 weeks', credentialingTimeline: '90–150 days', notes: ['Does not participate in IMLC', 'High academic medical center concentration'] },
  { slug: 'michigan', name: 'Michigan', abbr: 'MI', boardName: 'Michigan Board of Medicine', boardUrl: 'https://www.michigan.gov/lara/bureau-list/bpl/health/hp-lic-health-prof/medicine', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Large provider market'] },
  { slug: 'minnesota', name: 'Minnesota', abbr: 'MN', boardName: 'Minnesota Board of Medical Practice', boardUrl: 'https://mn.gov/boards/medical-practice/', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Strong health system presence (Mayo Clinic, etc.)'] },
  { slug: 'mississippi', name: 'Mississippi', abbr: 'MS', boardName: 'Mississippi State Board of Medical Licensure', boardUrl: 'https://www.msbml.ms.gov', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Critical rural provider shortages'] },
  { slug: 'missouri', name: 'Missouri', abbr: 'MO', boardName: 'Missouri Board of Registration for the Healing Arts', boardUrl: 'https://pr.mo.gov/healingarts.asp', licensureTimeline: '8–12 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Separate DO licensing board'] },
  { slug: 'montana', name: 'Montana', abbr: 'MT', boardName: 'Montana Board of Medical Examiners', boardUrl: 'https://boards.bsd.dli.mt.gov/medical-examiners', licensureTimeline: '4–8 weeks', credentialingTimeline: '60–90 days', notes: ['IMLC participating state', 'Rural frontier medicine opportunities'] },
  { slug: 'nebraska', name: 'Nebraska', abbr: 'NE', boardName: 'Nebraska Board of Medicine and Surgery', boardUrl: 'https://dhhs.ne.gov/licensure/Pages/Medicine-and-Surgery.aspx', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Telehealth-friendly regulatory environment'] },
  { slug: 'nevada', name: 'Nevada', abbr: 'NV', boardName: 'Nevada State Board of Medical Examiners', boardUrl: 'https://medboard.nv.gov', licensureTimeline: '8–12 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Growing healthcare market, especially Las Vegas metro'] },
  { slug: 'new-hampshire', name: 'New Hampshire', abbr: 'NH', boardName: 'New Hampshire Board of Medicine', boardUrl: 'https://www.oplc.nh.gov/board-medicine', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Small but well-organized licensing process'] },
  { slug: 'new-jersey', name: 'New Jersey', abbr: 'NJ', boardName: 'New Jersey State Board of Medical Examiners', boardUrl: 'https://www.njconsumeraffairs.gov/bme/', licensureTimeline: '10–14 weeks', credentialingTimeline: '90–120 days', notes: ['Large provider market near NYC metro', 'Telemedicine permits available for out-of-state providers'] },
  { slug: 'new-mexico', name: 'New Mexico', abbr: 'NM', boardName: 'New Mexico Medical Board', boardUrl: 'https://www.nmmb.nm.gov', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Significant rural health professional shortage areas'] },
  { slug: 'new-york', name: 'New York', abbr: 'NY', boardName: 'New York State Education Department — Office of the Professions', boardUrl: 'http://www.op.nysed.gov/prof/med/', licensureTimeline: '12–20 weeks', credentialingTimeline: '90–150 days', notes: ['One of the most complex licensure processes', 'Does not participate in IMLC', 'Limited permit available while application is pending'] },
  { slug: 'north-carolina', name: 'North Carolina', abbr: 'NC', boardName: 'North Carolina Medical Board', boardUrl: 'https://www.ncmedboard.org', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Growing research triangle healthcare market'] },
  { slug: 'north-dakota', name: 'North Dakota', abbr: 'ND', boardName: 'North Dakota Board of Medicine', boardUrl: 'https://www.ndbm.org', licensureTimeline: '4–8 weeks', credentialingTimeline: '60–90 days', notes: ['IMLC participating state', 'Generally fast processing'] },
  { slug: 'ohio', name: 'Ohio', abbr: 'OH', boardName: 'State Medical Board of Ohio', boardUrl: 'https://med.ohio.gov', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Large academic and community health system presence'] },
  { slug: 'oklahoma', name: 'Oklahoma', abbr: 'OK', boardName: 'Oklahoma State Board of Medical Licensure and Supervision', boardUrl: 'https://www.okmedicalboard.org', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Rural health incentive programs'] },
  { slug: 'oregon', name: 'Oregon', abbr: 'OR', boardName: 'Oregon Medical Board', boardUrl: 'https://www.oregon.gov/omb', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Telemedicine-friendly regulations'] },
  { slug: 'pennsylvania', name: 'Pennsylvania', abbr: 'PA', boardName: 'Pennsylvania State Board of Medicine', boardUrl: 'https://www.dos.pa.gov/ProfessionalLicensing/BoardsCommissions/Medicine/', licensureTimeline: '8–14 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Large provider market with major academic centers'] },
  { slug: 'rhode-island', name: 'Rhode Island', abbr: 'RI', boardName: 'Rhode Island Board of Medical Licensure and Discipline', boardUrl: 'https://health.ri.gov/licenses/detail.php?id=201', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Small state with concentrated healthcare market'] },
  { slug: 'south-carolina', name: 'South Carolina', abbr: 'SC', boardName: 'South Carolina Board of Medical Examiners', boardUrl: 'https://llr.sc.gov/med/', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Growing healthcare sector'] },
  { slug: 'south-dakota', name: 'South Dakota', abbr: 'SD', boardName: 'South Dakota Board of Medical and Osteopathic Examiners', boardUrl: 'https://www.sdbmoe.gov', licensureTimeline: '4–8 weeks', credentialingTimeline: '60–90 days', notes: ['IMLC participating state', 'Fast processing, small application volume'] },
  { slug: 'tennessee', name: 'Tennessee', abbr: 'TN', boardName: 'Tennessee Board of Medical Examiners', boardUrl: 'https://www.tn.gov/health/health-program-areas/health-professional-boards/me-board.html', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Major healthcare industry hub (Nashville)'] },
  { slug: 'texas', name: 'Texas', abbr: 'TX', boardName: 'Texas Medical Board', boardUrl: 'https://www.tmb.state.tx.us', licensureTimeline: '8–14 weeks', credentialingTimeline: '90–120 days', notes: ['One of the largest provider markets', 'Separate permits for telemedicine', 'IMLC participating state'] },
  { slug: 'utah', name: 'Utah', abbr: 'UT', boardName: 'Utah Division of Occupational and Professional Licensing', boardUrl: 'https://dopl.utah.gov', licensureTimeline: '4–8 weeks', credentialingTimeline: '60–90 days', notes: ['IMLC participating state', 'Generally efficient licensing process'] },
  { slug: 'vermont', name: 'Vermont', abbr: 'VT', boardName: 'Vermont Board of Medical Practice', boardUrl: 'https://sos.vermont.gov/medical-board/', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Small state with rural practice focus'] },
  { slug: 'virginia', name: 'Virginia', abbr: 'VA', boardName: 'Virginia Board of Medicine', boardUrl: 'https://www.dhp.virginia.gov/medicine/', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Strong federal/military healthcare presence'] },
  { slug: 'washington', name: 'Washington', abbr: 'WA', boardName: 'Washington Medical Commission', boardUrl: 'https://wmc.wa.gov', licensureTimeline: '6–12 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Growing tech-health intersection market'] },
  { slug: 'west-virginia', name: 'West Virginia', abbr: 'WV', boardName: 'West Virginia Board of Medicine', boardUrl: 'https://wvbom.wv.gov', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Critical rural health needs'] },
  { slug: 'wisconsin', name: 'Wisconsin', abbr: 'WI', boardName: 'Wisconsin Medical Examining Board', boardUrl: 'https://dsps.wi.gov/pages/BoardsCouncils/MEB/Default.aspx', licensureTimeline: '6–10 weeks', credentialingTimeline: '90–120 days', notes: ['IMLC participating state', 'Major academic and community health systems'] },
  { slug: 'wyoming', name: 'Wyoming', abbr: 'WY', boardName: 'Wyoming Board of Medicine', boardUrl: 'https://wyomedboard.wyo.gov', licensureTimeline: '4–8 weeks', credentialingTimeline: '60–90 days', notes: ['IMLC participating state', 'Fast processing, lowest population state'] },
  { slug: 'district-of-columbia', name: 'District of Columbia', abbr: 'DC', boardName: 'DC Board of Medicine', boardUrl: 'https://dchealth.dc.gov/service/board-medicine', licensureTimeline: '8–12 weeks', credentialingTimeline: '90–120 days', notes: ['Not a state — separate licensing jurisdiction', 'High concentration of federal and academic healthcare'] },
];

/** Lookup a state by slug. Returns undefined if not found. */
export function getStateBySlug(slug: string): StateCredentialingData | undefined {
  return STATES.find((s) => s.slug === slug);
}
