import type React from 'react';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from './Card';
import { ConfidenceBadge } from './ConfidenceBadge';
import { SeverityBadge } from './SeverityBadge';
import { Badge } from './Badge';

/** Investigator → left-border color mapping (VDS token names) */
const INVESTIGATOR_COLORS: Record<string, string> = {
  sanctions: 'var(--vt-color-critical)',
  trust_decline: 'var(--vt-color-critical)',
  research_momentum: 'var(--vt-color-info)',
  clinical_trial: 'var(--vt-color-success)',
  industry_influence: 'var(--vt-color-accent)',
  workforce_pressure: 'var(--vt-color-warning)',
  workforce_shift: 'var(--vt-color-warning)',
  institution_expansion: 'var(--vt-color-warning)',
  divergence: 'var(--vt-color-info)',
  network_emergence: 'var(--vt-color-accent)',
  freshness: 'var(--vt-color-neutral)',
};

function isNew(firstSeenAt?: string | Date): boolean {
  if (!firstSeenAt) return false;
  const ts = typeof firstSeenAt === 'string' ? new Date(firstSeenAt).getTime() : firstSeenAt.getTime();
  return Date.now() - ts < 2 * 60 * 60 * 1000; // 2 hours
}

export interface FindingCardProps {
  title: string;
  summary: string;
  severity: string;
  status: string;
  typeLabel: string;
  confidence: number;
  investigatorId?: string;
  firstSeenAt?: string | Date;
  metadata?: React.ReactNode;
  links?: React.ReactNode;
  footer?: React.ReactNode;
  className?: string;
}

export function FindingCard({
  confidence,
  footer,
  investigatorId,
  firstSeenAt,
  links,
  metadata,
  severity,
  status,
  summary,
  title,
  typeLabel,
  className,
}: FindingCardProps) {
  const stripeColor = investigatorId ? INVESTIGATOR_COLORS[investigatorId] ?? 'var(--vt-color-neutral)' : undefined;
  const investigatorLabel = investigatorId?.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());

  return (
    <Card
      className={className}
      interactive
      style={stripeColor ? { borderLeft: `3px solid ${stripeColor}` } : undefined}
    >
      <CardHeader>
        <div className="flex flex-wrap items-center gap-[var(--vt-space-8)]">
          <SeverityBadge severity={severity} />
          <Badge variant="neutral">{status}</Badge>
          <Badge variant="outline">{typeLabel}</Badge>
          <ConfidenceBadge confidence={confidence} />
          {isNew(firstSeenAt) ? <Badge variant="accent">New</Badge> : null}
        </div>
        {investigatorLabel ? (
          <p className="text-xs text-white/40 mt-[var(--vt-space-4)]">Generated by {investigatorLabel}</p>
        ) : null}
        <CardTitle>{title}</CardTitle>
        <CardDescription>{summary}</CardDescription>
      </CardHeader>
      {(metadata || links) ? (
        <CardContent className="space-y-[var(--vt-space-12)]">
          {metadata}
          {links ? <div className="flex flex-wrap gap-[var(--vt-space-8)]">{links}</div> : null}
        </CardContent>
      ) : null}
      {footer ? <CardFooter>{footer}</CardFooter> : null}
    </Card>
  );
}
