/**
 * B242B-ACC-012: Alt Text Management Service
 *
 * Manages alt text for images: stores recommended alt descriptions,
 * ensures alt exists for every image in the app, suggests improvements.
 * Includes integration with AI suggestions (stubbed).
 */

export interface AltTextRecord {
  /** Unique identifier for the image */
  imageId: string;
  /** Current alt text */
  altText: string;
  /** Whether alt text was auto-generated */
  autoGenerated: boolean;
  /** Confidence score (0-1) for auto-generated text */
  confidence?: number;
  /** Recommended improvement (if any) */
  recommendedAlt?: string;
  /** Reason for recommendation */
  recommendationReason?: string;
  /** Timestamp when alt text was last updated */
  lastUpdated: Date;
  /** User who set/updated the alt text */
  updatedBy?: string;
}

export interface AltTextSuggestion {
  /** Suggested alt text */
  altText: string;
  /** Confidence score (0-1) */
  confidence: number;
  /** Reasoning for the suggestion */
  reasoning: string;
}

/**
 * In-memory store for alt text records
 * In production, this would be a database
 */
const altTextStore = new Map<string, AltTextRecord>();

/**
 * AI service for generating alt text suggestions (stubbed)
 */
class AIAltTextService {
  /**
   * Generate alt text suggestion from image analysis
   * @param imageUrl URL or path to the image
   * @param context Optional context about where the image appears
   */
  async generateSuggestion(
    imageUrl: string,
    context?: string
  ): Promise<AltTextSuggestion> {
    // Stubbed implementation
    // In production, this would call an AI service (e.g., OpenAI Vision, Google Cloud Vision)

    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 100));

    // Return a placeholder suggestion
    return {
      altText: `Image: ${imageUrl.split('/').pop() || 'image'}`,
      confidence: 0.5,
      reasoning: 'Auto-generated placeholder. Please review and update with descriptive text.',
    };
  }

  /**
   * Analyze existing alt text and suggest improvements
   * @param currentAltText Current alt text
   * @param imageUrl URL or path to the image
   */
  async suggestImprovement(
    currentAltText: string,
    imageUrl: string
  ): Promise<AltTextSuggestion | null> {
    // Stubbed implementation
    // In production, this would analyze the current alt text quality

    // Check if alt text is too generic
    const genericPatterns = ['image', 'photo', 'picture', 'img', 'graphic'];
    const isGeneric = genericPatterns.some((pattern) =>
      currentAltText.toLowerCase().includes(pattern)
    );

    if (isGeneric && currentAltText.length < 20) {
      return {
        altText: currentAltText,
        confidence: 0.7,
        reasoning: 'Alt text is too generic. Consider adding more descriptive details about the image content.',
      };
    }

    // Check if alt text is missing
    if (!currentAltText || currentAltText.trim().length === 0) {
      return {
        altText: 'Descriptive text needed',
        confidence: 1.0,
        reasoning: 'Alt text is required for accessibility. Please provide a description of the image.',
      };
    }

    return null;
  }
}

const aiService = new AIAltTextService();

/**
 * Alt Text Management Service
 */
export class AltTextManagementService {
  /**
   * Get alt text for an image
   */
  getAltText(imageId: string): AltTextRecord | null {
    return altTextStore.get(imageId) || null;
  }

  /**
   * Set or update alt text for an image
   */
  async setAltText(
    imageId: string,
    altText: string,
    updatedBy?: string
  ): Promise<AltTextRecord> {
    const existing = altTextStore.get(imageId);

    const record: AltTextRecord = {
      imageId,
      altText: altText.trim(),
      autoGenerated: false,
      lastUpdated: new Date(),
      updatedBy,
    };

    // Check for improvements if updating existing
    if (existing) {
      const suggestion = await aiService.suggestImprovement(
        altText,
        imageId
      );
      if (suggestion) {
        record.recommendedAlt = suggestion.altText;
        record.recommendationReason = suggestion.reasoning;
      }
    }

    altTextStore.set(imageId, record);
    return record;
  }

  /**
   * Generate alt text suggestion using AI
   */
  async generateAltText(
    imageId: string,
    imageUrl: string,
    context?: string
  ): Promise<AltTextSuggestion> {
    const suggestion = await aiService.generateSuggestion(imageUrl, context);

    // Auto-save the suggestion
    const record: AltTextRecord = {
      imageId,
      altText: suggestion.altText,
      autoGenerated: true,
      confidence: suggestion.confidence,
      lastUpdated: new Date(),
    };

    altTextStore.set(imageId, record);
    return suggestion;
  }

  /**
   * Check if an image has alt text
   */
  hasAltText(imageId: string): boolean {
    const record = altTextStore.get(imageId);
    return record !== undefined && record.altText.trim().length > 0;
  }

  /**
   * Get all images missing alt text
   */
  getMissingAltText(imageIds: string[]): string[] {
    return imageIds.filter((id) => !this.hasAltText(id));
  }

  /**
   * Validate alt text quality
   */
  validateAltText(altText: string): {
    isValid: boolean;
    issues: string[];
  } {
    const issues: string[] = [];

    if (!altText || altText.trim().length === 0) {
      issues.push('Alt text is required');
      return { isValid: false, issues };
    }

    // Check for generic terms
    const genericPatterns = ['image', 'photo', 'picture', 'img'];
    if (genericPatterns.some((pattern) => altText.toLowerCase() === pattern)) {
      issues.push('Alt text is too generic. Provide specific description.');
    }

    // Check length (too short)
    if (altText.length < 10) {
      issues.push('Alt text may be too brief. Consider adding more detail.');
    }

    // Check length (too long - alt text should be concise)
    if (altText.length > 125) {
      issues.push('Alt text is very long. Consider shortening for better screen reader experience.');
    }

    // Check for file extensions (common mistake)
    if (/\.(jpg|jpeg|png|gif|svg|webp)$/i.test(altText)) {
      issues.push('Alt text should not include file extensions.');
    }

    return {
      isValid: issues.length === 0,
      issues,
    };
  }

  /**
   * Get improvement suggestions for an image
   */
  async getImprovements(imageId: string): Promise<AltTextSuggestion | null> {
    const record = altTextStore.get(imageId);
    if (!record) {
      return {
        altText: 'Alt text needed',
        confidence: 1.0,
        reasoning: 'No alt text found for this image.',
      };
    }

    return await aiService.suggestImprovement(record.altText, imageId);
  }

  /**
   * Bulk check images for alt text
   */
  checkAllImages(imageIds: string[]): {
    withAltText: string[];
    missingAltText: string[];
    needsImprovement: string[];
  } {
    const withAltText: string[] = [];
    const missingAltText: string[] = [];
    const needsImprovement: string[] = [];

    for (const imageId of imageIds) {
      const record = altTextStore.get(imageId);
      if (!record || !record.altText.trim()) {
        missingAltText.push(imageId);
      } else {
        withAltText.push(imageId);
        const validation = this.validateAltText(record.altText);
        if (!validation.isValid) {
          needsImprovement.push(imageId);
        }
      }
    }

    return { withAltText, missingAltText, needsImprovement };
  }
}

/**
 * Singleton instance
 */
export const altTextManagementService = new AltTextManagementService();

/**
 * Default export
 */
export default altTextManagementService;

