CREATE TABLE IF NOT EXISTS "NPDBCache"(npi TEXT PRIMARY KEY, payload JSONB, status TEXT, cached_at TIMESTAMPTZ DEFAULT now(), expires_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS "OIGCache"(npi TEXT PRIMARY KEY, payload JSONB, status TEXT, cached_at TIMESTAMPTZ DEFAULT now(), expires_at TIMESTAMPTZ);

