CREATE TABLE IF NOT EXISTS "Promo"(code TEXT PRIMARY KEY, percent_off INT CHECK(percent_off BETWEEN 0 AND 100), active BOOLEAN DEFAULT true);
CREATE TABLE IF NOT EXISTS "TaxRate"(region TEXT PRIMARY KEY, percent NUMERIC DEFAULT 0);
ALTER TABLE "Org" ADD COLUMN IF NOT EXISTS vat_number TEXT;

