export const semanticColorTokens = {
  background: 'background',
  surface: 'surface',
  surfaceSubtle: 'surface-subtle',
  border: 'border',
  borderSubtle: 'border-subtle',
  textPrimary: 'text-primary',
  textSecondary: 'text-secondary',
  textMuted: 'text-muted',
  accent: 'accent',
  focusRing: 'focus-ring',
  severityCritical: 'severity-critical',
  severityHigh: 'severity-high',
  severityMedium: 'severity-medium',
  severityLow: 'severity-low',
  statusNew: 'status-new',
  statusAcknowledged: 'status-acknowledged',
  statusInvestigating: 'status-investigating',
  statusResolved: 'status-resolved',
  statusDismissed: 'status-dismissed',
  riskLow: 'risk-low',
  riskMedium: 'risk-medium',
  riskHigh: 'risk-high',
  // Lane states — credential-readiness vocabulary (prototype Wave 1+).
  // Distinct from severity/risk: these describe what the system has done
  // about a fact, not how dangerous the fact is.
  stateVerified: 'state-verified',
  statePending: 'state-pending',
  stateAccess: 'state-access',
  stateBlocked: 'state-blocked',
  stateContradicted: 'state-contradicted',
  stateUnknown: 'state-unknown',
  nodeProvider: 'node-provider',
  nodeInstitution: 'node-institution',
  nodePublication: 'node-publication',
  nodeTrial: 'node-trial',
  nodeCompany: 'node-company',
  nodeAlert: 'node-alert',
  edgeCoAuthor: 'edge-co-author',
  edgeCoInvestigator: 'edge-co-investigator',
  edgeCoGrant: 'edge-co-grant',
  edgePracticeGroup: 'edge-practice-group',
  edgeIndustryPayment: 'edge-industry-payment',
  overlay: 'overlay',
} as const;

export type SemanticColorTokenName = keyof typeof semanticColorTokens;

export const semanticColorCssVariables: Record<SemanticColorTokenName, `--${string}`> = {
  background: '--vt-bg',
  surface: '--vt-surface',
  surfaceSubtle: '--vt-surface-subtle',
  border: '--vt-border',
  borderSubtle: '--vt-border-subtle',
  textPrimary: '--vt-text-primary',
  textSecondary: '--vt-text-secondary',
  textMuted: '--vt-text-muted',
  accent: '--vt-accent',
  focusRing: '--vt-focus-ring',
  severityCritical: '--vt-severity-critical',
  severityHigh: '--vt-severity-high',
  severityMedium: '--vt-severity-medium',
  severityLow: '--vt-severity-low',
  statusNew: '--vt-status-new',
  statusAcknowledged: '--vt-status-acknowledged',
  statusInvestigating: '--vt-status-investigating',
  statusResolved: '--vt-status-resolved',
  statusDismissed: '--vt-status-dismissed',
  riskLow: '--vt-risk-low',
  riskMedium: '--vt-risk-medium',
  riskHigh: '--vt-risk-high',
  stateVerified: '--vt-state-verified',
  statePending: '--vt-state-pending',
  stateAccess: '--vt-state-access',
  stateBlocked: '--vt-state-blocked',
  stateContradicted: '--vt-state-contradicted',
  stateUnknown: '--vt-state-unknown',
  nodeProvider: '--vt-node-provider',
  nodeInstitution: '--vt-node-institution',
  nodePublication: '--vt-node-publication',
  nodeTrial: '--vt-node-trial',
  nodeCompany: '--vt-node-company',
  nodeAlert: '--vt-node-alert',
  edgeCoAuthor: '--vt-edge-co-author',
  edgeCoInvestigator: '--vt-edge-co-investigator',
  edgeCoGrant: '--vt-edge-co-grant',
  edgePracticeGroup: '--vt-edge-practice-group',
  edgeIndustryPayment: '--vt-edge-industry-payment',
  overlay: '--vt-overlay',
} as const;

export type SemanticColorScale = Record<SemanticColorTokenName, string>;

export function colorTokenKeyToCssVariable(token: SemanticColorTokenName) {
  return semanticColorCssVariables[token];
}
