/** YC MVP — behavior frozen. Do not modify without scope approval. */
/** YC MVP - behavior frozen. Do not modify without scope approval. */
export { TrustStateResolver } from './TrustStateResolver';
export {
  validateCredentialArtifact,
  validateVerificationArtifact,
} from './artifactValidation';
export {
  InMemoryLatencyHistogram,
  trustStateLatencyHistogram,
  type LatencyHistogramSnapshot,
  type LatencyPercentile,
} from './latencyHistogram';
export {
  CANONICAL_SOURCE_COVERAGE_STATES,
  CANONICAL_TRUTH_DIMENSIONS,
  CANONICAL_TRUTH_STATUSES,
  CANONICAL_TRUTH_RENDER_RULES,
  DECISION_GRADE_SOURCE_COVERAGE_STATES,
  LAUNCH_SPINE_SOURCE_IDS,
  coverageSatisfiesDecisionGradeTruth,
  createCanonicalTruth,
  createCanonicalSourceCoverage,
  findPriorityCanonicalSourceCoverage,
  getTrustStatusLabel,
  isCanonicalSourceCoverageState,
  isDecisionGradePositiveTruthStatus,
  isDecisionGradePositiveTrustStatus,
  isDecisionGradeSourceCoverageState,
  mapSourceCoverageStateToTrustStatus,
  normalizeCanonicalSourceCoverageState,
  resolveCanonicalSourceCoverageState,
  resolveCanonicalTruthStatus,
  resolveTrustUiStatus,
  sourceCoverageBadgeLabel,
  sourceCoveragePosture,
  sourceCoverageStateLabel,
  summarizeCanonicalSourceCoverage,
  type CanonicalSourceCoverage,
  type CanonicalSourceCoverageFreshness,
  type CanonicalSourceCoverageFreshnessStatus,
  type CanonicalSourceCoverageReport,
  type CanonicalSourceCoverageState,
  type CanonicalSourceCoverageSummary,
  type CanonicalSourceProvenance,
  type CanonicalSourceProof,
  type CanonicalTruth,
  type CanonicalTruthDimensionId,
  type DecisionGradeSourceCoverageState,
  type DecisionGradePositiveTruthStatus,
  type CanonicalTruthKind,
  type CanonicalTruthSet,
  type CanonicalTruthStatus,
  type NonDecisionGradeSourceCoverageState,
  type SourceCoveragePosture,
  type TrustEvidenceKind,
  type TrustUiStatus,
} from './sourceCoverage';

export type {
  BlockingReason,
  AcceptanceScopeRecord,
  EmployerLink,
  CrsResult,
  PsvReceiptRecord,
  StartScopeRecord,
  TrustStateCredentialArtifact,
  TrustStateVerificationArtifact,
  TrustBand,
  TrustStateScope,
  TrustState,
  TrustStateAuditEvent,
  TrustStateResolverDependencies,
} from './contracts';
