// ── Apply-with-VCV Session Flow ──────────────────────────────────
// Turns a static Proof Pack Manifest into an employer action loop.
// The employer reviews the immutable snapshot and takes a compliance action.

import { ProofAvailability, ReadinessPosture } from '../../trust-contract/src/index';
import { AuditEventType, createAuditEvent, type AuditEvent } from './audit-events';
import type { ProofManifest } from './manifest-engine';

// ── Session Model ────────────────────────────────────────────────

export enum ApplySessionStatus {
  /** Session created, link generated by clinician */
  CREATED = 'created',
  /** Employer has opened the link */
  OPENED = 'opened',
  /** Employer made a hiring/compliance decision */
  DECIDED = 'decided',
  /** Link expired (e.g. 30 days) */
  EXPIRED = 'expired',
}

export enum ApplyActionType {
  APPROVE_CANDIDATE = 'APPROVE_CANDIDATE',
  REJECT_CANDIDATE = 'REJECT_CANDIDATE',
  REQUEST_REFRESH = 'REQUEST_REFRESH',
  ROUTE_TO_REVIEW = 'ROUTE_TO_REVIEW',
  HOLD = 'HOLD',
}

export interface ApplySession {
  /** UUID v4 */
  sessionId: string;
  /** The specific immutable manifest this session is bound to */
  manifestId: string;
  /** NPI of the clinician */
  subjectNpi: string;
  /** ID of the employer reviewing (null if public link) */
  employerId: string | null;
  /** When the session link was generated */
  createdAt: string;
  /** When the session expires */
  expiresAt: string;
  /** Current state of the flow */
  status: ApplySessionStatus;
  /** The action taken by the employer, if decided */
  actionTaken: ApplyActionType | null;
  /** When the action was taken */
  actionTakenAt: string | null;
  /** Context about the action (reasons, notes) */
  actionMetadata: Record<string, unknown> | null;
}

// ── Session Engine ───────────────────────────────────────────────

export function createApplySession(
  manifest: ProofManifest,
  employerId: string | null = null,
  ttlDays = 30
): { session: ApplySession; event: AuditEvent } {
  // Only allow sharing if minimum proof is available
  if (manifest.proofAvailability === ProofAvailability.NONE) {
    throw new Error('Cannot share a manifest with zero proof receipts');
  }

  const now = new Date();
  const expires = new Date(now.getTime() + ttlDays * 24 * 60 * 60 * 1000);

  const session: ApplySession = {
    sessionId: crypto.randomUUID(),
    manifestId: manifest.manifestId,
    subjectNpi: manifest.subject.npi,
    employerId,
    createdAt: now.toISOString(),
    expiresAt: expires.toISOString(),
    status: ApplySessionStatus.CREATED,
    actionTaken: null,
    actionTakenAt: null,
    actionMetadata: null,
  };

  const event = createAuditEvent({
    eventType: AuditEventType.APPLICATION_SUBMITTED,
    subjectNpi: session.subjectNpi,
    actor: session.subjectNpi, // Clinician is the actor initiating the share
    manifestId: session.manifestId,
    metadata: {
      sessionId: session.sessionId,
      targetEmployerId: employerId,
    },
  });

  return { session, event };
}

export function openApplySession(session: ApplySession): { session: ApplySession; event: AuditEvent } {
  if (session.status !== ApplySessionStatus.CREATED) {
    throw new Error(`Cannot open session from status ${session.status}`);
  }

  if (new Date() > new Date(session.expiresAt)) {
    throw new Error('Session has expired');
  }

  const updated: ApplySession = {
    ...session,
    status: ApplySessionStatus.OPENED,
  };

  const event = createAuditEvent({
    eventType: AuditEventType.REVIEW_OPENED,
    subjectNpi: updated.subjectNpi,
    actor: updated.employerId || 'anonymous_employer',
    manifestId: updated.manifestId,
    metadata: {
      sessionId: updated.sessionId,
    },
  });

  return { session: updated, event };
}

export function executeApplyAction(
  session: ApplySession,
  action: ApplyActionType,
  metadata?: Record<string, unknown>
): { session: ApplySession; events: AuditEvent[] } {
  if (session.status !== ApplySessionStatus.OPENED) {
    throw new Error(`Cannot execute action from status ${session.status}`);
  }

  if (new Date() > new Date(session.expiresAt)) {
    throw new Error('Session has expired');
  }

  const actionTakenAt = new Date().toISOString();

  const updated: ApplySession = {
    ...session,
    status: ApplySessionStatus.DECIDED,
    actionTaken: action,
    actionTakenAt,
    actionMetadata: metadata || null,
  };

  const events: AuditEvent[] = [];

  // Map to the correct core audit event based on the action
  let eventType: AuditEventType;
  switch (action) {
    case ApplyActionType.APPROVE_CANDIDATE:
      eventType = AuditEventType.EMPLOYER_ACCEPTED;
      break;
    case ApplyActionType.REJECT_CANDIDATE:
      eventType = AuditEventType.EMPLOYER_REJECTED;
      break;
    case ApplyActionType.REQUEST_REFRESH:
      eventType = AuditEventType.EMPLOYER_REQUESTED_REFRESH;
      break;
    case ApplyActionType.HOLD:
      eventType = AuditEventType.EMPLOYER_HOLD;
      break;
    case ApplyActionType.ROUTE_TO_REVIEW:
      eventType = AuditEventType.EMPLOYER_ESCALATED;
      break;
  }

  // 1. The action event
  events.push(createAuditEvent({
    eventType,
    subjectNpi: updated.subjectNpi,
    actor: updated.employerId || 'anonymous_employer',
    manifestId: updated.manifestId,
    metadata: {
      sessionId: updated.sessionId,
      actionTakenAt,
      ...(metadata || {}),
    },
  }));

  // 2. If approved, emit the secondary employment started event (simulating HRIS trigger)
  if (action === ApplyActionType.APPROVE_CANDIDATE) {
    events.push(createAuditEvent({
      eventType: AuditEventType.EMPLOYMENT_STARTED,
      subjectNpi: updated.subjectNpi,
      actor: updated.employerId || 'anonymous_employer',
      manifestId: updated.manifestId,
      metadata: { sourceSessionId: updated.sessionId },
    }));
  }

  return { session: updated, events };
}
