export {
  EndpointResource,
  FhirAddress,
  FhirCodeableConcept,
  FhirCoding,
  FhirContactPoint,
  FhirHumanName,
  FhirIdentifier,
  FhirPeriod,
  FhirQualification,
  FhirReference,
  OrganizationResource,
  PractitionerResource,
  PractitionerRoleResource,
  PractitionerRoleR6,
  PractitionerR6,
  ProvenanceAgent,
  ProvenanceResource,
  R6ResourceType,
} from '@domain/provider/contracts';
