import {
  RUNTIME_STEWARDSHIP_IGNITION_GATE_IDS,
  RUNTIME_STEWARDSHIP_IGNITION_SENTINELS,
  evaluateRuntimeStewardshipIgnition,
  evaluateRuntimeStewardshipIgnitionGate,
  type RuntimeStewardshipIgnitionEvidence,
} from '../runtimeStewardshipIgnition';

const evidence: RuntimeStewardshipIgnitionEvidence[] = [
  {
    evidenceId: 'ci-ignition-workflow',
    recordedAt: '2026-05-11T02:00:00.000Z',
    domain: 'stewardship_ignition_workflow',
    sourceSystemId: 'ci-ignition',
    replayTraceId: 'ci-ignition-replay-1',
    replayFaithfulness: 0.91,
    governanceContinuity: 0.9,
    institutionalStability: 0.9,
    stewardshipSurvivability: 0.9,
    ignitionReadiness: 0.91,
    caretakerLineageDurability: 0.9,
    operationalStability: 0.9,
    activated: true,
    immutable: true,
    failClosedReady: true,
    workflowRefs: ['ci-workflow-1'],
    governanceContinuityRefs: ['ci-continuity-1'],
    replayTelemetryRefs: ['ci-replay-telemetry-1'],
    caretakerLineageRefs: ['ci-caretaker-lineage-1'],
    harmonizationRefs: ['ci-harmonization-1'],
    survivabilityRefs: ['ci-survivability-1'],
    evidenceRefs: ['ci-evidence-1'],
    ambiguityRefs: ['ci-ambiguity-1'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-governance-continuity',
    recordedAt: '2026-05-11T02:08:00.000Z',
    domain: 'governance_continuity_activation',
    sourceSystemId: 'ci-governance-continuity',
    replayTraceId: 'ci-ignition-replay-2',
    replayFaithfulness: 0.9,
    governanceContinuity: 0.92,
    institutionalStability: 0.9,
    stewardshipSurvivability: 0.9,
    ignitionReadiness: 0.9,
    caretakerLineageDurability: 0.9,
    operationalStability: 0.9,
    activated: true,
    immutable: true,
    failClosedReady: true,
    workflowRefs: ['ci-workflow-2'],
    governanceContinuityRefs: ['ci-continuity-2', 'ci-continuity-lock-1'],
    replayTelemetryRefs: ['ci-replay-telemetry-2'],
    caretakerLineageRefs: ['ci-caretaker-lineage-2'],
    harmonizationRefs: ['ci-harmonization-2'],
    survivabilityRefs: ['ci-survivability-2'],
    evidenceRefs: ['ci-evidence-2'],
    ambiguityRefs: ['ci-ambiguity-2'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-replay-telemetry',
    recordedAt: '2026-05-11T02:16:00.000Z',
    domain: 'replay_stewardship_telemetry',
    sourceSystemId: 'ci-replay-telemetry',
    replayTraceId: 'ci-ignition-replay-3',
    replayFaithfulness: 0.93,
    governanceContinuity: 0.9,
    institutionalStability: 0.9,
    stewardshipSurvivability: 0.9,
    ignitionReadiness: 0.9,
    caretakerLineageDurability: 0.9,
    operationalStability: 0.91,
    activated: true,
    immutable: true,
    failClosedReady: true,
    workflowRefs: ['ci-workflow-3'],
    governanceContinuityRefs: ['ci-continuity-3'],
    replayTelemetryRefs: ['ci-replay-telemetry-3', 'ci-replay-monitor-1'],
    caretakerLineageRefs: ['ci-caretaker-lineage-3'],
    harmonizationRefs: ['ci-harmonization-3'],
    survivabilityRefs: ['ci-survivability-3'],
    evidenceRefs: ['ci-evidence-3'],
    ambiguityRefs: ['ci-ambiguity-3'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-caretaker-harmonization',
    recordedAt: '2026-05-11T02:24:00.000Z',
    domain: 'caretaker_harmonization',
    sourceSystemId: 'ci-caretaker-harmonization',
    replayTraceId: 'ci-ignition-replay-4',
    replayFaithfulness: 0.9,
    governanceContinuity: 0.9,
    institutionalStability: 0.9,
    stewardshipSurvivability: 0.9,
    ignitionReadiness: 0.9,
    caretakerLineageDurability: 0.93,
    operationalStability: 0.9,
    activated: true,
    immutable: true,
    failClosedReady: true,
    workflowRefs: ['ci-workflow-4'],
    governanceContinuityRefs: ['ci-continuity-4'],
    replayTelemetryRefs: ['ci-replay-telemetry-4'],
    caretakerLineageRefs: ['ci-caretaker-lineage-4', 'ci-succession-1'],
    harmonizationRefs: ['ci-harmonization-4', 'ci-caretaker-map-1'],
    survivabilityRefs: ['ci-survivability-4'],
    evidenceRefs: ['ci-evidence-4'],
    ambiguityRefs: ['ci-ambiguity-4'],
    ambiguity: 'CI caretaker handoff retains pending remote confirmation.',
  },
  {
    evidenceId: 'ci-survivability-score',
    recordedAt: '2026-05-11T02:32:00.000Z',
    domain: 'stewardship_survivability_scoring',
    sourceSystemId: 'ci-survivability',
    replayTraceId: 'ci-ignition-replay-5',
    replayFaithfulness: 0.9,
    governanceContinuity: 0.9,
    institutionalStability: 0.91,
    stewardshipSurvivability: 0.93,
    ignitionReadiness: 0.9,
    caretakerLineageDurability: 0.9,
    operationalStability: 0.91,
    activated: true,
    immutable: true,
    failClosedReady: true,
    workflowRefs: ['ci-workflow-5'],
    governanceContinuityRefs: ['ci-continuity-5'],
    replayTelemetryRefs: ['ci-replay-telemetry-5'],
    caretakerLineageRefs: ['ci-caretaker-lineage-5'],
    harmonizationRefs: ['ci-harmonization-5'],
    survivabilityRefs: ['ci-survivability-5', 'ci-chaos-survivability-1'],
    evidenceRefs: ['ci-evidence-5'],
    ambiguityRefs: ['ci-ambiguity-5'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-institutional-stability',
    recordedAt: '2026-05-11T02:40:00.000Z',
    domain: 'institutional_stability',
    sourceSystemId: 'ci-institutional-stability',
    replayTraceId: 'ci-ignition-replay-6',
    replayFaithfulness: 0.9,
    governanceContinuity: 0.91,
    institutionalStability: 0.93,
    stewardshipSurvivability: 0.91,
    ignitionReadiness: 0.9,
    caretakerLineageDurability: 0.9,
    operationalStability: 0.92,
    activated: true,
    immutable: true,
    failClosedReady: true,
    workflowRefs: ['ci-workflow-6'],
    governanceContinuityRefs: ['ci-continuity-6'],
    replayTelemetryRefs: ['ci-replay-telemetry-6'],
    caretakerLineageRefs: ['ci-caretaker-lineage-6'],
    harmonizationRefs: ['ci-harmonization-6'],
    survivabilityRefs: ['ci-survivability-6'],
    evidenceRefs: ['ci-evidence-6'],
    ambiguityRefs: ['ci-ambiguity-6'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-longitudinal-lineage',
    recordedAt: '2026-05-11T02:48:00.000Z',
    domain: 'longitudinal_caretaker_lineage',
    sourceSystemId: 'ci-longitudinal-lineage',
    replayTraceId: 'ci-ignition-replay-7',
    replayFaithfulness: 0.9,
    governanceContinuity: 0.9,
    institutionalStability: 0.91,
    stewardshipSurvivability: 0.91,
    ignitionReadiness: 0.9,
    caretakerLineageDurability: 0.93,
    operationalStability: 0.91,
    activated: true,
    immutable: true,
    failClosedReady: true,
    workflowRefs: ['ci-workflow-7'],
    governanceContinuityRefs: ['ci-continuity-7'],
    replayTelemetryRefs: ['ci-replay-telemetry-7'],
    caretakerLineageRefs: ['ci-caretaker-lineage-7', 'ci-longitudinal-lineage-1'],
    harmonizationRefs: ['ci-harmonization-7'],
    survivabilityRefs: ['ci-survivability-7'],
    evidenceRefs: ['ci-evidence-7'],
    ambiguityRefs: ['ci-ambiguity-7'],
    ambiguity: null,
  },
];

describe('CI gate - runtime stewardship ignition', () => {
  it('keeps the stewardship ignition gate id surface explicit and frozen', () => {
    expect(RUNTIME_STEWARDSHIP_IGNITION_GATE_IDS).toEqual([
      'stewardship_replay_faithful',
      'ambiguity_preserved_operationally',
      'governance_continuity_reconstructable',
      'fail_closed_stewardship_semantics',
      'caretaker_lineage_longitudinally_durable',
      'runtime_stewardship_operationally_stable',
      'stewardship_survivability_scored',
    ]);
    expect(Object.isFrozen(RUNTIME_STEWARDSHIP_IGNITION_GATE_IDS)).toBe(true);
    expect(Object.isFrozen(RUNTIME_STEWARDSHIP_IGNITION_SENTINELS)).toBe(true);
  });

  it('passes only when replay, ambiguity, governance, lineage, stability, and survivability gates hold', () => {
    const result = evaluateRuntimeStewardshipIgnition({
      ignitionId: 'ci-runtime-stewardship-ignition',
      generatedAt: '2026-05-11T02:20:00.000Z',
      evidence,
    });
    const gate = evaluateRuntimeStewardshipIgnitionGate(result);

    expect(result.failClosed).toBe(false);
    expect(gate.pass).toBe(true);
    expect(gate.failedGateIds).toEqual([]);
    expect(gate.gates.map((gateResult: { id: string }) => gateResult.id)).toEqual(RUNTIME_STEWARDSHIP_IGNITION_GATE_IDS);
  });
});
