import {
  RUNTIME_TRUTH_SEAL_GATE_IDS,
  RUNTIME_TRUTH_SEAL_SENTINELS,
  evaluateRuntimeTruthSeal,
  evaluateRuntimeTruthSealGate,
  type RuntimeTruthSealEvidence,
} from '../runtimeTruthSeal';

const evidence: RuntimeTruthSealEvidence[] = [
  {
    evidenceId: 'ci-truth-global',
    recordedAt: '2026-05-11T00:00:00.000Z',
    domain: 'global_truth_verification',
    sourceSystemId: 'ci-truth',
    replayTraceId: 'ci-replay-1',
    truthFidelity: 0.92,
    replayFaithfulness: 0.91,
    ambiguityPermanence: 0.9,
    driftPrevention: 0.91,
    runtimeStability: 0.9,
    longitudinalDurability: 0.9,
    sealed: true,
    immutable: true,
    failClosedReady: true,
    evidenceRefs: ['ci-evidence-1'],
    lineageRefs: ['ci-lineage-1'],
    ambiguityRefs: ['ci-ambiguity-1'],
    telemetryRefs: ['ci-telemetry-1'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-truth-replay',
    recordedAt: '2026-05-11T00:08:00.000Z',
    domain: 'replay_truth_immutability',
    sourceSystemId: 'ci-replay-lock',
    replayTraceId: 'ci-replay-2',
    truthFidelity: 0.91,
    replayFaithfulness: 0.92,
    ambiguityPermanence: 0.9,
    driftPrevention: 0.9,
    runtimeStability: 0.9,
    longitudinalDurability: 0.9,
    sealed: true,
    immutable: true,
    failClosedReady: true,
    evidenceRefs: ['ci-evidence-2'],
    lineageRefs: ['ci-lineage-2'],
    ambiguityRefs: ['ci-ambiguity-2'],
    telemetryRefs: ['ci-telemetry-2'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-truth-ambiguity',
    recordedAt: '2026-05-11T00:16:00.000Z',
    domain: 'ambiguity_permanence',
    sourceSystemId: 'ci-ambiguity-lock',
    replayTraceId: 'ci-replay-3',
    truthFidelity: 0.9,
    replayFaithfulness: 0.9,
    ambiguityPermanence: 0.93,
    driftPrevention: 0.9,
    runtimeStability: 0.9,
    longitudinalDurability: 0.9,
    sealed: true,
    immutable: true,
    failClosedReady: true,
    evidenceRefs: ['ci-evidence-3'],
    lineageRefs: ['ci-lineage-3'],
    ambiguityRefs: ['ci-ambiguity-3', 'ci-ambiguity-retention-1'],
    telemetryRefs: ['ci-telemetry-3'],
    ambiguity: 'CI verifier preserves confidence interval ambiguity under truth seal.',
  },
  {
    evidenceId: 'ci-truth-telemetry',
    recordedAt: '2026-05-11T00:24:00.000Z',
    domain: 'truth_telemetry_lock',
    sourceSystemId: 'ci-telemetry-lock',
    replayTraceId: 'ci-replay-4',
    truthFidelity: 0.9,
    replayFaithfulness: 0.9,
    ambiguityPermanence: 0.9,
    driftPrevention: 0.91,
    runtimeStability: 0.92,
    longitudinalDurability: 0.9,
    sealed: true,
    immutable: true,
    failClosedReady: true,
    evidenceRefs: ['ci-evidence-4'],
    lineageRefs: ['ci-lineage-4'],
    ambiguityRefs: ['ci-ambiguity-4'],
    telemetryRefs: ['ci-telemetry-4', 'ci-telemetry-lock-1'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-truth-drift',
    recordedAt: '2026-05-11T00:32:00.000Z',
    domain: 'truth_drift_prevention',
    sourceSystemId: 'ci-drift-lock',
    replayTraceId: 'ci-replay-5',
    truthFidelity: 0.9,
    replayFaithfulness: 0.9,
    ambiguityPermanence: 0.9,
    driftPrevention: 0.93,
    runtimeStability: 0.9,
    longitudinalDurability: 0.9,
    sealed: true,
    immutable: true,
    failClosedReady: true,
    evidenceRefs: ['ci-evidence-5'],
    lineageRefs: ['ci-lineage-5'],
    ambiguityRefs: ['ci-ambiguity-5'],
    telemetryRefs: ['ci-telemetry-5'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-truth-lineage',
    recordedAt: '2026-05-11T00:40:00.000Z',
    domain: 'runtime_truth_lineage',
    sourceSystemId: 'ci-lineage-lock',
    replayTraceId: 'ci-replay-6',
    truthFidelity: 0.9,
    replayFaithfulness: 0.9,
    ambiguityPermanence: 0.9,
    driftPrevention: 0.9,
    runtimeStability: 0.9,
    longitudinalDurability: 0.9,
    sealed: true,
    immutable: true,
    failClosedReady: true,
    evidenceRefs: ['ci-evidence-6'],
    lineageRefs: ['ci-lineage-6', 'ci-lineage-7'],
    ambiguityRefs: ['ci-ambiguity-6'],
    telemetryRefs: ['ci-telemetry-6'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-truth-durable',
    recordedAt: '2026-05-11T00:48:00.000Z',
    domain: 'longitudinal_truth_durability',
    sourceSystemId: 'ci-durability-lock',
    replayTraceId: 'ci-replay-7',
    truthFidelity: 0.9,
    replayFaithfulness: 0.9,
    ambiguityPermanence: 0.9,
    driftPrevention: 0.9,
    runtimeStability: 0.91,
    longitudinalDurability: 0.93,
    sealed: true,
    immutable: true,
    failClosedReady: true,
    evidenceRefs: ['ci-evidence-7'],
    lineageRefs: ['ci-lineage-8'],
    ambiguityRefs: ['ci-ambiguity-7'],
    telemetryRefs: ['ci-telemetry-7'],
    ambiguity: null,
  },
];

describe('CI gate - runtime truth seal', () => {
  it('keeps the truth-seal gate id surface explicit and frozen', () => {
    expect(RUNTIME_TRUTH_SEAL_GATE_IDS).toEqual([
      'replay_truth_globally_faithful',
      'ambiguity_permanently_preserved',
      'truth_lineage_reconstructable',
      'fail_closed_truth_semantics',
      'drift_impossible_post_seal',
      'truth_telemetry_locked',
      'runtime_truth_longitudinally_durable',
    ]);
    expect(Object.isFrozen(RUNTIME_TRUTH_SEAL_GATE_IDS)).toBe(true);
    expect(Object.isFrozen(RUNTIME_TRUTH_SEAL_SENTINELS)).toBe(true);
  });

  it('passes only when replay truth, ambiguity permanence, lineage, drift lock, telemetry lock, and durability gates hold', () => {
    const result = evaluateRuntimeTruthSeal({
      sealId: 'ci-runtime-truth-seal',
      generatedAt: '2026-05-11T01:10:00.000Z',
      evidence,
    });
    const gate = evaluateRuntimeTruthSealGate(result);

    expect(result.failClosed).toBe(false);
    expect(gate.pass).toBe(true);
    expect(gate.failedGateIds).toEqual([]);
    expect(gate.gates.map((gateResult: { id: string }) => gateResult.id)).toEqual(RUNTIME_TRUTH_SEAL_GATE_IDS);
  });
});
