import {
  RUNTIME_STEWARDSHIP_OPERATIONS_GATE_IDS,
  RUNTIME_STEWARDSHIP_OPERATIONS_SENTINELS,
  evaluateRuntimeStewardshipOperations,
  evaluateRuntimeStewardshipOperationsGate,
  type RuntimeStewardshipOperationsEvidence,
} from '../runtimeStewardshipOperations';

const evidence: RuntimeStewardshipOperationsEvidence[] = [
  {
    evidenceId: 'ci-stewardship-runbook',
    recordedAt: '2026-05-11T01:00:00.000Z',
    domain: 'operational_runbook',
    sourceSystemId: 'ci-stewardship',
    replayTraceId: 'ci-stewardship-replay-1',
    replayFaithfulness: 0.91,
    runtimeContinuity: 0.9,
    successionSurvivability: 0.9,
    operationalStability: 0.9,
    runtimeSurvivability: 0.9,
    longitudinalDurability: 0.9,
    runbookRefs: ['ci-runbook-1'],
    caretakerWorkflowRefs: ['ci-caretaker-1'],
    successionPlanRefs: ['ci-succession-1'],
    telemetryRefs: ['ci-telemetry-1'],
    evidenceRefs: ['ci-evidence-1'],
    continuityLineageRefs: ['ci-lineage-1'],
    ambiguityRefs: ['ci-ambiguity-1'],
    ambiguity: null,
    failClosedReady: true,
  },
  {
    evidenceId: 'ci-stewardship-replay',
    recordedAt: '2026-05-11T01:08:00.000Z',
    domain: 'replay_stewardship_monitoring',
    sourceSystemId: 'ci-replay-stewardship',
    replayTraceId: 'ci-stewardship-replay-2',
    replayFaithfulness: 0.92,
    runtimeContinuity: 0.9,
    successionSurvivability: 0.9,
    operationalStability: 0.9,
    runtimeSurvivability: 0.9,
    longitudinalDurability: 0.9,
    runbookRefs: ['ci-runbook-2'],
    caretakerWorkflowRefs: ['ci-caretaker-2'],
    successionPlanRefs: ['ci-succession-2'],
    telemetryRefs: ['ci-telemetry-2'],
    evidenceRefs: ['ci-evidence-2'],
    continuityLineageRefs: ['ci-lineage-2'],
    ambiguityRefs: ['ci-ambiguity-2'],
    ambiguity: null,
    failClosedReady: true,
  },
  {
    evidenceId: 'ci-stewardship-caretaker',
    recordedAt: '2026-05-11T01:16:00.000Z',
    domain: 'runtime_caretaker_workflow',
    sourceSystemId: 'ci-caretaker',
    replayTraceId: 'ci-stewardship-replay-3',
    replayFaithfulness: 0.9,
    runtimeContinuity: 0.91,
    successionSurvivability: 0.9,
    operationalStability: 0.91,
    runtimeSurvivability: 0.9,
    longitudinalDurability: 0.9,
    runbookRefs: ['ci-runbook-3'],
    caretakerWorkflowRefs: ['ci-caretaker-3'],
    successionPlanRefs: ['ci-succession-3'],
    telemetryRefs: ['ci-telemetry-3'],
    evidenceRefs: ['ci-evidence-3'],
    continuityLineageRefs: ['ci-lineage-3'],
    ambiguityRefs: ['ci-ambiguity-3'],
    ambiguity: null,
    failClosedReady: true,
  },
  {
    evidenceId: 'ci-stewardship-telemetry',
    recordedAt: '2026-05-11T01:24:00.000Z',
    domain: 'stewardship_telemetry',
    sourceSystemId: 'ci-telemetry',
    replayTraceId: 'ci-stewardship-replay-4',
    replayFaithfulness: 0.9,
    runtimeContinuity: 0.9,
    successionSurvivability: 0.9,
    operationalStability: 0.92,
    runtimeSurvivability: 0.9,
    longitudinalDurability: 0.9,
    runbookRefs: ['ci-runbook-4'],
    caretakerWorkflowRefs: ['ci-caretaker-4'],
    successionPlanRefs: ['ci-succession-4'],
    telemetryRefs: ['ci-telemetry-4', 'ci-telemetry-lock-1'],
    evidenceRefs: ['ci-evidence-4'],
    continuityLineageRefs: ['ci-lineage-4'],
    ambiguityRefs: ['ci-ambiguity-4'],
    ambiguity: 'CI stewardship telemetry keeps delayed caretaker heartbeat visible.',
    failClosedReady: true,
  },
  {
    evidenceId: 'ci-stewardship-succession',
    recordedAt: '2026-05-11T01:32:00.000Z',
    domain: 'succession_continuity_planning',
    sourceSystemId: 'ci-succession',
    replayTraceId: 'ci-stewardship-replay-5',
    replayFaithfulness: 0.9,
    runtimeContinuity: 0.9,
    successionSurvivability: 0.93,
    operationalStability: 0.9,
    runtimeSurvivability: 0.91,
    longitudinalDurability: 0.91,
    runbookRefs: ['ci-runbook-5'],
    caretakerWorkflowRefs: ['ci-caretaker-5'],
    successionPlanRefs: ['ci-succession-5', 'ci-emergency-succession-1'],
    telemetryRefs: ['ci-telemetry-5'],
    evidenceRefs: ['ci-evidence-5'],
    continuityLineageRefs: ['ci-lineage-5'],
    ambiguityRefs: ['ci-ambiguity-5'],
    ambiguity: null,
    failClosedReady: true,
  },
  {
    evidenceId: 'ci-stewardship-survivability',
    recordedAt: '2026-05-11T01:40:00.000Z',
    domain: 'runtime_survivability',
    sourceSystemId: 'ci-survivability',
    replayTraceId: 'ci-stewardship-replay-6',
    replayFaithfulness: 0.9,
    runtimeContinuity: 0.91,
    successionSurvivability: 0.9,
    operationalStability: 0.91,
    runtimeSurvivability: 0.93,
    longitudinalDurability: 0.91,
    runbookRefs: ['ci-runbook-6'],
    caretakerWorkflowRefs: ['ci-caretaker-6'],
    successionPlanRefs: ['ci-succession-6'],
    telemetryRefs: ['ci-telemetry-6'],
    evidenceRefs: ['ci-evidence-6'],
    continuityLineageRefs: ['ci-lineage-6'],
    ambiguityRefs: ['ci-ambiguity-6'],
    ambiguity: null,
    failClosedReady: true,
  },
  {
    evidenceId: 'ci-stewardship-longitudinal',
    recordedAt: '2026-05-11T01:48:00.000Z',
    domain: 'longitudinal_continuity',
    sourceSystemId: 'ci-longitudinal',
    replayTraceId: 'ci-stewardship-replay-7',
    replayFaithfulness: 0.9,
    runtimeContinuity: 0.91,
    successionSurvivability: 0.91,
    operationalStability: 0.9,
    runtimeSurvivability: 0.91,
    longitudinalDurability: 0.93,
    runbookRefs: ['ci-runbook-7'],
    caretakerWorkflowRefs: ['ci-caretaker-7'],
    successionPlanRefs: ['ci-succession-7'],
    telemetryRefs: ['ci-telemetry-7'],
    evidenceRefs: ['ci-evidence-7'],
    continuityLineageRefs: ['ci-lineage-7'],
    ambiguityRefs: ['ci-ambiguity-7'],
    ambiguity: null,
    failClosedReady: true,
  },
];

describe('CI gate - runtime stewardship operations', () => {
  it('keeps the stewardship operations gate id surface explicit and frozen', () => {
    expect(RUNTIME_STEWARDSHIP_OPERATIONS_GATE_IDS).toEqual([
      'stewardship_replay_faithful',
      'ambiguity_preserved_operationally',
      'continuity_lineage_reconstructable',
      'fail_closed_stewardship_semantics',
      'runtime_survivability_measurable',
      'operational_continuity_longitudinally_durable',
      'succession_continuity_survivable',
    ]);
    expect(Object.isFrozen(RUNTIME_STEWARDSHIP_OPERATIONS_GATE_IDS)).toBe(true);
    expect(Object.isFrozen(RUNTIME_STEWARDSHIP_OPERATIONS_SENTINELS)).toBe(true);
  });

  it('passes only when replay, ambiguity, lineage, survivability, continuity, and succession gates hold', () => {
    const result = evaluateRuntimeStewardshipOperations({
      operationsId: 'ci-runtime-stewardship-ops',
      generatedAt: '2026-05-11T01:30:00.000Z',
      evidence,
    });
    const gate = evaluateRuntimeStewardshipOperationsGate(result);

    expect(result.failClosed).toBe(false);
    expect(gate.pass).toBe(true);
    expect(gate.failedGateIds).toEqual([]);
    expect(gate.gates.map((gateResult: { id: string }) => gateResult.id)).toEqual(RUNTIME_STEWARDSHIP_OPERATIONS_GATE_IDS);
  });
});
