import {
  RUNTIME_MERGE_FREEZE_GATE_IDS,
  RUNTIME_MERGE_FREEZE_SENTINELS,
  evaluateRuntimeMergeFreeze,
  evaluateRuntimeMergeFreezeGate,
  type RuntimeMergeFreezeEvidence,
} from '../runtimeMergeFreeze';

const evidence: RuntimeMergeFreezeEvidence[] = [
  {
    evidenceId: 'ci-merge-freeze',
    recordedAt: '2026-05-11T11:00:00.000Z',
    domain: 'merge_freeze_verification',
    sourceSystemId: 'ci-freeze',
    replayTraceId: 'ci-replay-1',
    freezeIntegrity: 0.95,
    replayFreezeIntegrity: 0.94,
    governanceImmutability: 0.94,
    driftResistance: 0.93,
    runtimeContinuity: 0.92,
    ambiguityPermanence: 0.93,
    immutablePostFreeze: true,
    governanceLocked: true,
    failClosedReady: true,
    mergeLineageRefs: ['ci-merge-lineage'],
    replayFreezeRefs: ['ci-replay-freeze'],
    governanceRefs: ['ci-governance-lock'],
    telemetryRefs: ['ci-freeze-telemetry'],
    driftRefs: ['ci-drift-score'],
    ambiguityRefs: ['ci-ambiguity-permanence'],
    stewardshipRefs: ['ci-stewardship-enforcement'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-replay-freeze',
    recordedAt: '2026-05-11T11:08:00.000Z',
    domain: 'replay_freeze_harmonization',
    sourceSystemId: 'ci-replay',
    replayTraceId: 'ci-replay-2',
    freezeIntegrity: 0.94,
    replayFreezeIntegrity: 0.95,
    governanceImmutability: 0.94,
    driftResistance: 0.93,
    runtimeContinuity: 0.92,
    ambiguityPermanence: 0.93,
    immutablePostFreeze: true,
    governanceLocked: true,
    failClosedReady: true,
    mergeLineageRefs: ['ci-replay-lineage'],
    replayFreezeRefs: ['ci-replay-anchor'],
    governanceRefs: ['ci-replay-governance-lock'],
    telemetryRefs: ['ci-replay-telemetry'],
    driftRefs: ['ci-replay-drift-score'],
    ambiguityRefs: ['ci-replay-ambiguity'],
    stewardshipRefs: ['ci-replay-stewardship'],
    ambiguity: 'CI preserves one replay-freeze settlement ambiguity.',
  },
  {
    evidenceId: 'ci-governance-freeze',
    recordedAt: '2026-05-11T11:16:00.000Z',
    domain: 'governance_immutability_validation',
    sourceSystemId: 'ci-governance',
    replayTraceId: 'ci-replay-3',
    freezeIntegrity: 0.94,
    replayFreezeIntegrity: 0.94,
    governanceImmutability: 0.96,
    driftResistance: 0.95,
    runtimeContinuity: 0.93,
    ambiguityPermanence: 0.94,
    immutablePostFreeze: true,
    governanceLocked: true,
    failClosedReady: true,
    mergeLineageRefs: ['ci-governance-lineage'],
    replayFreezeRefs: ['ci-governance-replay'],
    governanceRefs: ['ci-governance-lock'],
    telemetryRefs: ['ci-governance-telemetry'],
    driftRefs: ['ci-governance-drift-score'],
    ambiguityRefs: ['ci-governance-ambiguity'],
    stewardshipRefs: ['ci-governance-stewardship'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-freeze-telemetry',
    recordedAt: '2026-05-11T11:24:00.000Z',
    domain: 'freeze_telemetry',
    sourceSystemId: 'ci-telemetry',
    replayTraceId: 'ci-replay-4',
    freezeIntegrity: 0.94,
    replayFreezeIntegrity: 0.94,
    governanceImmutability: 0.94,
    driftResistance: 0.93,
    runtimeContinuity: 0.95,
    ambiguityPermanence: 0.94,
    immutablePostFreeze: true,
    governanceLocked: true,
    failClosedReady: true,
    mergeLineageRefs: ['ci-telemetry-lineage'],
    replayFreezeRefs: ['ci-telemetry-replay'],
    governanceRefs: ['ci-telemetry-governance'],
    telemetryRefs: ['ci-telemetry-stream'],
    driftRefs: ['ci-telemetry-drift'],
    ambiguityRefs: ['ci-telemetry-ambiguity'],
    stewardshipRefs: ['ci-telemetry-stewardship'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-runtime-drift',
    recordedAt: '2026-05-11T11:32:00.000Z',
    domain: 'runtime_drift_scoring',
    sourceSystemId: 'ci-drift',
    replayTraceId: 'ci-replay-5',
    freezeIntegrity: 0.94,
    replayFreezeIntegrity: 0.94,
    governanceImmutability: 0.95,
    driftResistance: 0.96,
    runtimeContinuity: 0.94,
    ambiguityPermanence: 0.94,
    immutablePostFreeze: true,
    governanceLocked: true,
    failClosedReady: true,
    mergeLineageRefs: ['ci-drift-lineage'],
    replayFreezeRefs: ['ci-drift-replay'],
    governanceRefs: ['ci-drift-governance'],
    telemetryRefs: ['ci-drift-telemetry'],
    driftRefs: ['ci-drift-score'],
    ambiguityRefs: ['ci-drift-ambiguity'],
    stewardshipRefs: ['ci-drift-stewardship'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-stewardship-freeze',
    recordedAt: '2026-05-11T11:40:00.000Z',
    domain: 'stewardship_enforcement',
    sourceSystemId: 'ci-stewardship',
    replayTraceId: 'ci-replay-6',
    freezeIntegrity: 0.94,
    replayFreezeIntegrity: 0.94,
    governanceImmutability: 0.94,
    driftResistance: 0.94,
    runtimeContinuity: 0.95,
    ambiguityPermanence: 0.94,
    immutablePostFreeze: true,
    governanceLocked: true,
    failClosedReady: true,
    mergeLineageRefs: ['ci-stewardship-lineage'],
    replayFreezeRefs: ['ci-stewardship-replay'],
    governanceRefs: ['ci-stewardship-governance'],
    telemetryRefs: ['ci-stewardship-telemetry'],
    driftRefs: ['ci-stewardship-drift'],
    ambiguityRefs: ['ci-stewardship-ambiguity'],
    stewardshipRefs: ['ci-caretaker-lineage'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-merge-lineage',
    recordedAt: '2026-05-11T11:48:00.000Z',
    domain: 'merge_lineage_reconstruction',
    sourceSystemId: 'ci-lineage',
    replayTraceId: 'ci-replay-7',
    freezeIntegrity: 0.95,
    replayFreezeIntegrity: 0.94,
    governanceImmutability: 0.95,
    driftResistance: 0.94,
    runtimeContinuity: 0.94,
    ambiguityPermanence: 0.94,
    immutablePostFreeze: true,
    governanceLocked: true,
    failClosedReady: true,
    mergeLineageRefs: ['ci-lineage-root'],
    replayFreezeRefs: ['ci-lineage-replay'],
    governanceRefs: ['ci-lineage-governance'],
    telemetryRefs: ['ci-lineage-telemetry'],
    driftRefs: ['ci-lineage-drift'],
    ambiguityRefs: ['ci-lineage-ambiguity'],
    stewardshipRefs: ['ci-lineage-stewardship'],
    ambiguity: null,
  },
];

describe('CI gate - runtime merge freeze', () => {
  it('keeps the runtime-merge-freeze gate id surface explicit and frozen', () => {
    expect(RUNTIME_MERGE_FREEZE_GATE_IDS).toEqual([
      'merge_freeze_verified',
      'replay_integrity_immutable_post_freeze',
      'governance_drift_impossible',
      'ambiguity_permanence_preserved',
      'fail_closed_freeze_semantics',
      'runtime_continuity_measurable',
      'merge_lineage_reconstructable',
    ]);
    expect(Object.isFrozen(RUNTIME_MERGE_FREEZE_GATE_IDS)).toBe(true);
    expect(Object.isFrozen(RUNTIME_MERGE_FREEZE_SENTINELS)).toBe(true);
  });

  it('passes only when freeze, replay, governance, ambiguity, fail-closed, continuity, and lineage gates hold', () => {
    const result = evaluateRuntimeMergeFreeze({
      freezeId: 'ci-runtime-merge-freeze',
      generatedAt: '2026-05-11T12:00:00.000Z',
      evidence,
    });
    const gate = evaluateRuntimeMergeFreezeGate(result);

    expect(result.failClosed).toBe(false);
    expect(gate.pass).toBe(true);
    expect(gate.failedGateIds).toEqual([]);
    expect(gate.gates.map((gateResult: { id: string }) => gateResult.id)).toEqual(RUNTIME_MERGE_FREEZE_GATE_IDS);
  });
});
