import {
  RUNTIME_TRUTH_PERMANENCE_GATE_IDS,
  RUNTIME_TRUTH_PERMANENCE_SENTINELS,
  evaluateRuntimeTruthPermanence,
  evaluateRuntimeTruthPermanenceGate,
  type RuntimeTruthPermanenceEvidence,
} from '../runtimeTruthPermanence';

const evidence: RuntimeTruthPermanenceEvidence[] = [
  {
    evidenceId: 'ci-truth-freeze',
    recordedAt: '2026-05-11T01:00:00.000Z',
    domain: 'post_freeze_truth_verification',
    sourceSystemId: 'ci-post-freeze-truth',
    replayTraceId: 'ci-permanence-replay-1',
    replayFaithfulness: 0.91,
    truthDurability: 0.9,
    ambiguityPermanence: 0.9,
    driftResistance: 0.91,
    runtimeStability: 0.9,
    truthScore: 0.9,
    operationalObservability: 0.9,
    longitudinalDurability: 0.9,
    freezeSealed: true,
    immutable: true,
    failClosedReady: true,
    evidenceRefs: ['ci-evidence-1'],
    lineageRefs: ['ci-lineage-1'],
    ambiguityRefs: ['ci-ambiguity-1'],
    driftTelemetryRefs: ['ci-drift-1'],
    observabilityRefs: ['ci-observable-1'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-truth-replay',
    recordedAt: '2026-05-11T01:08:00.000Z',
    domain: 'replay_truth_durability',
    sourceSystemId: 'ci-replay-truth',
    replayTraceId: 'ci-permanence-replay-2',
    replayFaithfulness: 0.92,
    truthDurability: 0.92,
    ambiguityPermanence: 0.9,
    driftResistance: 0.9,
    runtimeStability: 0.9,
    truthScore: 0.9,
    operationalObservability: 0.9,
    longitudinalDurability: 0.91,
    freezeSealed: true,
    immutable: true,
    failClosedReady: true,
    evidenceRefs: ['ci-evidence-2'],
    lineageRefs: ['ci-lineage-2'],
    ambiguityRefs: ['ci-ambiguity-2'],
    driftTelemetryRefs: ['ci-drift-2'],
    observabilityRefs: ['ci-observable-2'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-truth-ambiguity',
    recordedAt: '2026-05-11T01:16:00.000Z',
    domain: 'ambiguity_permanence_validation',
    sourceSystemId: 'ci-ambiguity-truth',
    replayTraceId: 'ci-permanence-replay-3',
    replayFaithfulness: 0.9,
    truthDurability: 0.9,
    ambiguityPermanence: 0.93,
    driftResistance: 0.9,
    runtimeStability: 0.9,
    truthScore: 0.9,
    operationalObservability: 0.9,
    longitudinalDurability: 0.9,
    freezeSealed: true,
    immutable: true,
    failClosedReady: true,
    evidenceRefs: ['ci-evidence-3'],
    lineageRefs: ['ci-lineage-3'],
    ambiguityRefs: ['ci-ambiguity-3', 'ci-ambiguity-proof-1'],
    driftTelemetryRefs: ['ci-drift-3'],
    observabilityRefs: ['ci-observable-3'],
    ambiguity: 'CI post-freeze truth keeps verifier uncertainty interval visible.',
  },
  {
    evidenceId: 'ci-truth-drift',
    recordedAt: '2026-05-11T01:24:00.000Z',
    domain: 'truth_drift_telemetry',
    sourceSystemId: 'ci-truth-drift',
    replayTraceId: 'ci-permanence-replay-4',
    replayFaithfulness: 0.9,
    truthDurability: 0.9,
    ambiguityPermanence: 0.9,
    driftResistance: 0.93,
    runtimeStability: 0.91,
    truthScore: 0.9,
    operationalObservability: 0.91,
    longitudinalDurability: 0.91,
    freezeSealed: true,
    immutable: true,
    failClosedReady: true,
    evidenceRefs: ['ci-evidence-4'],
    lineageRefs: ['ci-lineage-4'],
    ambiguityRefs: ['ci-ambiguity-4'],
    driftTelemetryRefs: ['ci-drift-4', 'ci-drift-sentinel-1'],
    observabilityRefs: ['ci-observable-4'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-truth-score',
    recordedAt: '2026-05-11T01:32:00.000Z',
    domain: 'runtime_truth_scoring',
    sourceSystemId: 'ci-truth-score',
    replayTraceId: 'ci-permanence-replay-5',
    replayFaithfulness: 0.9,
    truthDurability: 0.9,
    ambiguityPermanence: 0.9,
    driftResistance: 0.9,
    runtimeStability: 0.9,
    truthScore: 0.92,
    operationalObservability: 0.9,
    longitudinalDurability: 0.9,
    freezeSealed: true,
    immutable: true,
    failClosedReady: true,
    evidenceRefs: ['ci-evidence-5', 'ci-score-inputs-1'],
    lineageRefs: ['ci-lineage-5'],
    ambiguityRefs: ['ci-ambiguity-5'],
    driftTelemetryRefs: ['ci-drift-5'],
    observabilityRefs: ['ci-observable-5'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-truth-observable',
    recordedAt: '2026-05-11T01:40:00.000Z',
    domain: 'institutional_truth_observability',
    sourceSystemId: 'ci-truth-observable',
    replayTraceId: 'ci-permanence-replay-6',
    replayFaithfulness: 0.9,
    truthDurability: 0.9,
    ambiguityPermanence: 0.9,
    driftResistance: 0.9,
    runtimeStability: 0.91,
    truthScore: 0.9,
    operationalObservability: 0.93,
    longitudinalDurability: 0.91,
    freezeSealed: true,
    immutable: true,
    failClosedReady: true,
    evidenceRefs: ['ci-evidence-6'],
    lineageRefs: ['ci-lineage-6'],
    ambiguityRefs: ['ci-ambiguity-6'],
    driftTelemetryRefs: ['ci-drift-6'],
    observabilityRefs: ['ci-observable-6', 'ci-operator-panel-1'],
    ambiguity: null,
  },
  {
    evidenceId: 'ci-truth-longitudinal',
    recordedAt: '2026-05-11T01:48:00.000Z',
    domain: 'longitudinal_truth_durability',
    sourceSystemId: 'ci-truth-longitudinal',
    replayTraceId: 'ci-permanence-replay-7',
    replayFaithfulness: 0.9,
    truthDurability: 0.91,
    ambiguityPermanence: 0.9,
    driftResistance: 0.9,
    runtimeStability: 0.91,
    truthScore: 0.9,
    operationalObservability: 0.91,
    longitudinalDurability: 0.93,
    freezeSealed: true,
    immutable: true,
    failClosedReady: true,
    evidenceRefs: ['ci-evidence-7'],
    lineageRefs: ['ci-lineage-7'],
    ambiguityRefs: ['ci-ambiguity-7'],
    driftTelemetryRefs: ['ci-drift-7'],
    observabilityRefs: ['ci-observable-7'],
    ambiguity: null,
  },
];

describe('CI gate - runtime truth permanence verification', () => {
  it('keeps the truth permanence gate id surface explicit and frozen', () => {
    expect(RUNTIME_TRUTH_PERMANENCE_GATE_IDS).toEqual([
      'truth_globally_replay_faithful',
      'ambiguity_permanently_preserved',
      'drift_impossible_post_freeze',
      'fail_closed_truth_semantics',
      'runtime_truth_longitudinally_durable',
      'institutional_truth_operationally_observable',
      'truth_scoring_evidence_derived',
    ]);
    expect(Object.isFrozen(RUNTIME_TRUTH_PERMANENCE_GATE_IDS)).toBe(true);
    expect(Object.isFrozen(RUNTIME_TRUTH_PERMANENCE_SENTINELS)).toBe(true);
  });

  it('passes only when replay truth, ambiguity, drift, fail-closed, durability, observability, and scoring gates hold', () => {
    const result = evaluateRuntimeTruthPermanence({
      permanenceId: 'ci-runtime-truth-permanence',
      generatedAt: '2026-05-11T01:55:00.000Z',
      evidence,
    });
    const gate = evaluateRuntimeTruthPermanenceGate(result);

    expect(result.failClosed).toBe(false);
    expect(gate.pass).toBe(true);
    expect(gate.failedGateIds).toEqual([]);
    expect(gate.gates.map((gateResult: { id: string }) => gateResult.id)).toEqual(RUNTIME_TRUTH_PERMANENCE_GATE_IDS);
  });
});
