import { PrismaClient } from '@prisma/client';
import { anchorEvent } from '../audit/anchor';

const prisma = new PrismaClient();

export interface CredentialForensicsData {
  syntheticDetection: {
    score: number; // 0-100, higher = more likely synthetic
    indicators: string[];
  };
  ocrAnomalies: Array<{
    type: 'spacing' | 'artifact' | 'tampering' | 'font_mismatch';
    location: string;
    severity: 'low' | 'medium' | 'high' | 'critical';
    confidence: number;
  }>;
  fieldMismatches: Array<{
    field: string;
    source1: string;
    source2: string;
    value1: any;
    value2: any;
    severity: 'low' | 'medium' | 'high' | 'critical';
  }>;
  signatureForgery: {
    detected: boolean;
    confidence: number;
    issuer: string;
    anomalies: string[];
  };
  blacklistMatches: Array<{
    entity: string;
    type: 'issuer' | 'verifier' | 'entity';
    reason: string;
  }>;
  whitelistMatches: Array<{
    entity: string;
    type: 'issuer' | 'verifier' | 'entity';
    verified: boolean;
  }>;
  fingerprintMatches: Array<{
    documentId: string;
    similarity: number;
    source: string;
  }>;
  overallRisk: number; // 0-100
  lastUpdated: string;
}

/**
 * Get credential forensics data
 */
export async function getCredentialForensics(credentialId: string): Promise<CredentialForensicsData | null> {
  const record = await prisma.credentialForensics.findFirst({
    where: { credentialId },
    orderBy: { updatedAt: 'desc' },
  });

  if (!record) {
    return null;
  }

  return record.forensics as CredentialForensicsData;
}

/**
 * Update credential forensics data
 */
export async function updateCredentialForensics(
  credentialId: string,
  forensics: CredentialForensicsData,
): Promise<void> {
  await prisma.credentialForensics.create({
    data: {
      credentialId,
      forensics: forensics as any,
      updatedAt: new Date(),
    },
  });
}

/**
 * Detect synthetic documents (AI-generated or modified)
 */
export async function detectSyntheticDocuments(document: {
  content: string;
  metadata: Record<string, any>;
  imageData?: Buffer;
}): Promise<{
  score: number;
  indicators: string[];
}> {
  const indicators: string[] = [];
  let score = 0;

  // Check for AI-generated text patterns
  if (document.content.includes('AI-generated') || document.content.includes('Generated by')) {
    indicators.push('Contains AI generation markers');
    score += 30;
  }

  // Check for unusual patterns
  const repeatedPhrases = document.content.match(/(.{10,})\1{2,}/g);
  if (repeatedPhrases && repeatedPhrases.length > 0) {
    indicators.push('Repeated phrase patterns detected');
    score += 20;
  }

  // Check metadata for inconsistencies
  if (document.metadata.createdAt && document.metadata.modifiedAt) {
    const created = new Date(document.metadata.createdAt);
    const modified = new Date(document.metadata.modifiedAt);
    if (modified.getTime() - created.getTime() < 1000) {
      indicators.push('Suspicious creation/modification timing');
      score += 15;
    }
  }

  // Check for image artifacts (if image data provided)
  if (document.imageData) {
    // Simulate image analysis
    const hasArtifacts = Math.random() > 0.7; // 30% chance of artifacts
    if (hasArtifacts) {
      indicators.push('Image artifacts detected');
      score += 25;
    }
  }

  return {
    score: Math.min(100, score),
    indicators,
  };
}

/**
 * Classify OCR anomalies (odd spacing, artifacts, tampered regions)
 */
export async function classifyOcrAnomalies(ocrData: {
  text: string;
  regions: Array<{
    x: number;
    y: number;
    width: number;
    height: number;
    text: string;
    confidence: number;
  }>;
}): Promise<Array<{
  type: 'spacing' | 'artifact' | 'tampering' | 'font_mismatch';
  location: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  confidence: number;
}>> {
  const anomalies: Array<{
    type: 'spacing' | 'artifact' | 'tampering' | 'font_mismatch';
    location: string;
    severity: 'low' | 'medium' | 'high' | 'critical';
    confidence: number;
  }> = [];

  // Check for spacing anomalies
  for (let i = 0; i < ocrData.regions.length - 1; i++) {
    const current = ocrData.regions[i];
    const next = ocrData.regions[i + 1];
    const spacing = next.x - (current.x + current.width);

    if (spacing < 0) {
      anomalies.push({
        type: 'spacing',
        location: `Region ${i} to ${i + 1}`,
        severity: 'medium',
        confidence: 0.8,
      });
    }
  }

  // Check for low confidence regions (potential artifacts)
  for (const region of ocrData.regions) {
    if (region.confidence < 0.5) {
      anomalies.push({
        type: 'artifact',
        location: `(${region.x}, ${region.y})`,
        severity: region.confidence < 0.3 ? 'high' : 'medium',
        confidence: 1 - region.confidence,
      });
    }
  }

  // Check for suspicious text patterns (potential tampering)
  const suspiciousPatterns = ['XXX', '###', '---', '???'];
  for (const region of ocrData.regions) {
    if (suspiciousPatterns.some((pattern) => region.text.includes(pattern))) {
      anomalies.push({
        type: 'tampering',
        location: `(${region.x}, ${region.y})`,
        severity: 'high',
        confidence: 0.9,
      });
    }
  }

  return anomalies;
}

/**
 * Detect cross-source field mismatches
 */
export async function detectFieldMismatches(sources: Array<{
  source: string;
  fields: Record<string, any>;
}>): Promise<Array<{
  field: string;
  source1: string;
  source2: string;
  value1: any;
  value2: any;
  severity: 'low' | 'medium' | 'high' | 'critical';
}>> {
  const mismatches: Array<{
    field: string;
    source1: string;
    source2: string;
    value1: any;
    value2: any;
    severity: 'low' | 'medium' | 'high' | 'critical';
  }> = [];

  if (sources.length < 2) {
    return mismatches;
  }

  // Compare all pairs of sources
  for (let i = 0; i < sources.length; i++) {
    for (let j = i + 1; j < sources.length; j++) {
      const source1 = sources[i];
      const source2 = sources[j];

      const fields1 = Object.keys(source1.fields);
      const fields2 = Object.keys(source2.fields);

      // Check for common fields
      const commonFields = fields1.filter((f) => f in source2.fields);

      for (const field of commonFields) {
        const value1 = source1.fields[field];
        const value2 = source2.fields[field];

        if (JSON.stringify(value1) !== JSON.stringify(value2)) {
          // Determine severity based on field importance
          const criticalFields = ['licenseNumber', 'npi', 'name', 'dateOfBirth'];
          const highFields = ['expirationDate', 'state', 'specialty'];
          const severity = criticalFields.includes(field)
            ? 'critical'
            : highFields.includes(field)
              ? 'high'
              : 'medium';

          mismatches.push({
            field,
            source1: source1.source,
            source2: source2.source,
            value1,
            value2,
            severity,
          });
        }
      }
    }
  }

  return mismatches;
}

/**
 * Classify signature forgery
 */
export async function classifySignatureForgery(signature: {
  issuer: string;
  signatureData: string | Buffer;
  documentHash: string;
}): Promise<{
  detected: boolean;
  confidence: number;
  issuer: string;
  anomalies: string[];
}> {
  const anomalies: string[] = [];
  let detected = false;
  let confidence = 0;

  // Check for known issuer signatures
  const knownIssuers = ['State Medical Board', 'Nursing Board', 'DEA'];
  const isKnownIssuer = knownIssuers.some((issuer) => signature.issuer.includes(issuer));

  if (!isKnownIssuer) {
    anomalies.push('Unknown issuer');
    confidence += 20;
  }

  // Check signature format (simplified)
  if (typeof signature.signatureData === 'string') {
    if (signature.signatureData.length < 10) {
      anomalies.push('Signature too short');
      confidence += 15;
    }

    if (!signature.signatureData.match(/^[A-Za-z0-9+/=]+$/)) {
      anomalies.push('Invalid signature format');
      confidence += 25;
    }
  }

  // Check document hash consistency
  if (signature.documentHash.length !== 64) {
    anomalies.push('Invalid document hash format');
    confidence += 20;
  }

  detected = confidence > 30;
  confidence = Math.min(100, confidence);

  return {
    detected,
    confidence,
    issuer: signature.issuer,
    anomalies,
  };
}

/**
 * Check global blacklist/whitelist
 */
export async function checkBlacklistWhitelist(entities: Array<{
  name: string;
  type: 'issuer' | 'verifier' | 'entity';
  identifier?: string;
}>): Promise<{
  blacklistMatches: Array<{
    entity: string;
    type: 'issuer' | 'verifier' | 'entity';
    reason: string;
  }>;
  whitelistMatches: Array<{
    entity: string;
    type: 'issuer' | 'verifier' | 'entity';
    verified: boolean;
  }>;
}> {
  // Simulated blacklist/whitelist (in production, this would query a database)
  const blacklist: Array<{ name: string; type: string; reason: string }> = [
    { name: 'Fraudulent Issuer Inc', type: 'issuer', reason: 'Known fraud' },
    { name: 'Suspicious Verifier LLC', type: 'verifier', reason: 'Multiple violations' },
  ];

  const whitelist: Array<{ name: string; type: string }> = [
    { name: 'State Medical Board', type: 'issuer' },
    { name: 'Nursing Board', type: 'issuer' },
    { name: 'DEA', type: 'issuer' },
  ];

  const blacklistMatches: Array<{
    entity: string;
    type: 'issuer' | 'verifier' | 'entity';
    reason: string;
  }> = [];

  const whitelistMatches: Array<{
    entity: string;
    type: 'issuer' | 'verifier' | 'entity';
    verified: boolean;
  }> = [];

  for (const entity of entities) {
    // Check blacklist
    const blacklisted = blacklist.find(
      (b) => b.name.toLowerCase().includes(entity.name.toLowerCase()) && b.type === entity.type,
    );
    if (blacklisted) {
      blacklistMatches.push({
        entity: entity.name,
        type: entity.type,
        reason: blacklisted.reason,
      });
    }

    // Check whitelist
    const whitelisted = whitelist.find(
      (w) => w.name.toLowerCase().includes(entity.name.toLowerCase()) && w.type === entity.type,
    );
    if (whitelisted) {
      whitelistMatches.push({
        entity: entity.name,
        type: entity.type,
        verified: true,
      });
    }
  }

  return { blacklistMatches, whitelistMatches };
}

/**
 * Match document fingerprints across submissions
 */
export async function matchDocumentFingerprints(
  fingerprint: string,
  submissions: Array<{
    documentId: string;
    fingerprint: string;
    source: string;
  }>,
): Promise<Array<{
  documentId: string;
  similarity: number;
  source: string;
}>> {
  const matches: Array<{
    documentId: string;
    similarity: number;
    source: string;
  }> = [];

  for (const submission of submissions) {
    // Simple similarity (in production, use proper fingerprint matching)
    const similarity = fingerprint === submission.fingerprint ? 1.0 : calculateSimilarity(fingerprint, submission.fingerprint);

    if (similarity > 0.8) {
      matches.push({
        documentId: submission.documentId,
        similarity,
        source: submission.source,
      });
    }
  }

  return matches.sort((a, b) => b.similarity - a.similarity);
}

function calculateSimilarity(str1: string, str2: string): number {
  // Simple Levenshtein-based similarity
  const maxLen = Math.max(str1.length, str2.length);
  if (maxLen === 0) {
    return 1.0;
  }

  let matches = 0;
  const minLen = Math.min(str1.length, str2.length);
  for (let i = 0; i < minLen; i++) {
    if (str1[i] === str2[i]) {
      matches++;
    }
  }

  return matches / maxLen;
}

/**
 * Calculate overall forensics risk score
 */
export async function calculateForensicsRisk(forensics: CredentialForensicsData): Promise<number> {
  let risk = 0;

  // Synthetic detection contributes to risk
  risk += forensics.syntheticDetection.score * 0.3;

  // OCR anomalies contribute
  for (const anomaly of forensics.ocrAnomalies) {
    const weight = { low: 5, medium: 10, high: 20, critical: 30 }[anomaly.severity];
    risk += weight * anomaly.confidence;
  }

  // Field mismatches contribute
  for (const mismatch of forensics.fieldMismatches) {
    const weight = { low: 10, medium: 20, high: 30, critical: 40 }[mismatch.severity];
    risk += weight;
  }

  // Signature forgery contributes heavily
  if (forensics.signatureForgery.detected) {
    risk += forensics.signatureForgery.confidence * 0.4;
  }

  // Blacklist matches are critical
  risk += forensics.blacklistMatches.length * 50;

  return Math.min(100, risk);
}

/**
 * Anchor forensics snapshot
 */
export async function anchorForensicsSnapshot(credentialId: string): Promise<void> {
  const forensics = await getCredentialForensics(credentialId);
  if (!forensics) {
    return;
  }

  const riskScore = await calculateForensicsRisk(forensics);

  anchorEvent('credentialForensicsAnchored', {
    credentialId,
    riskScore,
    syntheticScore: forensics.syntheticDetection.score,
    ocrAnomalyCount: forensics.ocrAnomalies.length,
    fieldMismatchCount: forensics.fieldMismatches.length,
    signatureForgeryDetected: forensics.signatureForgery.detected,
    blacklistMatches: forensics.blacklistMatches.length,
    timestamp: new Date().toISOString(),
  });
}

