'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import {
  AlertTriangle,
  CheckCircle2,
  Map as MapIcon,
  MapPin,
  ShieldCheck,
} from 'lucide-react';

interface CompactRuleCondition {
  code: string;
  detail: string;
  passed: boolean;
}

interface DemoCompactEntry {
  compactType: string;
  displayName: string;
  profession: string;
  homeState: string;
  authorizedStates: string[];
  ruleSummary: {
    eligible: boolean;
    reason: string;
    conditions: CompactRuleCondition[];
  };
}

const US_STATES = [
  'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL',
  'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT',
  'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI',
  'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WI', 'WV', 'WY', 'DC',
] as const;

const MOCK_COMPACTS: DemoCompactEntry[] = [
  {
    compactType: 'IMLC',
    displayName: 'Interstate Medical Licensure Compact',
    profession: 'Physician (MD)',
    homeState: 'TX',
    authorizedStates: ['TX', 'WA', 'UT', 'CO', 'AZ', 'OK', 'NM'],
    ruleSummary: {
      eligible: true,
      reason: 'IMLC privilege allows practice in WA',
      conditions: [
        { code: 'home_state_member', detail: 'Home state TX participates in IMLC', passed: true },
        { code: 'active_home_license', detail: 'Active physician license in TX', passed: true },
        { code: 'minimum_practice_time', detail: 'Primary license meets 12-month rule', passed: true },
        { code: 'discipline_check', detail: 'No disciplinary actions found', passed: true },
        { code: 'coverage', detail: 'IMLC privilege lists WA', passed: true },
      ],
    },
  },
  {
    compactType: 'PSYPACT',
    displayName: 'Psychology Interjurisdictional Compact',
    profession: 'Clinical Psychologist',
    homeState: 'AZ',
    authorizedStates: ['AZ', 'WA', 'CO', 'UT', 'ID'],
    ruleSummary: {
      eligible: true,
      reason: 'PSYPACT APIT active for telepsychology in CO',
      conditions: [
        { code: 'active_psychology_license', detail: 'Active psychology license in AZ', passed: true },
        { code: 'epassport', detail: 'PSYPACT e.Passport active', passed: true },
        { code: 'apit_authority', detail: 'APIT authority granted', passed: true },
        { code: 'coverage', detail: 'PSYPACT roster lists CO', passed: true },
      ],
    },
  },
];

export default function ClinicianCompactWalletPage() {
  return (
    <div className="container mx-auto p-6 space-y-8">
      <header className="space-y-2">
        <p className="text-sm text-muted-foreground">Demo &raquo; Clinician &raquo; Compact Wallet</p>
        <h1 className="text-3xl font-bold">Compact Wallet</h1>
        <p className="text-muted-foreground max-w-3xl">
          Review a clinician’s compact credentials, authorized jurisdictions, and rule-check summaries generated by
          the PracticeEligibilityEngine. The map grid highlights every state where the compact allows practice.
        </p>
      </header>

      <div className="grid gap-6">
        {MOCK_COMPACTS.map((compact) => (
          <Card
            key={compact.compactType}
            aria-live="polite"
            aria-label={`${compact.displayName} summary`}
          >
            <CardHeader className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
              <div className="space-y-1">
                <CardTitle className="flex items-center gap-2">
                  <ShieldCheck className="h-5 w-5 text-primary" aria-hidden="true" />
                  {compact.displayName}
                </CardTitle>
                <CardDescription className="flex items-center gap-3 text-sm">
                  <span className="inline-flex items-center gap-1">
                    <MapPin className="h-4 w-4" aria-hidden="true" />
                    Home state {compact.homeState}
                  </span>
                  <Badge variant="secondary">{compact.profession}</Badge>
                </CardDescription>
              </div>
              <div className="text-right">
                <p className={cn('text-sm font-semibold', compact.ruleSummary.eligible ? 'text-green-600' : 'text-amber-600')}>
                  {compact.ruleSummary.reason}
                </p>
                <p className="text-xs text-muted-foreground">
                  {compact.authorizedStates.length} authorized states via {compact.compactType}
                </p>
              </div>
            </CardHeader>
            <CardContent className="space-y-6">
              <section aria-label={`${compact.displayName} conditions`}>
                <h2 className="text-sm font-semibold mb-3 flex items-center gap-2">
                  <ShieldCheck className="h-4 w-4" aria-hidden="true" />
                  Rule checks
                </h2>
                <ul className="space-y-2">
                  {compact.ruleSummary.conditions.map((condition) => (
                    <li key={`${compact.compactType}-${condition.code}`} className="flex items-start gap-2 text-sm">
                      {condition.passed ? (
                        <CheckCircle2 className="h-4 w-4 text-green-600 shrink-0" aria-hidden="true" />
                      ) : (
                        <AlertTriangle className="h-4 w-4 text-amber-600 shrink-0" aria-hidden="true" />
                      )}
                      <span>{condition.detail}</span>
                    </li>
                  ))}
                </ul>
              </section>

              <section aria-label={`${compact.displayName} authorized states`}>
                <div className="flex items-center gap-2 mb-3">
                  <MapIcon className="h-5 w-5 text-muted-foreground" aria-hidden="true" />
                  <h2 className="text-sm font-semibold">Authorized states map</h2>
                </div>
                <p className="sr-only">
                  Authorized states for {compact.compactType}: {compact.authorizedStates.join(', ')}
                </p>
                <div className="grid grid-cols-10 gap-1" role="grid">
                  {US_STATES.map((state) => {
                    const enabled = compact.authorizedStates.includes(state);
                    return (
                      <span
                        key={`${compact.compactType}-${state}`}
                        role="gridcell"
                        aria-label={`${state} ${enabled ? 'authorized' : 'not authorized'}`}
                        className={cn(
                          'text-xs font-semibold px-1.5 py-1 rounded border text-center',
                          enabled ? 'bg-emerald-600 text-white border-emerald-700' : 'bg-muted text-muted-foreground'
                        )}
                      >
                        {state}
                      </span>
                    );
                  })}
                </div>
              </section>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}

