/**
 * NUCC provider-taxonomy → ABMS certificate crosswalk (physician-grouping seed).
 *
 * GENERATED from the NUCC Health Care Provider Taxonomy Code Set v26.1
 * (nucc.org, fetched 2026-08-09) by a hand-curated mapping — codes,
 * classifications, and specializations are verbatim from the source file;
 * the mapping judgments are VitalCV curation. No official NUCC↔ABMS crosswalk
 * exists anywhere; this table is original curation (see the research doc).
 *
 * Coverage (honest): 235 of 238 physician-grouping codes mapped.
 * Deliberately unmapped (3): AOA-certified concepts awaiting AOA
 * certificate modeling (ONMM 204D00000X / 204C00000X) and codes needing further
 * diligence — absent rather than guessed. Non-physician groupings (~645 codes)
 * are a later pass. NUCC licensing: taxonomy use is free; embedding of the full
 * code set for commercial redistribution needs NUCC's (free) license form —
 * flagged as an open item; this seed carries only curated mappings.
 *
 * A 'practice_focus' mapping is a statement about the CODE (no current ABMS
 * certificate exists for it), never a claim about any clinician.
 */

import type { NuccCrosswalkEntry } from './types';

export const NUCC_CROSSWALK: readonly NuccCrosswalkEntry[] = [
  { code: '207K00000X', classification: 'Allergy & Immunology', specialization: null, mapping: { kind: 'certificate', certificateId: 'allergy-immunology' } },
  { code: '207KA0200X', classification: 'Allergy & Immunology', specialization: 'Allergy', mapping: { kind: 'practice_focus' } },
  { code: '207KI0005X', classification: 'Allergy & Immunology', specialization: 'Clinical & Laboratory Immunology', mapping: { kind: 'practice_focus' } },
  { code: '207L00000X', classification: 'Anesthesiology', specialization: null, mapping: { kind: 'certificate', certificateId: 'anesthesiology' } },
  { code: '207LA0401X', classification: 'Anesthesiology', specialization: 'Addiction Medicine', mapping: { kind: 'certificate', certificateId: 'addiction-medicine' } },
  { code: '207LC0200X', classification: 'Anesthesiology', specialization: 'Critical Care Medicine', mapping: { kind: 'certificate', certificateId: 'critical-care-medicine-anesthesiology' } },
  { code: '207LH0002X', classification: 'Anesthesiology', specialization: 'Hospice and Palliative Medicine', mapping: { kind: 'certificate', certificateId: 'hospice-palliative-medicine' } },
  { code: '207LP2900X', classification: 'Anesthesiology', specialization: 'Pain Medicine', mapping: { kind: 'certificate', certificateId: 'pain-medicine' } },
  { code: '207LP3000X', classification: 'Anesthesiology', specialization: 'Pediatric Anesthesiology', mapping: { kind: 'certificate', certificateId: 'pediatric-anesthesiology' } },
  { code: '207LP4000X', classification: 'Anesthesiology', specialization: 'Physician Nutrition Specialist', mapping: { kind: 'practice_focus' } },
  { code: '208U00000X', classification: 'Clinical Pharmacology', specialization: null, mapping: { kind: 'practice_focus' } },
  { code: '208C00000X', classification: 'Colon & Rectal Surgery', specialization: null, mapping: { kind: 'certificate', certificateId: 'colon-rectal-surgery' } },
  { code: '207N00000X', classification: 'Dermatology', specialization: null, mapping: { kind: 'certificate', certificateId: 'dermatology' } },
  { code: '207NI0002X', classification: 'Dermatology', specialization: 'Clinical & Laboratory Dermatological Immunology', mapping: { kind: 'practice_focus' } },
  { code: '207ND0900X', classification: 'Dermatology', specialization: 'Dermatopathology', mapping: { kind: 'certificate', certificateId: 'dermatopathology' } },
  { code: '207ND0101X', classification: 'Dermatology', specialization: 'MOHS-Micrographic Surgery', mapping: { kind: 'certificate', certificateId: 'micrographic-dermatologic-surgery' } },
  { code: '207NP0225X', classification: 'Dermatology', specialization: 'Pediatric Dermatology', mapping: { kind: 'certificate', certificateId: 'pediatric-dermatology' } },
  { code: '207NS0135X', classification: 'Dermatology', specialization: 'Procedural Dermatology', mapping: { kind: 'practice_focus' } },
  { code: '204R00000X', classification: 'Electrodiagnostic Medicine', specialization: null, mapping: { kind: 'practice_focus' } },
  { code: '207P00000X', classification: 'Emergency Medicine', specialization: null, mapping: { kind: 'certificate', certificateId: 'emergency-medicine' } },
  { code: '207PE0004X', classification: 'Emergency Medicine', specialization: 'Emergency Medical Services', mapping: { kind: 'certificate', certificateId: 'emergency-medical-services' } },
  { code: '207PH0002X', classification: 'Emergency Medicine', specialization: 'Hospice and Palliative Medicine', mapping: { kind: 'certificate', certificateId: 'hospice-palliative-medicine' } },
  { code: '207PT0002X', classification: 'Emergency Medicine', specialization: 'Medical Toxicology', mapping: { kind: 'certificate', certificateId: 'medical-toxicology' } },
  { code: '207PP0204X', classification: 'Emergency Medicine', specialization: 'Pediatric Emergency Medicine', mapping: { kind: 'certificate', certificateId: 'pediatric-emergency-medicine' } },
  { code: '207PS0010X', classification: 'Emergency Medicine', specialization: 'Sports Medicine', mapping: { kind: 'certificate', certificateId: 'sports-medicine' } },
  { code: '207PE0005X', classification: 'Emergency Medicine', specialization: 'Undersea and Hyperbaric Medicine', mapping: { kind: 'certificate', certificateId: 'undersea-hyperbaric-medicine' } },
  { code: '207Q00000X', classification: 'Family Medicine', specialization: null, mapping: { kind: 'certificate', certificateId: 'family-medicine' } },
  { code: '207QA0401X', classification: 'Family Medicine', specialization: 'Addiction Medicine', mapping: { kind: 'certificate', certificateId: 'addiction-medicine' } },
  { code: '207QA0000X', classification: 'Family Medicine', specialization: 'Adolescent Medicine', mapping: { kind: 'certificate', certificateId: 'adolescent-medicine' } },
  { code: '207QA0505X', classification: 'Family Medicine', specialization: 'Adult Medicine', mapping: { kind: 'practice_focus' } },
  { code: '207QD0401X', classification: 'Family Medicine', specialization: 'Diabetology', mapping: { kind: 'practice_focus' } },
  { code: '207QG0300X', classification: 'Family Medicine', specialization: 'Geriatric Medicine', mapping: { kind: 'certificate', certificateId: 'geriatric-medicine' } },
  { code: '207QH0002X', classification: 'Family Medicine', specialization: 'Hospice and Palliative Medicine', mapping: { kind: 'certificate', certificateId: 'hospice-palliative-medicine' } },
  { code: '207QB0002X', classification: 'Family Medicine', specialization: 'Obesity Medicine', mapping: { kind: 'practice_focus' } },
  { code: '207QP0002X', classification: 'Family Medicine', specialization: 'Physician Nutrition Specialist', mapping: { kind: 'practice_focus' } },
  { code: '207QS1201X', classification: 'Family Medicine', specialization: 'Sleep Medicine', mapping: { kind: 'certificate', certificateId: 'sleep-medicine' } },
  { code: '207QS0010X', classification: 'Family Medicine', specialization: 'Sports Medicine', mapping: { kind: 'certificate', certificateId: 'sports-medicine' } },
  { code: '208D00000X', classification: 'General Practice', specialization: null, mapping: { kind: 'practice_focus' } },
  { code: '208M00000X', classification: 'Hospitalist', specialization: null, mapping: { kind: 'practice_focus' } },
  { code: '202C00000X', classification: 'Independent Medical Examiner', specialization: null, mapping: { kind: 'practice_focus' } },
  { code: '202D00000X', classification: 'Integrative Medicine', specialization: null, mapping: { kind: 'practice_focus' } },
  { code: '207R00000X', classification: 'Internal Medicine', specialization: null, mapping: { kind: 'certificate', certificateId: 'internal-medicine' } },
  { code: '207RA0401X', classification: 'Internal Medicine', specialization: 'Addiction Medicine', mapping: { kind: 'certificate', certificateId: 'addiction-medicine' } },
  { code: '207RA0000X', classification: 'Internal Medicine', specialization: 'Adolescent Medicine', mapping: { kind: 'certificate', certificateId: 'adolescent-medicine' } },
  { code: '207RA0002X', classification: 'Internal Medicine', specialization: 'Adult Congenital Heart Disease', mapping: { kind: 'certificate', certificateId: 'adult-congenital-heart-disease' } },
  { code: '207RA0001X', classification: 'Internal Medicine', specialization: 'Advanced Heart Failure and Transplant Cardiology', mapping: { kind: 'certificate', certificateId: 'advanced-heart-failure-transplant-cardiology' } },
  { code: '207RA0201X', classification: 'Internal Medicine', specialization: 'Allergy & Immunology', mapping: { kind: 'certificate', certificateId: 'allergy-immunology' } },
  { code: '207RC0000X', classification: 'Internal Medicine', specialization: 'Cardiovascular Disease', mapping: { kind: 'certificate', certificateId: 'cardiovascular-disease' } },
  { code: '207RI0001X', classification: 'Internal Medicine', specialization: 'Clinical & Laboratory Immunology', mapping: { kind: 'practice_focus' } },
  { code: '207RC0001X', classification: 'Internal Medicine', specialization: 'Clinical Cardiac Electrophysiology', mapping: { kind: 'certificate', certificateId: 'clinical-cardiac-electrophysiology' } },
  { code: '207RC0200X', classification: 'Internal Medicine', specialization: 'Critical Care Medicine', mapping: { kind: 'certificate', certificateId: 'critical-care-medicine-internal-medicine' } },
  { code: '207QB0505X', classification: 'Internal Medicine', specialization: 'Diabetology', mapping: { kind: 'practice_focus' } },
  { code: '207RE0101X', classification: 'Internal Medicine', specialization: 'Endocrinology, Diabetes & Metabolism', mapping: { kind: 'certificate', certificateId: 'endocrinology-diabetes-metabolism' } },
  { code: '207RG0100X', classification: 'Internal Medicine', specialization: 'Gastroenterology', mapping: { kind: 'certificate', certificateId: 'gastroenterology' } },
  { code: '207RG0300X', classification: 'Internal Medicine', specialization: 'Geriatric Medicine', mapping: { kind: 'certificate', certificateId: 'geriatric-medicine' } },
  { code: '207RH0000X', classification: 'Internal Medicine', specialization: 'Hematology', mapping: { kind: 'certificate', certificateId: 'hematology' } },
  { code: '207RH0003X', classification: 'Internal Medicine', specialization: 'Hematology & Oncology', mapping: { kind: 'practice_focus' } },
  { code: '207RI0008X', classification: 'Internal Medicine', specialization: 'Hepatology', mapping: { kind: 'practice_focus' } },
  { code: '207RH0002X', classification: 'Internal Medicine', specialization: 'Hospice and Palliative Medicine', mapping: { kind: 'certificate', certificateId: 'hospice-palliative-medicine' } },
  { code: '207RH0005X', classification: 'Internal Medicine', specialization: 'Hypertension Specialist', mapping: { kind: 'practice_focus' } },
  { code: '207RI0200X', classification: 'Internal Medicine', specialization: 'Infectious Disease', mapping: { kind: 'certificate', certificateId: 'infectious-disease' } },
  { code: '207RI0011X', classification: 'Internal Medicine', specialization: 'Interventional Cardiology', mapping: { kind: 'certificate', certificateId: 'interventional-cardiology' } },
  { code: '207RM1200X', classification: 'Internal Medicine', specialization: 'Magnetic Resonance Imaging (MRI)', mapping: { kind: 'practice_focus' } },
  { code: '207RX0202X', classification: 'Internal Medicine', specialization: 'Medical Oncology', mapping: { kind: 'certificate', certificateId: 'medical-oncology' } },
  { code: '207RN0300X', classification: 'Internal Medicine', specialization: 'Nephrology', mapping: { kind: 'certificate', certificateId: 'nephrology' } },
  { code: '207RB0002X', classification: 'Internal Medicine', specialization: 'Obesity Medicine', mapping: { kind: 'practice_focus' } },
  { code: '207RP1002X', classification: 'Internal Medicine', specialization: 'Physician Nutrition Specialist', mapping: { kind: 'practice_focus' } },
  { code: '207RP1001X', classification: 'Internal Medicine', specialization: 'Pulmonary Disease', mapping: { kind: 'certificate', certificateId: 'pulmonary-disease' } },
  { code: '207RR0500X', classification: 'Internal Medicine', specialization: 'Rheumatology', mapping: { kind: 'certificate', certificateId: 'rheumatology' } },
  { code: '207RS0012X', classification: 'Internal Medicine', specialization: 'Sleep Medicine', mapping: { kind: 'certificate', certificateId: 'sleep-medicine' } },
  { code: '207RS0010X', classification: 'Internal Medicine', specialization: 'Sports Medicine', mapping: { kind: 'certificate', certificateId: 'sports-medicine' } },
  { code: '207RT0003X', classification: 'Internal Medicine', specialization: 'Transplant Hepatology', mapping: { kind: 'certificate', certificateId: 'transplant-hepatology' } },
  { code: '209800000X', classification: 'Legal Medicine', specialization: null, mapping: { kind: 'practice_focus' } },
  { code: '207SG0202X', classification: 'Medical Genetics', specialization: 'Clinical Biochemical Genetics', mapping: { kind: 'certificate', certificateId: 'clinical-biochemical-genetics' } },
  { code: '207SC0300X', classification: 'Medical Genetics', specialization: 'Clinical Cytogenetics', mapping: { kind: 'certificate', certificateId: 'laboratory-genetics-genomics' }, note: 'Legacy Clinical Cytogenetics; merged into Laboratory Genetics and Genomics (2017).' },
  { code: '207SG0201X', classification: 'Medical Genetics', specialization: 'Clinical Genetics (M.D.)', mapping: { kind: 'certificate', certificateId: 'clinical-genetics-genomics' } },
  { code: '207SG0203X', classification: 'Medical Genetics', specialization: 'Clinical Molecular Genetics', mapping: { kind: 'certificate', certificateId: 'laboratory-genetics-genomics' }, note: 'Legacy Clinical Molecular Genetics; merged into Laboratory Genetics and Genomics (2017).' },
  { code: '207SG0207X', classification: 'Medical Genetics', specialization: 'Medical Biochemical Genetics', mapping: { kind: 'certificate', certificateId: 'medical-biochemical-genetics' } },
  { code: '207SM0001X', classification: 'Medical Genetics', specialization: 'Molecular Genetic Pathology', mapping: { kind: 'certificate', certificateId: 'molecular-genetic-pathology' } },
  { code: '207SG0205X', classification: 'Medical Genetics', specialization: 'Ph.D. Medical Genetics', mapping: { kind: 'practice_focus' } },
  { code: '207T00000X', classification: 'Neurological Surgery', specialization: null, mapping: { kind: 'certificate', certificateId: 'neurological-surgery' } },
  { code: '207U00000X', classification: 'Nuclear Medicine', specialization: null, mapping: { kind: 'certificate', certificateId: 'nuclear-medicine' } },
  { code: '207UN0903X', classification: 'Nuclear Medicine', specialization: 'In Vivo & In Vitro Nuclear Medicine', mapping: { kind: 'practice_focus' } },
  { code: '207UN0901X', classification: 'Nuclear Medicine', specialization: 'Nuclear Cardiology', mapping: { kind: 'practice_focus' } },
  { code: '207UN0902X', classification: 'Nuclear Medicine', specialization: 'Nuclear Imaging & Therapy', mapping: { kind: 'practice_focus' } },
  { code: '207V00000X', classification: 'Obstetrics & Gynecology', specialization: null, mapping: { kind: 'certificate', certificateId: 'obstetrics-gynecology' } },
  { code: '207VC0300X', classification: 'Obstetrics & Gynecology', specialization: 'Complex Family Planning', mapping: { kind: 'certificate', certificateId: 'complex-family-planning' } },
  { code: '207VC0200X', classification: 'Obstetrics & Gynecology', specialization: 'Critical Care Medicine', mapping: { kind: 'certificate', certificateId: 'critical-care-medicine-anesthesiology' } },
  { code: '207VX0201X', classification: 'Obstetrics & Gynecology', specialization: 'Gynecologic Oncology', mapping: { kind: 'certificate', certificateId: 'gynecologic-oncology' } },
  { code: '207VG0400X', classification: 'Obstetrics & Gynecology', specialization: 'Gynecology', mapping: { kind: 'practice_focus' } },
  { code: '207VH0002X', classification: 'Obstetrics & Gynecology', specialization: 'Hospice and Palliative Medicine', mapping: { kind: 'certificate', certificateId: 'hospice-palliative-medicine' } },
  { code: '207VM0101X', classification: 'Obstetrics & Gynecology', specialization: 'Maternal & Fetal Medicine', mapping: { kind: 'certificate', certificateId: 'maternal-fetal-medicine' } },
  { code: '207VB0002X', classification: 'Obstetrics & Gynecology', specialization: 'Obesity Medicine', mapping: { kind: 'practice_focus' } },
  { code: '207VX0000X', classification: 'Obstetrics & Gynecology', specialization: 'Obstetrics', mapping: { kind: 'practice_focus' } },
  { code: '207VE0102X', classification: 'Obstetrics & Gynecology', specialization: 'Reproductive Endocrinology', mapping: { kind: 'certificate', certificateId: 'reproductive-endocrinology-infertility' } },
  { code: '207VF0040X', classification: 'Obstetrics & Gynecology', specialization: 'Urogynecology and Reconstructive Pelvic Surgery', mapping: { kind: 'certificate', certificateId: 'urogynecology-reconstructive-pelvic-surgery' } },
  { code: '207W00000X', classification: 'Ophthalmology', specialization: null, mapping: { kind: 'certificate', certificateId: 'ophthalmology' } },
  { code: '207WX0120X', classification: 'Ophthalmology', specialization: 'Cornea and External Diseases Specialist', mapping: { kind: 'practice_focus' } },
  { code: '207WX0009X', classification: 'Ophthalmology', specialization: 'Glaucoma Specialist', mapping: { kind: 'practice_focus' } },
  { code: '207WX0109X', classification: 'Ophthalmology', specialization: 'Neuro-ophthalmology', mapping: { kind: 'practice_focus' } },
  { code: '207WX0200X', classification: 'Ophthalmology', specialization: 'Ophthalmic Plastic and Reconstructive Surgery', mapping: { kind: 'practice_focus' } },
  { code: '207WX0110X', classification: 'Ophthalmology', specialization: 'Pediatric Ophthalmology and Strabismus Specialist', mapping: { kind: 'practice_focus' } },
  { code: '207WX0107X', classification: 'Ophthalmology', specialization: 'Retina Specialist', mapping: { kind: 'practice_focus' } },
  { code: '207WX0108X', classification: 'Ophthalmology', specialization: 'Uveitis and Ocular Inflammatory Disease', mapping: { kind: 'practice_focus' } },
  { code: '204E00000X', classification: 'Oral & Maxillofacial Surgery', specialization: null, mapping: { kind: 'practice_focus' } },
  { code: '207X00000X', classification: 'Orthopaedic Surgery', specialization: null, mapping: { kind: 'certificate', certificateId: 'orthopaedic-surgery' } },
  { code: '207XS0114X', classification: 'Orthopaedic Surgery', specialization: 'Adult Reconstructive Orthopaedic Surgery', mapping: { kind: 'practice_focus' } },
  { code: '207XX0004X', classification: 'Orthopaedic Surgery', specialization: 'Foot and Ankle Surgery', mapping: { kind: 'practice_focus' } },
  { code: '207XS0106X', classification: 'Orthopaedic Surgery', specialization: 'Hand Surgery', mapping: { kind: 'certificate', certificateId: 'surgery-of-the-hand' } },
  { code: '207XS0117X', classification: 'Orthopaedic Surgery', specialization: 'Orthopaedic Surgery of the Spine', mapping: { kind: 'practice_focus' } },
  { code: '207XX0801X', classification: 'Orthopaedic Surgery', specialization: 'Orthopaedic Trauma', mapping: { kind: 'practice_focus' } },
  { code: '207XP3100X', classification: 'Orthopaedic Surgery', specialization: 'Pediatric Orthopaedic Surgery', mapping: { kind: 'practice_focus' } },
  { code: '207XX0005X', classification: 'Orthopaedic Surgery', specialization: 'Sports Medicine', mapping: { kind: 'certificate', certificateId: 'orthopaedic-sports-medicine' } },
  { code: '207Y00000X', classification: 'Otolaryngology', specialization: null, mapping: { kind: 'certificate', certificateId: 'otolaryngology-hns' } },
  { code: '207YS0123X', classification: 'Otolaryngology', specialization: 'Facial Plastic Surgery', mapping: { kind: 'practice_focus' } },
  { code: '207YX0602X', classification: 'Otolaryngology', specialization: 'Otolaryngic Allergy', mapping: { kind: 'practice_focus' } },
  { code: '207YX0901X', classification: 'Otolaryngology', specialization: 'Otology & Neurotology', mapping: { kind: 'certificate', certificateId: 'neurotology' } },
  { code: '207YP0228X', classification: 'Otolaryngology', specialization: 'Pediatric Otolaryngology', mapping: { kind: 'practice_focus' } },
  { code: '207YX0007X', classification: 'Otolaryngology', specialization: 'Plastic Surgery within the Head & Neck', mapping: { kind: 'certificate', certificateId: 'plastic-surgery-head-neck' } },
  { code: '207YS0012X', classification: 'Otolaryngology', specialization: 'Sleep Medicine', mapping: { kind: 'certificate', certificateId: 'sleep-medicine' } },
  { code: '208VP0014X', classification: 'Pain Medicine', specialization: 'Interventional Pain Medicine', mapping: { kind: 'practice_focus' } },
  { code: '208VP0000X', classification: 'Pain Medicine', specialization: 'Pain Medicine', mapping: { kind: 'certificate', certificateId: 'pain-medicine' } },
  { code: '207ZP0101X', classification: 'Pathology', specialization: 'Anatomic Pathology', mapping: { kind: 'certificate', certificateId: 'pathology-anatomic' } },
  { code: '207ZP0102X', classification: 'Pathology', specialization: 'Anatomic Pathology & Clinical Pathology', mapping: { kind: 'certificate', certificateId: 'pathology-anatomic-clinical' } },
  { code: '207ZB0001X', classification: 'Pathology', specialization: 'Blood Banking & Transfusion Medicine', mapping: { kind: 'certificate', certificateId: 'blood-banking-transfusion-medicine' } },
  { code: '207ZP0104X', classification: 'Pathology', specialization: 'Chemical Pathology', mapping: { kind: 'certificate', certificateId: 'chemical-pathology' } },
  { code: '207ZC0008X', classification: 'Pathology', specialization: 'Clinical Informatics', mapping: { kind: 'certificate', certificateId: 'clinical-informatics' } },
  { code: '207ZC0006X', classification: 'Pathology', specialization: 'Clinical Pathology', mapping: { kind: 'certificate', certificateId: 'pathology-clinical' } },
  { code: '207ZP0105X', classification: 'Pathology', specialization: 'Clinical Pathology/Laboratory Medicine', mapping: { kind: 'practice_focus' } },
  { code: '207ZC0500X', classification: 'Pathology', specialization: 'Cytopathology', mapping: { kind: 'certificate', certificateId: 'cytopathology' } },
  { code: '207ZD0900X', classification: 'Pathology', specialization: 'Dermatopathology', mapping: { kind: 'certificate', certificateId: 'dermatopathology' } },
  { code: '207ZF0201X', classification: 'Pathology', specialization: 'Forensic Pathology', mapping: { kind: 'certificate', certificateId: 'forensic-pathology' } },
  { code: '207ZH0000X', classification: 'Pathology', specialization: 'Hematology', mapping: { kind: 'certificate', certificateId: 'hematopathology' } },
  { code: '207ZI0100X', classification: 'Pathology', specialization: 'Immunopathology', mapping: { kind: 'practice_focus' } },
  { code: '207ZM0300X', classification: 'Pathology', specialization: 'Medical Microbiology', mapping: { kind: 'certificate', certificateId: 'medical-microbiology-pathology' } },
  { code: '207ZP0007X', classification: 'Pathology', specialization: 'Molecular Genetic Pathology', mapping: { kind: 'certificate', certificateId: 'molecular-genetic-pathology' } },
  { code: '207ZN0500X', classification: 'Pathology', specialization: 'Neuropathology', mapping: { kind: 'certificate', certificateId: 'neuropathology' } },
  { code: '207ZP0213X', classification: 'Pathology', specialization: 'Pediatric Pathology', mapping: { kind: 'certificate', certificateId: 'pediatric-pathology' } },
  { code: '208000000X', classification: 'Pediatrics', specialization: null, mapping: { kind: 'certificate', certificateId: 'pediatrics' } },
  { code: '2080A0000X', classification: 'Pediatrics', specialization: 'Adolescent Medicine', mapping: { kind: 'certificate', certificateId: 'adolescent-medicine' } },
  { code: '2080C0008X', classification: 'Pediatrics', specialization: 'Child Abuse Pediatrics', mapping: { kind: 'certificate', certificateId: 'child-abuse-pediatrics' } },
  { code: '2080I0007X', classification: 'Pediatrics', specialization: 'Clinical & Laboratory Immunology', mapping: { kind: 'practice_focus' } },
  { code: '2080P0006X', classification: 'Pediatrics', specialization: 'Developmental - Behavioral Pediatrics', mapping: { kind: 'certificate', certificateId: 'developmental-behavioral-pediatrics' } },
  { code: '2080H0002X', classification: 'Pediatrics', specialization: 'Hospice and Palliative Medicine', mapping: { kind: 'certificate', certificateId: 'hospice-palliative-medicine' } },
  { code: '2080T0002X', classification: 'Pediatrics', specialization: 'Medical Toxicology', mapping: { kind: 'certificate', certificateId: 'medical-toxicology' } },
  { code: '2080N0001X', classification: 'Pediatrics', specialization: 'Neonatal-Perinatal Medicine', mapping: { kind: 'certificate', certificateId: 'neonatal-perinatal-medicine' } },
  { code: '2080P0008X', classification: 'Pediatrics', specialization: 'Neurodevelopmental Disabilities', mapping: { kind: 'certificate', certificateId: 'neurodevelopmental-disabilities' } },
  { code: '2080B0002X', classification: 'Pediatrics', specialization: 'Obesity Medicine', mapping: { kind: 'practice_focus' } },
  { code: '2080P0201X', classification: 'Pediatrics', specialization: 'Pediatric Allergy/Immunology', mapping: { kind: 'certificate', certificateId: 'allergy-immunology' } },
  { code: '2080P0202X', classification: 'Pediatrics', specialization: 'Pediatric Cardiology', mapping: { kind: 'certificate', certificateId: 'pediatric-cardiology' } },
  { code: '2080P0203X', classification: 'Pediatrics', specialization: 'Pediatric Critical Care Medicine', mapping: { kind: 'certificate', certificateId: 'pediatric-critical-care-medicine' } },
  { code: '2080P0204X', classification: 'Pediatrics', specialization: 'Pediatric Emergency Medicine', mapping: { kind: 'certificate', certificateId: 'pediatric-emergency-medicine' } },
  { code: '2080P0205X', classification: 'Pediatrics', specialization: 'Pediatric Endocrinology', mapping: { kind: 'certificate', certificateId: 'pediatric-endocrinology' } },
  { code: '2080P0206X', classification: 'Pediatrics', specialization: 'Pediatric Gastroenterology', mapping: { kind: 'certificate', certificateId: 'pediatric-gastroenterology' } },
  { code: '2080P0207X', classification: 'Pediatrics', specialization: 'Pediatric Hematology-Oncology', mapping: { kind: 'certificate', certificateId: 'pediatric-hematology-oncology' } },
  { code: '2080P0208X', classification: 'Pediatrics', specialization: 'Pediatric Infectious Diseases', mapping: { kind: 'certificate', certificateId: 'pediatric-infectious-diseases' } },
  { code: '2080P0210X', classification: 'Pediatrics', specialization: 'Pediatric Nephrology', mapping: { kind: 'certificate', certificateId: 'pediatric-nephrology' } },
  { code: '2080P0214X', classification: 'Pediatrics', specialization: 'Pediatric Pulmonology', mapping: { kind: 'certificate', certificateId: 'pediatric-pulmonology' } },
  { code: '2080P0216X', classification: 'Pediatrics', specialization: 'Pediatric Rheumatology', mapping: { kind: 'certificate', certificateId: 'pediatric-rheumatology' } },
  { code: '2080T0004X', classification: 'Pediatrics', specialization: 'Pediatric Transplant Hepatology', mapping: { kind: 'certificate', certificateId: 'pediatric-transplant-hepatology' } },
  { code: '2080P1004X', classification: 'Pediatrics', specialization: 'Physician Nutrition Specialist', mapping: { kind: 'practice_focus' } },
  { code: '2080S0012X', classification: 'Pediatrics', specialization: 'Sleep Medicine', mapping: { kind: 'certificate', certificateId: 'sleep-medicine' } },
  { code: '2080S0010X', classification: 'Pediatrics', specialization: 'Sports Medicine', mapping: { kind: 'certificate', certificateId: 'sports-medicine' } },
  { code: '202K00000X', classification: 'Phlebology', specialization: null, mapping: { kind: 'practice_focus' } },
  { code: '208100000X', classification: 'Physical Medicine & Rehabilitation', specialization: null, mapping: { kind: 'certificate', certificateId: 'physical-medicine-rehabilitation' } },
  { code: '2081P0301X', classification: 'Physical Medicine & Rehabilitation', specialization: 'Brain Injury Medicine', mapping: { kind: 'certificate', certificateId: 'brain-injury-medicine' } },
  { code: '2081H0002X', classification: 'Physical Medicine & Rehabilitation', specialization: 'Hospice and Palliative Medicine', mapping: { kind: 'certificate', certificateId: 'hospice-palliative-medicine' } },
  { code: '2081N0008X', classification: 'Physical Medicine & Rehabilitation', specialization: 'Neuromuscular Medicine', mapping: { kind: 'certificate', certificateId: 'neuromuscular-medicine' } },
  { code: '2081P2900X', classification: 'Physical Medicine & Rehabilitation', specialization: 'Pain Medicine', mapping: { kind: 'certificate', certificateId: 'pain-medicine' } },
  { code: '2081P0010X', classification: 'Physical Medicine & Rehabilitation', specialization: 'Pediatric Rehabilitation Medicine', mapping: { kind: 'certificate', certificateId: 'pediatric-rehabilitation-medicine' } },
  { code: '2081P0004X', classification: 'Physical Medicine & Rehabilitation', specialization: 'Spinal Cord Injury Medicine', mapping: { kind: 'certificate', certificateId: 'spinal-cord-injury-medicine' } },
  { code: '2081S0010X', classification: 'Physical Medicine & Rehabilitation', specialization: 'Sports Medicine', mapping: { kind: 'certificate', certificateId: 'sports-medicine' } },
  { code: '208200000X', classification: 'Plastic Surgery', specialization: null, mapping: { kind: 'certificate', certificateId: 'plastic-surgery' } },
  { code: '2082S0099X', classification: 'Plastic Surgery', specialization: 'Plastic Surgery Within the Head and Neck', mapping: { kind: 'certificate', certificateId: 'plastic-surgery-head-neck' } },
  { code: '2082S0105X', classification: 'Plastic Surgery', specialization: 'Surgery of the Hand', mapping: { kind: 'certificate', certificateId: 'surgery-of-the-hand' } },
  { code: '2083A0300X', classification: 'Preventive Medicine', specialization: 'Addiction Medicine', mapping: { kind: 'certificate', certificateId: 'addiction-medicine' } },
  { code: '2083A0100X', classification: 'Preventive Medicine', specialization: 'Aerospace Medicine', mapping: { kind: 'certificate', certificateId: 'aerospace-medicine' } },
  { code: '2083C0008X', classification: 'Preventive Medicine', specialization: 'Clinical Informatics', mapping: { kind: 'certificate', certificateId: 'clinical-informatics' } },
  { code: '2083T0002X', classification: 'Preventive Medicine', specialization: 'Medical Toxicology', mapping: { kind: 'certificate', certificateId: 'medical-toxicology' } },
  { code: '2083B0002X', classification: 'Preventive Medicine', specialization: 'Obesity Medicine', mapping: { kind: 'practice_focus' } },
  { code: '2083X0100X', classification: 'Preventive Medicine', specialization: 'Occupational Medicine', mapping: { kind: 'certificate', certificateId: 'occupational-environmental-medicine' } },
  { code: '2083P0500X', classification: 'Preventive Medicine', specialization: 'Preventive Medicine/Occupational Environmental Medicine', mapping: { kind: 'practice_focus' } },
  { code: '2083P0901X', classification: 'Preventive Medicine', specialization: 'Public Health & General Preventive Medicine', mapping: { kind: 'certificate', certificateId: 'public-health-general-preventive-medicine' } },
  { code: '2083S0010X', classification: 'Preventive Medicine', specialization: 'Sports Medicine', mapping: { kind: 'certificate', certificateId: 'sports-medicine' } },
  { code: '2083P0011X', classification: 'Preventive Medicine', specialization: 'Undersea and Hyperbaric Medicine', mapping: { kind: 'certificate', certificateId: 'undersea-hyperbaric-medicine' } },
  { code: '2084A0401X', classification: 'Psychiatry & Neurology', specialization: 'Addiction Medicine', mapping: { kind: 'certificate', certificateId: 'addiction-medicine' } },
  { code: '2084P0802X', classification: 'Psychiatry & Neurology', specialization: 'Addiction Psychiatry', mapping: { kind: 'certificate', certificateId: 'addiction-psychiatry' } },
  { code: '2084B0040X', classification: 'Psychiatry & Neurology', specialization: 'Behavioral Neurology & Neuropsychiatry', mapping: { kind: 'practice_focus' } },
  { code: '2084P0301X', classification: 'Psychiatry & Neurology', specialization: 'Brain Injury Medicine', mapping: { kind: 'certificate', certificateId: 'brain-injury-medicine' } },
  { code: '2084P0804X', classification: 'Psychiatry & Neurology', specialization: 'Child & Adolescent Psychiatry', mapping: { kind: 'certificate', certificateId: 'child-adolescent-psychiatry' } },
  { code: '2084N0600X', classification: 'Psychiatry & Neurology', specialization: 'Clinical Neurophysiology', mapping: { kind: 'certificate', certificateId: 'clinical-neurophysiology' } },
  { code: '2084D0003X', classification: 'Psychiatry & Neurology', specialization: 'Diagnostic Neuroimaging', mapping: { kind: 'practice_focus' } },
  { code: '2084E0001X', classification: 'Psychiatry & Neurology', specialization: 'Epilepsy', mapping: { kind: 'certificate', certificateId: 'epilepsy' } },
  { code: '2084F0202X', classification: 'Psychiatry & Neurology', specialization: 'Forensic Psychiatry', mapping: { kind: 'certificate', certificateId: 'forensic-psychiatry' } },
  { code: '2084P0805X', classification: 'Psychiatry & Neurology', specialization: 'Geriatric Psychiatry', mapping: { kind: 'certificate', certificateId: 'geriatric-psychiatry' } },
  { code: '2084H0002X', classification: 'Psychiatry & Neurology', specialization: 'Hospice and Palliative Medicine', mapping: { kind: 'certificate', certificateId: 'hospice-palliative-medicine' } },
  { code: '2084A2900X', classification: 'Psychiatry & Neurology', specialization: 'Neurocritical Care', mapping: { kind: 'certificate', certificateId: 'neurocritical-care' } },
  { code: '2084P0005X', classification: 'Psychiatry & Neurology', specialization: 'Neurodevelopmental Disabilities', mapping: { kind: 'certificate', certificateId: 'neurodevelopmental-disabilities' } },
  { code: '2084N0400X', classification: 'Psychiatry & Neurology', specialization: 'Neurology', mapping: { kind: 'certificate', certificateId: 'neurology' } },
  { code: '2084N0402X', classification: 'Psychiatry & Neurology', specialization: 'Neurology with Special Qualifications in Child Neurology', mapping: { kind: 'certificate', certificateId: 'neurology-child' } },
  { code: '2084N0008X', classification: 'Psychiatry & Neurology', specialization: 'Neuromuscular Medicine', mapping: { kind: 'certificate', certificateId: 'neuromuscular-medicine' } },
  { code: '2084B0002X', classification: 'Psychiatry & Neurology', specialization: 'Obesity Medicine', mapping: { kind: 'practice_focus' } },
  { code: '2084P2900X', classification: 'Psychiatry & Neurology', specialization: 'Pain Medicine', mapping: { kind: 'certificate', certificateId: 'pain-medicine' } },
  { code: '2084P0800X', classification: 'Psychiatry & Neurology', specialization: 'Psychiatry', mapping: { kind: 'certificate', certificateId: 'psychiatry' } },
  { code: '2084P0015X', classification: 'Psychiatry & Neurology', specialization: 'Psychosomatic Medicine', mapping: { kind: 'certificate', certificateId: 'consultation-liaison-psychiatry' }, note: 'Legacy "Psychosomatic Medicine" label; certificate renamed Consultation-Liaison Psychiatry (2018).' },
  { code: '2084S0012X', classification: 'Psychiatry & Neurology', specialization: 'Sleep Medicine', mapping: { kind: 'certificate', certificateId: 'sleep-medicine' } },
  { code: '2084S0010X', classification: 'Psychiatry & Neurology', specialization: 'Sports Medicine', mapping: { kind: 'certificate', certificateId: 'sports-medicine' } },
  { code: '2084V0102X', classification: 'Psychiatry & Neurology', specialization: 'Vascular Neurology', mapping: { kind: 'certificate', certificateId: 'vascular-neurology' } },
  { code: '2085B0100X', classification: 'Radiology', specialization: 'Body Imaging', mapping: { kind: 'practice_focus' } },
  { code: '2085D0003X', classification: 'Radiology', specialization: 'Diagnostic Neuroimaging', mapping: { kind: 'practice_focus' } },
  { code: '2085R0202X', classification: 'Radiology', specialization: 'Diagnostic Radiology', mapping: { kind: 'certificate', certificateId: 'diagnostic-radiology' } },
  { code: '2085U0001X', classification: 'Radiology', specialization: 'Diagnostic Ultrasound', mapping: { kind: 'practice_focus' } },
  { code: '2085H0002X', classification: 'Radiology', specialization: 'Hospice and Palliative Medicine', mapping: { kind: 'certificate', certificateId: 'hospice-palliative-medicine' } },
  { code: '2085N0700X', classification: 'Radiology', specialization: 'Neuroradiology', mapping: { kind: 'certificate', certificateId: 'neuroradiology' } },
  { code: '2085N0904X', classification: 'Radiology', specialization: 'Nuclear Radiology', mapping: { kind: 'certificate', certificateId: 'nuclear-radiology' } },
  { code: '2085P0229X', classification: 'Radiology', specialization: 'Pediatric Radiology', mapping: { kind: 'certificate', certificateId: 'pediatric-radiology' } },
  { code: '2085R0001X', classification: 'Radiology', specialization: 'Radiation Oncology', mapping: { kind: 'certificate', certificateId: 'radiation-oncology' } },
  { code: '2085R0205X', classification: 'Radiology', specialization: 'Radiological Physics', mapping: { kind: 'certificate', certificateId: 'medical-physics' } },
  { code: '2085R0203X', classification: 'Radiology', specialization: 'Therapeutic Radiology', mapping: { kind: 'certificate', certificateId: 'radiation-oncology' }, note: 'Legacy "Therapeutic Radiology" label for radiation oncology.' },
  { code: '2085R0204X', classification: 'Radiology', specialization: 'Vascular & Interventional Radiology', mapping: { kind: 'certificate', certificateId: 'interventional-radiology-diagnostic-radiology' }, note: 'Legacy Vascular & Interventional Radiology CAQ label; succeeded by the IR/DR certificate.' },
  { code: '208600000X', classification: 'Surgery', specialization: null, mapping: { kind: 'certificate', certificateId: 'general-surgery' } },
  { code: '2086H0002X', classification: 'Surgery', specialization: 'Hospice and Palliative Medicine', mapping: { kind: 'certificate', certificateId: 'hospice-palliative-medicine' } },
  { code: '2086S0120X', classification: 'Surgery', specialization: 'Pediatric Surgery', mapping: { kind: 'certificate', certificateId: 'pediatric-surgery' } },
  { code: '2086P0122X', classification: 'Surgery', specialization: 'Physician Nutrition Specialist', mapping: { kind: 'practice_focus' } },
  { code: '2086S0122X', classification: 'Surgery', specialization: 'Plastic and Reconstructive Surgery', mapping: { kind: 'certificate', certificateId: 'plastic-surgery' } },
  { code: '2086S0105X', classification: 'Surgery', specialization: 'Surgery of the Hand', mapping: { kind: 'certificate', certificateId: 'surgery-of-the-hand' } },
  { code: '2086S0102X', classification: 'Surgery', specialization: 'Surgical Critical Care', mapping: { kind: 'certificate', certificateId: 'surgical-critical-care' } },
  { code: '2086X0206X', classification: 'Surgery', specialization: 'Surgical Oncology', mapping: { kind: 'certificate', certificateId: 'complex-general-surgical-oncology' }, note: 'NUCC "Surgical Oncology" label predates the Complex General Surgical Oncology certificate (2014).' },
  { code: '2086S0127X', classification: 'Surgery', specialization: 'Trauma Surgery', mapping: { kind: 'practice_focus' } },
  { code: '2086S0129X', classification: 'Surgery', specialization: 'Vascular Surgery', mapping: { kind: 'certificate', certificateId: 'vascular-surgery' } },
  { code: '208G00000X', classification: 'Thoracic Surgery (Cardiothoracic Vascular Surgery)', specialization: null, mapping: { kind: 'certificate', certificateId: 'thoracic-cardiac-surgery' } },
  { code: '204F00000X', classification: 'Transplant Surgery', specialization: null, mapping: { kind: 'practice_focus' } },
  { code: '208800000X', classification: 'Urology', specialization: null, mapping: { kind: 'certificate', certificateId: 'urology' } },
  { code: '2088P0231X', classification: 'Urology', specialization: 'Pediatric Urology', mapping: { kind: 'certificate', certificateId: 'pediatric-urology' } },
  { code: '2088F0040X', classification: 'Urology', specialization: 'Urogynecology and Reconstructive Pelvic Surgery', mapping: { kind: 'certificate', certificateId: 'urogynecology-reconstructive-pelvic-surgery' } },
];
