'use client';

/**
 * Credential PDF Export
 *
 * Client-side PDF rendering for credentials
 */

import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import { toast } from 'sonner';

interface CredentialPdfExportProps {
  credential: {
    id: string;
    type: string;
    subject: string;
    issuer: string;
    issuedDate: string;
    expiresDate?: string;
    status: 'active' | 'revoked' | 'expired';
    data?: Record<string, any>;
  };
  className?: string;
}

export function CredentialPdfExport({ credential, className }: CredentialPdfExportProps) {
  const generatePdf = async () => {
    try {
      // Dynamically import jsPDF only when needed
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();

      // Set up document
      const pageWidth = doc.internal.pageSize.width;
      const margin = 20;
      let yPosition = 20;

      // Helper to add new page if needed
      const checkPageBreak = () => {
        if (yPosition > 280) {
          doc.addPage();
          yPosition = 20;
        }
      };

      // Title
      doc.setFontSize(20);
      doc.setTextColor(33, 37, 41);
      doc.text('Verifiable Credential', margin, yPosition);
      yPosition += 10;

      // Credential ID
      doc.setFontSize(12);
      doc.setTextColor(108, 117, 125);
      doc.text(`ID: ${credential.id}`, margin, yPosition);
      yPosition += 15;

      // Status Badge
      checkPageBreak();
      doc.setFontSize(14);
      const statusColor =
        credential.status === 'active'
          ? [40, 167, 69]
          : credential.status === 'revoked'
          ? [220, 53, 69]
          : [255, 193, 7];
      doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
      doc.text(
        `Status: ${credential.status.charAt(0).toUpperCase() + credential.status.slice(1)}`,
        margin,
        yPosition,
      );
      yPosition += 15;

      checkPageBreak();
      doc.setFontSize(12);
      doc.setTextColor(33, 37, 41);

      // Type
      doc.text(`Type: ${credential.type}`, margin, yPosition);
      yPosition += 10;

      checkPageBreak();
      doc.text(`Subject: ${credential.subject}`, margin, yPosition);
      yPosition += 10;

      checkPageBreak();
      doc.text(`Issuer: ${credential.issuer}`, margin, yPosition);
      yPosition += 10;

      checkPageBreak();
      doc.text(
        `Issued: ${new Date(credential.issuedDate).toLocaleDateString()}`,
        margin,
        yPosition,
      );
      yPosition += 10;

      if (credential.expiresDate) {
        checkPageBreak();
        doc.text(
          `Expires: ${new Date(credential.expiresDate).toLocaleDateString()}`,
          margin,
          yPosition,
        );
        yPosition += 10;
      }

      // Additional data
      if (credential.data) {
        checkPageBreak();
        yPosition += 10;
        doc.setFontSize(14);
        doc.setTextColor(33, 37, 41);
        doc.text('Credential Data:', margin, yPosition);
        yPosition += 10;

        doc.setFontSize(10);
        doc.setTextColor(108, 117, 125);
        Object.entries(credential.data).forEach(([key, value]) => {
          checkPageBreak();
          doc.text(`${key}: ${String(value)}`, margin, yPosition);
          yPosition += 8;
        });
      }

      // Footer
      const totalPages = doc.internal.pages.length - 1;
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(108, 117, 125);
        doc.text(
          `Page ${i} of ${totalPages} - Generated by VitalCV`,
          pageWidth / 2,
          doc.internal.pageSize.height - 10,
          { align: 'center' },
        );
      }

      // Save the PDF
      const fileName = `credential-${credential.id}-${credential.status}.pdf`;
      doc.save(fileName);
      toast.success('PDF downloaded successfully');
    } catch (error) {
      console.error('Error generating PDF:', error);
      toast.error('Failed to generate PDF');
    }
  };

  return (
    <Button variant="outline" size="sm" onClick={generatePdf} className={className}>
      <Download className="h-4 w-4 mr-2" />
      Export as PDF
    </Button>
  );
}
