/**
 * build-directory-sitemap-seed.ts — chooses which provider pages VitalCV asks
 * search engines to crawl.
 *
 * /directory/[npi] renders for any NPI in the federal registry. That is ~5.5M
 * URLs, and publishing all of them would be a programmatic-republishing play
 * with no editorial position — the thing search engines demote and the thing
 * that makes a company look like a data broker. So the sitemap is a deliberate,
 * reviewable subset, and this script is how the subset is chosen.
 *
 * SCOPE: the declared beachhead — advanced practice providers (NP/PA), per
 * docs/strategy/beachhead-decision.md. Not "everyone we can enumerate".
 *
 * SOURCE: the CMS Doctors & Clinicians National Downloadable File, the same
 * dataset lib/clinician-record/cmsClinicians.ts reads per record. Inclusion in
 * it means the clinician is enrolled in Medicare, which is a real fact about
 * them from CMS's own enrollment records — so the sitemap subset is defined by
 * a federal source, not by a scrape or a guess.
 *
 * WHAT THIS DOES NOT DO: it does not decide that these clinicians want a page.
 * The page exists either way, because NPPES is public record and the route is
 * open. What the sitemap changes is how fast a crawler finds it. Anyone who
 * asks to be left out goes in EXCLUDED_NPIS in lib/directory/sitemapSeed.ts,
 * which is applied at read time and cannot be undone by regenerating this file.
 *
 * Run: pnpm tsx scripts/build-directory-sitemap-seed.ts
 * Output: apps/web/lib/directory/sitemap-seed.json (committed, provenance-stamped)
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const ENDPOINT =
  'https://data.cms.gov/provider-data/api/1/datastore/query/mj5m-pzi6/0';
const DATASET = 'mj5m-pzi6';

/** The beachhead, as decided 2026-08-05. */
const SPECIALTIES = ['NURSE PRACTITIONER', 'PHYSICIAN ASSISTANT'] as const;

/**
 * Capped per (specialty, state) rather than globally, so one large state cannot
 * consume the whole budget and leave the sitemap looking like a Texas directory.
 */
const STATES = ['TX', 'CA', 'FL', 'NY', 'PA', 'OH', 'IL', 'NC', 'GA', 'MI'] as const;
const PER_BUCKET = 250;
const PAGE = 500;

const OUT = resolve(
  import.meta.dirname,
  '../apps/web/lib/directory/sitemap-seed.json',
);

interface Row {
  npi?: unknown;
  pri_spec?: unknown;
  state?: unknown;
}

function isNpi(value: unknown): value is string {
  return typeof value === 'string' && /^\d{10}$/.test(value);
}

async function fetchBucket(specialty: string, state: string): Promise<string[]> {
  const seen = new Set<string>();

  for (let offset = 0; seen.size < PER_BUCKET; offset += PAGE) {
    const params = new URLSearchParams();
    params.set('conditions[0][property]', 'pri_spec');
    params.set('conditions[0][value]', specialty);
    params.set('conditions[0][operator]', '=');
    params.set('conditions[1][property]', 'state');
    params.set('conditions[1][value]', state);
    params.set('conditions[1][operator]', '=');
    params.set('limit', String(PAGE));
    params.set('offset', String(offset));

    const res = await fetch(`${ENDPOINT}?${params}`, {
      headers: { Accept: 'application/json' },
      signal: AbortSignal.timeout(30_000),
    });
    if (!res.ok) throw new Error(`${specialty}/${state} → HTTP ${res.status}`);

    const payload = (await res.json()) as { results?: Row[] };
    const rows = Array.isArray(payload.results) ? payload.results : [];
    if (rows.length === 0) break;

    for (const row of rows) {
      // The file repeats a clinician once per practice address, so the same
      // NPI arrives many times. The Set is the dedupe.
      if (isNpi(row.npi) && seen.size < PER_BUCKET) seen.add(row.npi);
    }
  }

  return [...seen];
}

async function main() {
  const npis = new Set<string>();
  const buckets: Record<string, number> = {};

  for (const specialty of SPECIALTIES) {
    for (const state of STATES) {
      const key = `${specialty}/${state}`;
      try {
        const found = await fetchBucket(specialty, state);
        found.forEach((n) => npis.add(n));
        buckets[key] = found.length;
        process.stderr.write(`  ${key}: ${found.length}\n`);
      } catch (err) {
        // A bucket that fails is recorded as 0 rather than silently skipped —
        // a short sitemap with no explanation is how coverage quietly rots.
        buckets[key] = 0;
        process.stderr.write(`  ${key}: FAILED (${(err as Error).message})\n`);
      }
    }
  }

  const sorted = [...npis].sort();
  const seed = {
    $comment:
      'Generated by scripts/build-directory-sitemap-seed.ts. Do not hand-edit. ' +
      'To remove a clinician, add their NPI to EXCLUDED_NPIS in ' +
      'apps/web/lib/directory/sitemapSeed.ts — that list is applied at read ' +
      'time and survives regeneration of this file.',
    source: {
      name: 'CMS Doctors & Clinicians National Downloadable File',
      dataset: DATASET,
      endpoint: ENDPOINT,
      retrievedAt: new Date().toISOString(),
    },
    scope: {
      specialties: [...SPECIALTIES],
      states: [...STATES],
      perBucket: PER_BUCKET,
      rationale:
        'Declared beachhead: hospital-based advanced practice providers (docs/strategy/beachhead-decision.md).',
    },
    buckets,
    count: sorted.length,
    npis: sorted,
  };

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, `${JSON.stringify(seed, null, 2)}\n`);
  process.stderr.write(`\nwrote ${sorted.length} NPIs → ${OUT}\n`);
}

main().catch((err) => {
  process.stderr.write(`${(err as Error).stack}\n`);
  process.exit(1);
});
