import { NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { logEvent } from "../../../../../lib/events";

const NPI_PATTERN = /^\d{10}$/;

/**
 * GET /api/artifact/export/:npi
 *
 * Generate a credential artifact PDF for the given NPI.
 * Mock data — same deterministic logic as the NPI lookup.
 */
export async function GET(
  _request: Request,
  { params }: { params: Promise<{ npi: string }> },
): Promise<NextResponse | Response> {
  const { npi } = await params;

  if (!NPI_PATTERN.test(npi)) {
    return NextResponse.json(
      { error: "NPI must be exactly 10 digits" },
      { status: 400 },
    );
  }

  const exists = npi.startsWith("1");
  if (!exists) {
    return NextResponse.json(
      { error: "NPI not found" },
      { status: 404 },
    );
  }

  // Fire-and-forget event logging
  void logEvent("artifact_exported", npi);

  const now = new Date();
  const timestamp = now.toISOString();
  const dateStr = now.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // ── Generate PDF ──
  const doc = new PDFDocument({ size: "LETTER", margin: 72 });
  const chunks: Buffer[] = [];

  doc.on("data", (chunk: Buffer) => chunks.push(chunk));

  const pdfReady = new Promise<Buffer>((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });

  // Header
  doc
    .fontSize(22)
    .font("Helvetica-Bold")
    .text("VitalCV — Credential Artifact", { align: "center" });

  doc.moveDown(0.5);
  doc
    .fontSize(10)
    .font("Helvetica")
    .fillColor("#666666")
    .text(`Generated ${dateStr}`, { align: "center" });

  doc.moveDown(1.5);

  // Divider
  doc
    .moveTo(72, doc.y)
    .lineTo(540, doc.y)
    .strokeColor("#e5e7eb")
    .stroke();

  doc.moveDown(1);

  // Credential fields
  doc.fillColor("#000000");

  const fields: [string, string][] = [
    ["NPI", npi],
    ["License", `State Medical License — Active`],
    ["Source", "NPPES (mock)"],
    ["Timestamp", timestamp],
    ["Status", "Verified — Active"],
    ["Monitoring", "Continuous monitoring enabled"],
    ["Signature", `ES256 — sha256:${npi.slice(0, 8)}...mock`],
  ];

  for (const [label, value] of fields) {
    doc.fontSize(10).font("Helvetica-Bold").text(label, { continued: false });
    doc
      .fontSize(10)
      .font("Helvetica")
      .fillColor("#374151")
      .text(value);
    doc.fillColor("#000000");
    doc.moveDown(0.6);
  }

  doc.moveDown(1);

  // Footer divider
  doc
    .moveTo(72, doc.y)
    .lineTo(540, doc.y)
    .strokeColor("#e5e7eb")
    .stroke();

  doc.moveDown(0.5);

  doc
    .fontSize(8)
    .font("Helvetica")
    .fillColor("#9ca3af")
    .text(
      "This document is a mock credential artifact generated by VitalCV. " +
        "Production artifacts will include cryptographic signatures anchored to " +
        "verifiable credential infrastructure (OpenID4VCI / HAIP 1.0).",
      { align: "center" },
    );

  doc.end();

  const pdfBuffer = await pdfReady;

  return new Response(new Uint8Array(pdfBuffer), {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="vitalcv-artifact-${npi}.pdf"`,
      "Content-Length": String(pdfBuffer.length),
    },
  });
}
