export const themeTypography = {
  family: {
    sans: `var(--font-nunito-sans), 'Nunito Sans', system-ui, sans-serif`,
    body: `var(--font-nunito-sans), 'Nunito Sans', system-ui, sans-serif`,
    heading: `var(--font-nunito-sans), 'Nunito Sans', system-ui, sans-serif`,
    mono: `'JetBrains Mono', 'SFMono-Regular', ui-monospace, monospace`,
    canvas: `'Nunito Sans', system-ui, sans-serif`,
  },
  size: {
    xs: '0.75rem',
    sm: '0.875rem',
    base: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.875rem',
    '4xl': '2.25rem',
    '5xl': '3rem',
    '6xl': '3.75rem',
    '7xl': '4.5rem',
    '8xl': '6rem',
    '9xl': '8rem',
  },
  lineHeight: {
    none: '1',
    tight: '1.15',
    snug: '1.3',
    normal: '1.5',
    relaxed: '1.65',
    loose: '1.85',
  },
  spacing: {
    px: '1px',
    0: '0',
    0.5: '0.125rem',
    1: '0.25rem',
    1.5: '0.375rem',
    2: '0.5rem',
    3: '0.75rem',
    4: '1rem',
    5: '1.25rem',
    6: '1.5rem',
    8: '2rem',
    10: '2.5rem',
    12: '3rem',
    16: '4rem',
    20: '5rem',
    24: '6rem',
    32: '8rem',
    40: '10rem',
    48: '12rem',
    64: '16rem',
  },
} as const;

export type ThemeTypography = typeof themeTypography;
