import type {
  IntelligenceTone,
  IntelligenceActionWorkflowEffects,
  IntelligenceRecommendationDecision,
} from './contracts';
import type { EmploymentGraph } from './employment-graph';

export interface InvestigatorFindingEntity {
  entityType: string;
  entityId: string;
  entityLabel?: string | null;
  relationship?: string | null;
  metadata?: Record<string, unknown>;
}

export interface InvestigatorFindingEvidence {
  evidenceId: string;
  evidenceType: string;
  sourceId?: string | null;
  sourceLabel?: string | null;
  recordType?: string | null;
  recordId?: string | null;
  url?: string | null;
  snippet?: string | null;
  observedAt?: string | null;
  confidence?: number | null;
  relevance?: number | null;
  metadata?: Record<string, unknown>;
}

export interface InvestigatorFindingStatusEvent {
  fromStatus: string | null;
  toStatus: string;
  actorId?: string | null;
  note?: string | null;
  metadata?: Record<string, unknown>;
  createdAt: string;
}

export interface InvestigatorFindingDetail {
  findingId: string;
  investigatorId: string;
  findingType: string;
  scope: string;
  severity: string;
  title: string;
  summary: string;
  entityIds: string[];
  entities: InvestigatorFindingEntity[];
  supportingEvidence: InvestigatorFindingEvidence[];
  confidence: number;
  explanation: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  firstSeenAt: string;
  lastSeenAt: string;
  occurrenceCount: number;
  priorityScore: number;
  storylineKey: string;
  storylineId?: string | null;
  storylineTitle?: string | null;
  audienceRoles: string[];
  metadata: Record<string, unknown>;
  statusEvents: InvestigatorFindingStatusEvent[];
}

export interface InvestigatorFindingDetailResponse {
  finding: InvestigatorFindingDetail;
  relatedStoryline?: {
    storylineId: string;
    title: string;
    severity: string;
    status: string;
    recommendedActions?: string[];
  } | null;
}

export interface StorylineTimelineEvent {
  eventKey: string;
  type: string;
  summary: string;
  occurredAt: string;
  findingIds: string[];
  fromStatus?: string;
  toStatus?: string;
  metadata: Record<string, unknown>;
}

export interface StorylineActionEvent {
  eventKey: string;
  actionType: string;
  actorId: string | null;
  note: string | null;
  payload: Record<string, unknown>;
  occurredAt: string;
}

export interface StorylineFindingLink {
  findingId: string;
  findingCategory: string;
  findingSeverity: string;
  observedAt: string;
  weight: number;
  snapshot: Record<string, unknown>;
}

export interface StorylineEntityLink {
  entityType: string;
  entityKey: string;
  entityLabel: string | null;
  weight: number;
  firstSeenAt: string;
  lastSeenAt: string;
}

export interface StorylineDetailResponse {
  storyline: {
    storylineId: string;
    fingerprint: string;
    storylineType: string;
    perspective: string;
    title: string;
    summary: string;
    whyItMatters: string;
    recommendedActions: string[];
    severity: string;
    confidence: number;
    entityIds: string[];
    findingIds: string[];
    supportingEvidence: Array<{
      bullet: string;
      source: string;
      sourceLabel?: string | null;
      confidence: number;
      observedAt: string;
      findingId?: string;
      artifactId?: string;
    }>;
    createdAt: string;
    updatedAt: string;
    lastActivityAt: string;
    status: string;
    progressionScore: number;
    noveltyScore: number;
    persistenceScore: number;
    escalationThreshold: number;
    timeline: {
      originEvent: StorylineTimelineEvent;
      events: StorylineTimelineEvent[];
      quietPeriods: number;
      reactivations: number;
      lastEventAt: string;
      lastActivityAt: string;
      currentStatus: string;
    };
    metadata: Record<string, unknown>;
  };
  findingLinks: StorylineFindingLink[];
  entityLinks: StorylineEntityLink[];
  statusEvents: StorylineTimelineEvent[];
  actionEvents: StorylineActionEvent[];
}

export interface ActionStatusEvent {
  fromStatus: string | null;
  toStatus: string;
  actorId: string | null;
  note: string | null;
  metadata: Record<string, unknown>;
  createdAt: string;
}

export interface ActionDetailResponse {
  action: {
    actionId: string;
    actionType: string;
    targetEntity: {
      entityType: string;
      entityId: string;
      entityLabel: string | null;
    };
    recommendedAction: string;
    priority: string;
    priorityScore: number;
    confidence: number;
    explanation: string;
    createdAt: string;
    updatedAt: string;
    status: string;
    recommendationLabel?: string | null;
    recommendationConfidence?: number | null;
    workflowEffects?: IntelligenceActionWorkflowEffects | null;
    autoGenerated?: boolean;
    previewDecision?: IntelligenceRecommendationDecision | null;
    storylineKey: string | null;
    sourceFindingIds: string[];
    predictionIds: string[];
    evidence: Array<{
      label: string;
      snippet: string | null;
      source: string | null;
    }>;
    metadata: Record<string, unknown>;
    executedAt: string | null;
    dismissedAt: string | null;
    savedAt: string | null;
    dueAt?: string | null;
    statusEvents?: ActionStatusEvent[];
    linkedPredictions?: Array<{
      predictionId: string;
      predictionType: string;
      targetEntity: {
        entityType: string;
        entityId: string;
        entityLabel: string | null;
      };
      probability: number;
      confidence: number;
      timeHorizon: string;
      evidenceSignals: Array<{
        label: string;
        value: string | number | boolean | null;
      }>;
      explanation: string;
      createdAt: string;
      updatedAt: string;
      metadata: Record<string, unknown>;
    }>;
  };
}

export interface PublicProviderProfile {
  npi: string;
  status: 'CLEARED' | 'PENDING';
  trustBand: string;
  readinessScore: number;
  lastAnchored: string | null;
  activeCredentials: string[];
  readiness: {
    evaluated: boolean;
    isEligible: boolean | null;
    missingRequirements: string[];
    traceCount: number;
  };
  artifactSummaries: Array<{
    artifactId: string;
    issuer: string;
    status: string;
    lifecycleState: string;
    verifiedAt: string;
    expiresAt: string | null;
    monitoring: boolean;
    checksum: string;
    claimCount: number;
    claimHashes: string[];
    selectiveDisclosure: {
      algorithm: string;
      hashAlgorithm: string;
      claimCount: number;
    } | null;
  }>;
  issuerProvenance: Array<{
    issuer: string;
    artifactCount: number;
    latestVerifiedAt: string;
    monitored: boolean;
    statuses: string[];
  }>;
  monitoringSummary: {
    monitoredArtifactCount: number;
    totalArtifactCount: number;
    coverageRate: number;
    activeAlertCount: number;
    latestAlertAt: string | null;
  };
  proof: {
    jsonUrl: string;
    pdfUrl: string;
    auditBundleJson: string;
    auditBundleDownload: string;
  };
  events: Array<{
    type: string;
    hash: string;
    createdAt: string;
  }>;
  generatedAt: string;
}

export interface ProviderDetailResponse {
  provider: {
    npi: string;
    fullName: string;
    providerType: string | null;
    credential: string | null;
    npiStatus: string | null;
    enumerationType: string | null;
    specialties: string[];
    identifiers: Array<{
      label: string;
      value: string;
    }>;
    locations: Array<{
      label: string;
      state: string | null;
    }>;
    trustScore: number;
    readinessScore: number;
    riskScore: number;
    riskLevel: IntelligenceTone;
    findingCount: number;
    activeStorylineCount: number;
    totalCredentialCount: number;
    activeCredentialCount: number;
  };
  employmentGraph: EmploymentGraph;
  profile: PublicProviderProfile;
  credentials: Array<{
    id: string;
    type: string;
    name: string;
    issuer: string;
    status: string;
    verifiedAt: string | null;
    expiresAt: string | null;
    isPublic: boolean;
  }>;
  findings: Array<{
    findingId: string;
    title: string;
    severity: string;
    status: string;
    updatedAt: string;
  }>;
  storylines: Array<{
    storylineId: string;
    title: string;
    severity: string;
    status: string;
    lastActivityAt: string;
  }>;
  actions: Array<{
    actionId: string;
    recommendedAction: string;
    priority: string;
    status: string;
    createdAt: string;
  }>;
  signals?: {
    npi: string;
    providerId: string;
    providerLabel: string;
    specialty: string | null;
    geography: string | null;
    trust: {
      score: number | null;
      tier: string;
      confidence: number;
      drivers: Array<{
        label: string;
        value: number | string;
        direction: string;
        source: string;
        explanation: string;
      }>;
      sourceSignals: string[];
      last_updated: string;
      explanation: string;
      insufficientSignal: boolean;
    };
    influence: {
      score: number | null;
      percentile: number | null;
      tier: string;
      confidence: number;
      drivers: Array<{
        label: string;
        value: number | string;
        direction: string;
        source: string;
        explanation: string;
      }>;
      sourceSignals: string[];
      centrality_delta: number | null;
      last_updated: string;
      explanation: string;
      insufficientSignal: boolean;
    };
    workforcePressure: {
      state: string;
      score: number | null;
      confidence: number;
      drivers: Array<{
        label: string;
        value: number | string;
        direction: string;
        source: string;
        explanation: string;
      }>;
      sourceSignals: string[];
      geography: string | null;
      specialty: string | null;
      last_updated: string;
      explanation: string;
      insufficientSignal: boolean;
    };
    institutionMomentum: {
      institutionId: string;
      institutionLabel: string;
      state: string;
      score: number | null;
      confidence: number;
      trend_summary: string;
      last_updated: string;
      explanation: string;
      insufficientSignal: boolean;
    } | null;
    earlyWarnings: Array<{
      id: string;
      headline: string;
      type: string;
      state: string;
      score: number | null;
      confidence: number;
      timestamp: string;
      explanation: string;
      recommendedAction: string;
    }>;
    feed: {
      generatedAt: string;
      total: number;
      counts: {
        finding: number;
        storyline: number;
        prediction: number;
        insight: number;
        early_warning: number;
      };
      items: Array<{
        id: string;
        headline: string;
        type: string;
        explanation: string;
        confidence: number;
        recommendedAction: string | null;
        created_at: string;
        state: string | null;
        score: number | null;
      }>;
    };
    summary: string;
    generatedAt: string;
  } | null;
  intelligence?: {
    generatedAt: string;
    entity: {
      entityType: string;
      entityId: string;
      entityLabel: string | null;
    };
    trustScore: {
      id: string;
      type: string;
      state: string;
      score: number;
      lastUpdated: string;
      explanation: {
        summary: string;
        details: string[];
      };
    } | null;
    influenceScore: {
      id: string;
      type: string;
      state: string;
      score: number;
      lastUpdated: string;
      explanation: {
        summary: string;
        details: string[];
      };
    } | null;
    trajectorySignals: Array<{
      id: string;
      type: string;
      state: string;
      score: number;
      lastUpdated: string;
      explanation: {
        summary: string;
        details: string[];
      };
    }>;
    recentWarnings: Array<{
      id: string;
      type: string;
      state: string;
      score: number;
      lastUpdated: string;
      explanation: {
        summary: string;
        details: string[];
      };
    }>;
    recentFeed: Array<{
      id: string;
      type: string;
      headline: string;
      summary: string;
      createdAt: string;
      updatedAt: string;
    }>;
    recentFindings: Array<{
      id: string;
      type: string;
      headline: string;
      summary: string;
      createdAt: string;
      updatedAt: string;
    }>;
    recentStorylines: Array<{
      id: string;
      type: string;
      headline: string;
      summary: string;
      createdAt: string;
      updatedAt: string;
    }>;
    recommendedWatchItems: string[];
  } | null;
}
