'use client';

import { useMemo, useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Separator } from '@/components/ui/separator';
import { cn } from '@/lib/utils';
import { AlertTriangle, ArrowRight, CheckCircle2, Clock, FileText, Loader2, RefreshCcw } from 'lucide-react';

export type RemediationSeverity = 'critical' | 'high' | 'medium' | 'low';

export interface RemediationActionEvidence {
  id: string;
  label: string;
  type: 'PSV' | 'PECOS' | 'CAQH' | 'DRIFT' | 'NOTE' | 'OTHER';
  reference?: string;
}

export interface RemediationAction {
  id: string;
  title: string;
  description: string;
  severity: RemediationSeverity;
  dueDate?: string;
  recommendedBy: string;
  workflow: 'license' | 'pecos' | 'caqh' | 'drift' | 'compliance';
  evidence: RemediationActionEvidence[];
  ctaLabel?: string;
}

export interface RemediationActionsProps {
  actions?: RemediationAction[];
  onActionLaunched?: (action: RemediationAction) => void;
}

const DEFAULT_ACTIONS: RemediationAction[] = [
  {
    id: 'renew-license-wa',
    title: 'Renew Washington state license',
    description: 'Agent detected an expiring license in 27 days. Renewal packet can be auto-populated.',
    severity: 'critical',
    dueDate: new Date(Date.now() + 27 * 24 * 60 * 60 * 1000).toISOString(),
    recommendedBy: 'Auto-PSV drift watch',
    workflow: 'license',
    evidence: [
      { id: 'psv-8842', label: 'PSV verify 10/29', type: 'PSV' },
      { id: 'drift-2025-11-A', label: 'Drift ticket DR-2025-11-A', type: 'DRIFT' },
    ],
    ctaLabel: 'Launch Renewal Wizard',
  },
  {
    id: 'update-caqh',
    title: 'Update CAQH attestation',
    description: 'CAQH profile is stale (93 days). Agent can sync DEA and training docs automatically.',
    severity: 'high',
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    recommendedBy: 'CAQH monitor',
    workflow: 'caqh',
    evidence: [
      { id: 'caqh-profile', label: 'CAQH profile extract', type: 'CAQH' },
    ],
    ctaLabel: 'Start CAQH Sync',
  },
  {
    id: 'refresh-pecos',
    title: 'Refresh PECOS enrollment evidence',
    description: 'PECOS auto-sync picked up payer edits; export updated 855 data to committee packet.',
    severity: 'medium',
    recommendedBy: 'PECOS watcher',
    workflow: 'pecos',
    evidence: [
      { id: 'pecos-evidence', label: 'PECOS evidence bundle', type: 'PECOS' },
    ],
    ctaLabel: 'Queue PECOS Pull',
  },
  {
    id: 'resolve-drift',
    title: 'Resolve credential drift summary',
    description: 'Finalize the drift remediation summary before sending to compliance.',
    severity: 'low',
    recommendedBy: 'Drift engine',
    workflow: 'drift',
    evidence: [
      { id: 'drift-report', label: 'Drift report 11.09', type: 'DRIFT' },
      { id: 'notes-17', label: 'Analyst note by L. Chen', type: 'NOTE' },
    ],
    ctaLabel: 'Mark Drift Resolved',
  },
];

const severityCopy: Record<RemediationSeverity, { label: string; badgeClass: string; icon: typeof AlertTriangle }> = {
  critical: { label: 'Critical', badgeClass: 'border-red-500 text-red-600', icon: AlertTriangle },
  high: { label: 'High', badgeClass: 'border-amber-500 text-amber-600', icon: AlertTriangle },
  medium: { label: 'Medium', badgeClass: 'border-blue-500 text-blue-600', icon: Clock },
  low: { label: 'Low', badgeClass: 'border-slate-300 text-slate-500', icon: Clock },
};

export function RemediationActions({ actions = DEFAULT_ACTIONS, onActionLaunched }: RemediationActionsProps) {
  const [runningActionId, setRunningActionId] = useState<string | null>(null);
  const [completed, setCompleted] = useState<Set<string>>(new Set());

  const completionPercent = useMemo(() => {
    if (actions.length === 0) {
      return 0;
    }
    return Math.round(((completed.size ?? 0) / actions.length) * 100);
  }, [actions.length, completed]);

  const handleLaunch = async (action: RemediationAction) => {
    setRunningActionId(action.id);
    await new Promise((resolve) => setTimeout(resolve, 600));
    setCompleted((prev) => {
      const next = new Set(prev);
      next.add(action.id);
      return next;
    });
    setRunningActionId(null);
    onActionLaunched?.(action);
  };

  return (
    <Card className="shadow-sm" aria-live="polite">
      <CardHeader>
        <CardTitle className="flex items-center justify-between">
          <span>Agent remediation queue</span>
          <Badge variant="outline" className="text-xs">
            {actions.length} open
          </Badge>
        </CardTitle>
        <CardDescription>Recommended fixes generated by the credentialing agent.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-5">
        <div>
          <div className="mb-2 flex items-center justify-between text-sm">
            <span className="text-muted-foreground">Queue completion</span>
            <span className="font-medium">{completionPercent}%</span>
          </div>
          <Progress value={completionPercent} aria-label="Completion percentage" />
        </div>

        <div className="space-y-4">
          {actions.map((action) => {
            const severity = severityCopy[action.severity];
            const isRunning = runningActionId === action.id;
            const isDone = completed.has(action.id);
            const Icon = severity.icon;

            return (
              <div
                key={action.id}
                className={cn(
                  'rounded-lg border bg-card/60 p-4 transition hover:border-primary/40',
                  isDone && 'border-emerald-400/70 bg-emerald-50/60'
                )}
              >
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div>
                    <div className="flex items-center gap-2">
                      <Badge variant="outline" className={severity.badgeClass}>
                        {severity.label}
                      </Badge>
                      {action.dueDate && (
                        <span className="text-xs text-muted-foreground">
                          Due {new Date(action.dueDate).toLocaleDateString()}
                        </span>
                      )}
                    </div>
                    <h3 className="mt-2 text-base font-semibold">{action.title}</h3>
                    <p className="text-sm text-muted-foreground">{action.description}</p>
                  </div>
                  <Button
                    size="sm"
                    variant={isDone ? 'secondary' : 'default'}
                    disabled={isRunning}
                    onClick={() => handleLaunch(action)}
                  >
                    {isRunning ? (
                      <>
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" /> Launching...
                      </>
                    ) : isDone ? (
                      <>
                        <CheckCircle2 className="mr-2 h-4 w-4" /> Workflow sent
                      </>
                    ) : (
                      <>
                        <ArrowRight className="mr-2 h-4 w-4" /> {action.ctaLabel ?? 'Trigger workflow'}
                      </>
                    )}
                  </Button>
                </div>

                <Separator className="my-3" />

                <dl className="grid gap-3 text-sm sm:grid-cols-3" aria-label="Evidence references">
                  <div>
                    <dt className="text-muted-foreground">Recommended by</dt>
                    <dd className="font-medium">{action.recommendedBy}</dd>
                  </div>
                  <div>
                    <dt className="text-muted-foreground">Workflow</dt>
                    <dd className="font-medium capitalize">{action.workflow}</dd>
                  </div>
                  <div>
                    <dt className="text-muted-foreground">Evidence</dt>
                    <dd className="flex flex-wrap gap-2 pt-1">
                      {action.evidence.map((evidence) => (
                        <Badge key={evidence.id} variant="secondary" className="flex items-center gap-1 text-xs">
                          <FileText className="h-3.5 w-3.5" />
                          {evidence.label}
                        </Badge>
                      ))}
                    </dd>
                  </div>
                </dl>
              </div>
            );
          })}
        </div>

        <div className="rounded-lg border bg-muted/40 p-3 text-sm text-muted-foreground">
          <p className="flex items-center gap-2">
            <RefreshCcw className="h-4 w-4" />
            Buttons trigger the appropriate agent workflow and push an immutable timeline event with supporting evidence.
          </p>
        </div>
      </CardContent>
    </Card>
  );
}
